ko6: src/soft/hal/cpu/atomic.h File Reference
atomic.h File Reference
Typedefs
typedef unsigned spinlock_t
Functions
void spin_lock (spinlock_t *lock)
get the lock, block until success
void spin_unlock (spinlock_t *lock)
release the lock
int atomic_add (int *counter, int val)
add a value to the pointed value, block until success
Typedef Documentation
spinlock_t
typedef unsigned spinlock_t
Same as for the IRQs and some drivers, the function here are marked extern because they need to be implemented at some point by a platform-specific file It's a simple word, but it is forbidden to read it directly to not copy it in cache
Function Documentation
atomic_add()
int atomic_add (int * counter, int val)
add a value to the pointed value, block until success
Parameters
counter pointer to change
val value to add
Returns
the new value
spin_lock()
void spin_lock (spinlock_t * lock)
get the lock, block until success
Parameters
lock blocking function until lock is free
Referenced by thread_barrier_destroy(), thread_barrier_init(), thread_barrier_wait(), thread_exit(), thread_join(), thread_mutex_lock(), thread_mutex_unlock(), thread_notify(), and thread_wait().
spin_unlock()
void spin_unlock (spinlock_t * lock)
release the lock
Parameters
lock freeing the lock
Referenced by thread_barrier_destroy(), thread_barrier_wait(), thread_exit(), thread_join(), thread_mutex_lock(), thread_mutex_unlock(), thread_notify(), and thread_wait().