ko6: src/soft/uapp/barrier/main.c File Reference
main.c File Reference
#include <libc.h>
#include <pthread.h>
Classes
struct arg_s
Macros
#define DELAY(n) for(int i=n;i--;) __asm__("nop");
Functions
void * t0_fun (void *arg)
int main (void)
Variables
pthread_t t0
pthread_t t1
struct arg_s a0 a1
pthread_barrier_t barrier
Macro Definition Documentation
DELAY
#define DELAY (n) for(int i=n;i--;) __asm__("nop");
Function Documentation
main()
int main (void)
{
    pthread_barrier_init (&barrier, NULL, 3);
    a0.delay = 100000;
    a0.message = "bonjour";
    a1.delay = 500000;
    a1.message = "salut";
    pthread_create (&t0, NULL, t0_fun, &a0);
    pthread_create (&t0, NULL, t0_fun, &a1);
    for (int i=0;1;i++) {
        fprintf (0, "[%d] app is alive\n", i);
        DELAY(100000);
        //thread_barrier_wait( &barrier);
    }
    void * trash;
    pthread_join (t1, &trash);
    pthread_join (t0, &trash);
    return 0;
}
References a1, barrier, DELAY, arg_s::delay, fprintf(), arg_s::message, NULL, pthread_barrier_init(), pthread_create(), pthread_join(), t0, t0_fun(), and t1.
t0_fun()
void * t0_fun (void * arg)
{
    struct arg_s * a = arg;
    for (int i=0;1;i++) {
        fprintf (1, "[%d] %s\n", i, a->message);
        DELAY ((a->delay) * (1 + rand()%2));
        //thread_barrier_wait (&barrier);
    };
}
References DELAY, arg_s::delay, fprintf(), arg_s::message, and rand().
Referenced by main().
Variable Documentation
a1
struct arg_s a0 a1
Referenced by main(), and unknown_syscall().
barrier
pthread_barrier_t barrier
Referenced by main(), pthread_barrier_destroy(), pthread_barrier_init(), pthread_barrier_wait(), thread_barrier_destroy(), thread_barrier_init(), and thread_barrier_wait().
t0
pthread_t t0
Referenced by main().
t1
pthread_t t1
Referenced by main().