ko6: src/soft/hal/cpu/cache.h File Reference
cache.h File Reference
Functions
size_t cachelinesize (void)
get the cache line size in bytes
void dcache_buf_invalidate (void *buf, unsigned size)
invalidate all line of the buffer buf
void dcache_invalidate (void *addr)
invalidate all line of the buffer buf
unsigned uncached_load (void *addr)
get the value pointed by addr without use the cache this function must be used for all shared variables between several cpu
Function Documentation
cachelinesize()
size_t cachelinesize (void)
get the cache line size in bytes
Returns
the size
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CACHELINESIZE);
}
References SYSCALL_CACHELINESIZE, and syscall_fct().
Referenced by malloc_init(), and memory_init().
dcache_buf_invalidate()
void dcache_buf_invalidate (void * buf, unsigned size)
invalidate all line of the buffer buf
Parameters
buf first address
size of buffer in bytes
Referenced by dcache_buf_inval_user(), and soclib_dma_memcpy().
dcache_invalidate()
void dcache_invalidate (void * addr)
invalidate all line of the buffer buf
Parameters
addr address to invalidate
Referenced by dcache_inval_user().
uncached_load()
unsigned uncached_load (void * addr)
get the value pointed by addr without use the cache this function must be used for all shared variables between several cpu
Returns
the pointed value