ko6: src/soft/hal/cpu/irq.h File Reference
irq.h File Reference
Functions
void irq_enable (void)
enable irq (do not change the MIPS mode thus stay in kernel mode)
unsigned irq_disable (void)
disable irq
Function Documentation
irq_disable()
unsigned irq_disable (void)
disable irq
Referenced by __attribute__(), ns16550_read(), and soclib_tty_read().
irq_enable()
void irq_enable (void)
enable irq (do not change the MIPS mode thus stay in kernel mode)
Generic IRQs functions
Referenced by __attribute__(), ns16550_read(), and soclib_tty_read().