ko6: src/soft/hal/cpu/cpuregs.h File Reference
cpuregs.h File Reference
Functions
unsigned clock (void)
clock cycle counter
unsigned cpuid (void)
cpu identifier
Function Documentation
clock()
unsigned clock (void)
clock cycle counter
Returns
the number of cycles from the reset
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CLOCK);
}
References SYSCALL_CLOCK, and syscall_fct().
Referenced by delay(), sched_dump(), and sched_insert().
cpuid()
unsigned cpuid (void)
cpu identifier
Returns
the current cpu identifier from 0 to NCPUS-1
Referenced by isrcall(), plic_acknowledge(), plic_get_highest(), plic_mask(), and plic_unmask().