ko6: src/soft/ulib/crt0.c File Reference
crt0.c File Reference
#include <libc.h>
#include <pthread.h>
Functions
int main (void)
static void _start (void)
__attribute__ ((section(".usermem")))
Variables
int __bss_origin
int __bss_end
int __data_end
Function Documentation
__attribute__()
__attribute__ ((section(".usermem")))
                      {
    .ustack_end   = &__data_end,// at the begining there is no stack.
    .ustack_beg   = &__data_end,// last address of the free user data region
    .uheap_beg    = &__bss_end ,// first address of the free user data region
    .uheap_end    = &__bss_end ,// at the begining there is no heap.
    .main_thread  = NULL       ,// initialized by thread_create() in kernel/kinit.c
    .main_start   = _start      // _start function of the process
};
References __bss_end, __data_end, _start(), NULL, and _usermem_s::ustack_end.
_start()
void _start (void) static
{
    int res;
//    urandseed = 1;
    for (int *a = &__bss_origin; a != &__bss_end; *a++ = 0);
    malloc_init (_usermem.uheap_beg);
    res = main ();
    exit (res);
}
References __bss_end, __bss_origin, _usermem, exit(), main(), malloc_init(), and _usermem_s::uheap_beg.
Referenced by __attribute__().
main()
int main (void)
{
    pthread_barrier_init (&barrier, NULL, 3);
    a0.delay = 100000;
    a0.message = "bonjour";
    a1.delay = 500000;
    a1.message = "salut";
    pthread_create (&t0, NULL, t0_fun, &a0);
    pthread_create (&t0, NULL, t0_fun, &a1);
    for (int i=0;1;i++) {
        fprintf (0, "[%d] app is alive\n", i);
        DELAY(100000);
        //thread_barrier_wait( &barrier);
    }
    void * trash;
    pthread_join (t1, &trash);
    pthread_join (t0, &trash);
    return 0;
}
References a1, barrier, DELAY, arg_s::delay, fgets(), fprintf(), arg_s::message, NULL, pthread_barrier_init(), pthread_create(), pthread_join(), strlen(), t0, t0_fun(), and t1.
Referenced by _start().
Variable Documentation
__bss_end
int __bss_end extern
Referenced by __attribute__(), and _start().
__bss_origin
int __bss_origin extern
Referenced by _start(), and kinit().
__data_end
int __data_end extern
Referenced by __attribute__().