ko6: src/soft/common/cstd.c File Reference
cstd.c File Reference
#include <common/cstd.h>
Functions
void wzero (void *addr, size_t n)
write 0 in a buffer
void * memset (void *s, int c, unsigned n)
set every byte in a buffer to a same value
void * memcpy (char *dest, const char *src, unsigned n)
copies buffer src to the buffer dest (the buffers must be disjoints)
int memcmp (const void *str1, const void *str2, size_t n)
compare two buffers byte per byte
void * memmove (void *dest, const void *src, size_t n)
copies buffer src to the buffer dest (the buffers can overlap)
void * memchr (const void *src, int c, size_t n)
search byte in buffer
int strlen (const char *buf)
calculates the length of the string s, excluding the terminating null byte
size_t strnlen (const char *s, size_t n)
calculates the length of the string s, excluding the terminating null byte, up to the value n
char * strchr (const char *s, int c)
returns a pointer to the first occurrence of a character in a null-terminated string
char * strrchr (const char *s, int c)
returns a pointer to the last occurrence of a character in a null-terminated string
void * strncpy (char *dest, char *src, unsigned n)
copies the string src, included the ending byte '\0', to the buffer dest
int strcmp (const char *s1, const char *s2)
compare two null-terminated strings
int atoi (char *val)
ascii to integer the number can be negative, the space at beginning are ignored
int vsnprintf (char *buffer, unsigned size, char *fmt, va_list ap)
write a formated string to the str buffer this a simplified version which handles only: c, s, $d, x and p
int snprintf (char *str, unsigned size, char *fmt,...)
write a formated string to the str buffer this a simplified version which handles only: c, s, $d, x and p
unsigned long int strtoul (char *s, char **endptr, int base)
convert a string into an unsigned 32bit number
Variables
static char xdigit [] = "0123456789abcdef"
Function Documentation
atoi()
int atoi (char * val)
ascii to integer the number can be negative, the space at beginning are ignored
Parameters
val string to translate, with a decimal number
Returns
the integer corresponding to val
{
    int res = 0;
    int neg = 0;
    while ((*val == ' ') || (*val == '\t'))     // look for the first non-space character
        val++;
    if (*val == '-') {                          // if negative
        neg = 1;                                // register it
        val++;                                  // go to the first real number
    } else {
        neg = 0;                                // it is positive
    }
    while (*val) {                              // while there is a char
        res = (res * 10) + (*val - '0');        // add  to the result
        val++;
    }
    return (neg) ? -res : res;                  // return the right result
}
Referenced by getoption().
memchr()
void * memchr (const void * src, int c, size_t n)
search byte in buffer
Parameters
src buffer
c byte to search
n number of bytes to check in the buffer
Returns
pointer to the byte in buffer if found, NULL else
{
    const unsigned char *csrc = (const unsigned char *)src;
    while (n-- > 0) {
        if (*csrc == c)
            return (void *)csrc;
        csrc++;
    }
    return NULL;
}
References NULL.
Referenced by fdt_get_string(), fdt_nodename_eq_(), fdt_path_offset_namelen(), fdt_stringlist_contains(), overlay_fixup_phandle(), and overlay_symbol_update().
memcmp()
int memcmp (const void * str1, const void * str2, size_t n)
compare two buffers byte per byte
Parameters
str1 first buffer
str2 second buffer
n number of bytes to compare
{
    const unsigned char *s1 = (const unsigned char*)str1;
    const unsigned char *s2 = (const unsigned char*)str2;
    while (n-- > 0) {
        if (*s1++ != *s2++)
            return s1[-1] < s2[-1] ? -1 : 1;
    }
    return 0;
}
Referenced by fdt_find_string_(), fdt_node_offset_by_prop_value(), fdt_nodename_eq_(), fdt_string_eq_(), fdt_stringlist_contains(), fdt_stringlist_search(), and overlay_symbol_update().
memcpy()
void * memcpy (char * dest, const char * src, unsigned n)
copies buffer src to the buffer dest (the buffers must be disjoints)
Parameters
dest destination buffer
src source buffer
n number of bytes to copy
Returns
the dest buffer address
{
    char *d = dest;
    while (n--)
        *d++ = *src++;
    return dest;
}
Referenced by dma_memcpy_user(), fdt_add_string_(), fdt_add_subnode_namelen(), fdt_appendprop(), fdt_begin_node(), fdt_find_add_string_(), fdt_get_path(), fdt_property(), fdt_set_name(), fdt_setprop(), fdt_setprop_inplace_namelen_partial(), overlay_symbol_update(), and overlay_update_local_node_references().
memmove()
void * memmove (void * dest, const void * src, size_t n)
copies buffer src to the buffer dest (the buffers can overlap)
Parameters
dest destination buffer
src source buffer
n number of bytes to copy
Returns
the dest buffer address
{
    if (dest < src) {
        const char *firsts = (const char *) src;
        char *firstd = (char *) dest;
        while (n--)
            *firstd++ = *firsts++;
    } else {
        const char *lasts = (const char *)src + (n-1);
        char *lastd = (char *)dest + (n-1);
        while (n--)
            *lastd-- = *lasts--;
    }
    return dest;
}
Referenced by fdt_finish(), fdt_move(), fdt_open_into(), fdt_packblocks_(), fdt_resize(), fdt_splice_(), and kfs_absolute_pathname().
memset()
void * memset (void * s, int c, unsigned n)
set every byte in a buffer to a same value
Parameters
s buffer address
c value to write
n number of bytes to write
{
    char *p = s;
    while (n--)
        *p++ = c;
    return s;
}
Referenced by add_new_file(), fdt_add_subnode_namelen(), fdt_create_with_flags(), kfs_absolute_pathname(), kfs_print_files(), mess(), and split().
snprintf()
int snprintf (char * buffer, unsigned size, char * fmt, ...)
write a formated string to the str buffer this a simplified version which handles only: c, s, $d, x and p
Parameters
buffer buffer of chars where string is formed
size size of buffer
fmt formated string
... variadic arguments, i.e. variable number of arguments
Returns
number of printed char
{
    va_list ap;
    va_start (ap, fmt);
    int res = vsnprintf(str, size, fmt, ap);
    va_end(ap);
    return res;
}
References vsnprintf().
strchr()
char * strchr (const char * s, int c)
returns a pointer to the first occurrence of a character in a null-terminated string
Parameters
s string to search
c searched character
Returns
pointer to the character in s if found, NULL else
{
    do {
        if (*s == c) {
            return (char*)s;
        }
    } while (*s++);
    return (0);
}
Referenced by overlay_symbol_update().
strcmp()
int strcmp (const char * s1, const char * s2)
compare two null-terminated strings
Parameters
s1 first string
s2 second string
Returns
return less than, equal to or greater than 0 if s1 is less than, equal to or greater than s2
{
    unsigned char c1, c2;
    do {
        c1 = (unsigned char) *s1++;
        c2 = (unsigned char) *s2++;
        if (c1 == 0)
            return c1 - c2;
    } while (c1 == c2);
    return c1 - c2;
}
Referenced by getoption().
strlen()
int strlen (const char * buf)
calculates the length of the string s, excluding the terminating null byte
Parameters
buf input string
Returns
the number of characters
{
    int n = 0;
    if (buf) while (*buf++) n++;
    return n;
}
Referenced by build(), fdt_add_string_(), fdt_add_subnode(), fdt_begin_node(), fdt_del_last_string_(), fdt_find_add_string_(), fdt_find_string_(), fdt_get_alias(), fdt_get_name(), fdt_get_property(), fdt_get_string(), fdt_get_symbol(), fdt_getprop(), fdt_path_offset(), fdt_set_name(), fdt_setprop_inplace(), fdt_stringlist_contains(), fdt_stringlist_search(), fdt_subnode_offset(), kfs_absolute_pathname(), kfs_print_dentry(), main(), overlay_symbol_update(), overlay_update_local_node_references(), and split().
strncpy()
void * strncpy (char * dest, char * src, unsigned n)
copies the string src, included the ending byte '\0', to the buffer dest
Parameters
dest buffer where the source string must be copied
src the source string
n size of the dest buffer
Returns
the dest buffer address
{
    unsigned i;
    for (i = 0; i < n && src[i] != '\0'; i++)
        dest[i] = src[i];
    for (; i < n; i++)
        dest[i] = '\0';
    return dest;
}
Referenced by kfs_absolute_pathname(), and split().
strnlen()
size_t strnlen (const char * s, size_t n)
calculates the length of the string s, excluding the terminating null byte, up to the value n
Parameters
s string
n maximum number of characters
Returns
the number of characters if it is less than n, n else
{
    size_t i;
    for (i = 0; i < n; ++i)
        if (s[i] == '\0')
            break;
    return i;
}
Referenced by fdt_stringlist_count(), fdt_stringlist_get(), and fdt_stringlist_search().
strrchr()
char * strrchr (const char * s, int c)
returns a pointer to the last occurrence of a character in a null-terminated string
Parameters
s string to search
c searched character
Returns
pointer to the character in s if found, NULL else
{
    char *rtnval = 0;
    do {
        if (*s == c)
            rtnval = (char*) s;
    } while (*s++);
    return (rtnval);
}
Referenced by fdt_get_name().
strtoul()
unsigned long int strtoul (char * s, char ** endptr, int base)
convert a string into an unsigned 32bit number
Parameters
s buffer containing the number representation
endptr pointer to the last char read by the function, can be NULL
base base of the number contained in the string, if 0 the baase will be guessed from the number representation format
Returns
the number extracted from the string
{
    while (*s == ' '
        || *s == '\t'
        || *s == '\n'
        || *s == '\v'
        || *s == '\f'
        || *s == '\r')                              // Skip the whitespaces
        s++;
    if (*s == '+')
        s++;
    if (!base) {                                    // If base is zero,
                                                    // try to guess the base from the format
        if (*s == '0') {
            s++;
            if (*s == 'x' || *s == 'X') {           // 0x, 0X prefix means hexadecimal
                s++;
                base = 16;
            } else if ('0' <= *s && *s <= '9') {    // 0d with d a digit means octal
                base = 8;
            }
        } else if ('0' <= *s && *s <= '9') {        // We found a digit, let's guess decimal
            base = 10;
        }
    }
    if (!base) {                                    // If after the guessing block we still
                                                    // don't know what the base is, abort
        if (endptr) *endptr = s;
        return 0;
    }
    unsigned long n = 0;
    char overflow = 0;
    char c;
    while (*s) {
        c = *s;
        if ('0' <= c && c <= '9') {                 // Convert a char digit to its value
            c -= '0';
        } else if ('a' <= c && c <= 'z') {          // Convert a char to its value
                                                    // (A = a = 10, Z = z = 36)
            c -= 'a';
            c += 10;
        } else if ('A' <= c && c <= 'Z') {
            c -= 'A';
            c += 10;
        } else {
            break;
        }
        if (c >= base)                              // If the digit is outside the range of
                                                    // the base (ex: g is outside hexadecimal
                                                    // range) the number is not decodable
            break;
        if (n < ULONG_MAX / base &&                 // Check that we can multiply with base
            n * base < ULONG_MAX - c) {             // and add char without overflow
            n *= base;
            n += c;
        } else {
            overflow = 1;
            break;
        }
        s++;
    }
    if (endptr) *endptr = s;
    if (overflow)
        return 0;
    return n;
}
References ULONG_MAX.
Referenced by overlay_fixup_phandle().
vsnprintf()
int vsnprintf (char * buffer, unsigned size, char * fmt, va_list ap)
write a formated string to the str buffer this a simplified version which handles only: c, s, $d, x and p
Parameters
buffer buffer of chars where string is formed
size size of buffer
fmt formated string
ap variadic arguments, i.e. variable number of arguments
Returns
number of printed char
{
    char arg[16];                               // buffer used to build the argument
    char *tmp;                                  // temporary pointer used to build arguments
    char *buf = buffer;                         // pointer to the current filling position in buffer
    int res;                                    // function result (number of printed char)
    int val;                                    // argument value
    /*long val64_lsb;
    lo ng val64_msb;
    long long val64;
    */
    int i;                                      // temporary variable
    int count = size - 1;                       // max nb of char in buffer (-1 because of last 0)
    while (*fmt) {                              // for all char in fmt
        while ((*fmt) && (*fmt != '%')) {       // while char exists and it is not a %
            *buf++ = *fmt++;                    // copy it in output buffer
            if (--count == 0)                   // decrement count
                goto abort;                     // and abort if there is no space anymore
        }
        if (*fmt == '%') {                      // if char is a %
            fmt++;                              // go to the next char
            switch (*fmt) {                     // study the different cases
            case '%':                           // case %%
                *buf++ = '%';                   // then it is just %
                if (--count == 0)               // go to the next char if there is space yet
                    goto abort;
                goto next;
            /* case 'l':                           // TODO: handle u,d formats
                fmt++;
                switch (*fmt) {
                case 'x':
                    //val64 = va_arg (ap, long long);     // val <- value to convert in ascii
                    val64_lsb = va_arg (ap, long);
                    val64_msb = va_arg (ap, long);
                    val64 = ((long long) val64_msb << 32LL) | val64_lsb;
                    tmp = arg + sizeof (arg);           // goto at the end of tmp buffer
                    *--tmp = '\0';                      // put the ending char 0
                    i = 0;                              // i is used to count the digits
                    do {
                        *--tmp = xdigit[val64 & 0xF];   // compute the unit digit
                        val64 = (unsigned long long) val64 >> 4;  // go to the next digit
                        i++;                            // digits counter
                    } while (val64);                    // until val becomes 0
                    goto copy_tmp;                      // go to copy tmp in buffer
                default:
                    *buf++ = '%';                       // invalid format
                    if (--count == 0)
                        goto abort;
                    goto next;
                }
                goto next;*/
            case 'c':                           // case %c (char)
                *buf++ = (char)va_arg (ap, int);// get the argument and copy it in output buffer
                if (--count == 0)               // go to the next char if there is space yet
                    goto abort;
                goto next;
            case 's':                           // case %s (string)
                tmp = va_arg (ap, char *);      // tmp points to this string argumment
                tmp = (tmp) ? tmp : "(null)";   // replace "" by "(null)"
                goto copy_tmp;                  // go to copy tmp in buffer
            case 'd':                           // case %d (decimal int)
                val = va_arg (ap, int);         // val <- value to convert in ascii
                i = (val == 0x80000000);        // i <- 1 if val==-(MAXINT+1) MAXINT==0x7FFFFFFF
                if (val < 0) {                  // if val is negative
                    val = -val;                 // val <- abs(val)
                    val = val - i;              // but if val==-(MAXINT+1) then val <- MAXINT
                    *buf++ = '-';               // put '-' to the output buffer
                    if (--count == 0)           // check if there is space yet
                        goto abort;
                }
                tmp = arg + sizeof (arg);       // goto at the end of tmp buffer
                *--tmp = '\0';                  // put the ending char 0
                do {
                    *--tmp = (val % 10) + '0';  // compute the unit digit
                    *tmp = *tmp + i;            // but add 1 if we had decremented val just before
                    i = 0;                      // must be done only once
                    val = val / 10;             // go to the next digit
                }
                while (val);                    // until val becomes 0
                goto copy_tmp;                  // go to copy tmp in buffer
            case 'p':                           // case %p (pointer)
            case 'x':                           // case %x (simple hexadecimal)
                val = va_arg (ap, int);         // val <- value to convert in ascii
                tmp = arg + sizeof (arg);       // goto at the end of tmp buffer
                *--tmp = '\0';                  // put the ending char 0
                i = 0;                          // i is used to count the digits
                do {
                    *--tmp = xdigit[val & 0xF]; // compute the unit digit
                    val = (unsigned) val >> 4;  // go to the next digit
                    i++;                        // digits counter
                } while (val);                  // until val becomes 0
                if (*fmt == 'p') {              // if it is a pointer
                    while (i < 8) {             // then complete with '0'
                        *--tmp = '0';
                        i++;
                    }
                }
                goto copy_tmp;                  // go to copy tmp in buffer
            default:                            // if format not recognized
                *buf++ = *fmt;                  // then just copy it in output buffer
                if (--count == 0)               // go to the next char if there is space yet
                    goto abort;
                goto next;
            }
          copy_tmp:
            while (*tmp) {                      // copy tmp in output buffer
                *buf++ = *tmp++;
                if (--count == 0)               // check if there is space yet
                    goto abort;
            }
          next:
            fmt++;                              // go to the next char
        }
    }
  abort:
    *buf = '\0';                                // put the ending char 0
    res = (int)((unsigned)buf-(unsigned)buffer);// compute the number of char to write
    return res;                                 // and return it
}
References buffer, and xdigit.
Referenced by fprintf(), kprintf(), and snprintf().
wzero()
void wzero (void * addr, size_t n)
write 0 in a buffer
Parameters
addr address word aligned
n number of bytes to erase must be a multiple of sizeof word
{
    unsigned *a = addr;
    if (a)
    do { *a++ = 0; } while (n -= sizeof(unsigned));
}
Referenced by kmalloc().
Variable Documentation
xdigit
char xdigit[] = "0123456789abcdef" static
Referenced by vsnprintf().