ko6: src/soft/external/libfdt/fdt_sw.c File Reference
fdt_sw.c File Reference
#include "libfdt_env.h"
#include <external/libfdt/fdt.h>
#include <external/libfdt/libfdt.h>
#include "libfdt_internal.h"
Macros
#define FDT_SW_PROBE(fdt)
#define FDT_SW_PROBE_MEMRSV(fdt)
#define FDT_SW_PROBE_STRUCT(fdt)
Functions
static int fdt_sw_probe_ (void *fdt)
static int fdt_sw_probe_memrsv_ (void *fdt)
static int fdt_sw_probe_struct_ (void *fdt)
static uint32_t sw_flags (void *fdt)
static void * fdt_grab_space_ (void *fdt, size_t len)
int fdt_create_with_flags (void *buf, int bufsize, uint32_t flags)
int fdt_create (void *buf, int bufsize)
int fdt_resize (void *fdt, void *buf, int bufsize)
int fdt_add_reservemap_entry (void *fdt, uint64_t addr, uint64_t size)
int fdt_finish_reservemap (void *fdt)
int fdt_begin_node (void *fdt, const char *name)
int fdt_end_node (void *fdt)
static int fdt_add_string_ (void *fdt, const char *s)
static void fdt_del_last_string_ (void *fdt, const char *s)
static int fdt_find_add_string_ (void *fdt, const char *s, int *allocated)
int fdt_property_placeholder (void *fdt, const char *name, int len, void **valp)
int fdt_property (void *fdt, const char *name, const void *val, int len)
int fdt_finish (void *fdt)
Macro Definition Documentation
FDT_SW_PROBE
#define FDT_SW_PROBE (fdt)
Value:
    { \
        int err; \
        if ((err = fdt_sw_probe_(fdt)) != 0) \
            return err; \
    }
FDT_SW_PROBE_MEMRSV
#define FDT_SW_PROBE_MEMRSV (fdt)
Value:
    { \
        int err; \
        if ((err = fdt_sw_probe_memrsv_(fdt)) != 0) \
            return err; \
    }
FDT_SW_PROBE_STRUCT
#define FDT_SW_PROBE_STRUCT (fdt)
Value:
    { \
        int err; \
        if ((err = fdt_sw_probe_struct_(fdt)) != 0) \
            return err; \
    }
Function Documentation
fdt_add_reservemap_entry()
int fdt_add_reservemap_entry (void * fdt, uint64_t addr, uint64_t size)
{
    struct fdt_reserve_entry *re;
    int offset;
    FDT_SW_PROBE_MEMRSV(fdt);
    offset = fdt_off_dt_struct(fdt);
    if ((offset + sizeof(*re)) > fdt_totalsize(fdt))
        return -FDT_ERR_NOSPACE;
    re = (struct fdt_reserve_entry *)((char *)fdt + offset);
    re->address = cpu_to_fdt64(addr);
    re->size = cpu_to_fdt64(size);
    fdt_set_off_dt_struct(fdt, offset + sizeof(*re));
    return 0;
}
References fdt_reserve_entry::address, cpu_to_fdt64(), FDT_ERR_NOSPACE, fdt_off_dt_struct, FDT_SW_PROBE_MEMRSV, fdt_totalsize, and fdt_reserve_entry::size.
Referenced by fdt_finish_reservemap().
fdt_add_string_()
static int fdt_add_string_ (void * fdt, const char * s) static
{
    char *strtab = (char *)fdt + fdt_totalsize(fdt);
    unsigned int strtabsize = fdt_size_dt_strings(fdt);
    unsigned int len = strlen(s) + 1;
    unsigned int struct_top, offset;
    offset = strtabsize + len;
    struct_top = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
    if (fdt_totalsize(fdt) - offset < struct_top)
        return 0; /* no more room :( */
    memcpy(strtab - offset, s, len);
    fdt_set_size_dt_strings(fdt, strtabsize + len);
    return -offset;
}
References fdt_off_dt_struct, fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, memcpy(), and strlen().
Referenced by fdt_find_add_string_(), and fdt_property_placeholder().
fdt_begin_node()
int fdt_begin_node (void * fdt, const char * name)
{
    struct fdt_node_header *nh;
    int namelen;
    FDT_SW_PROBE_STRUCT(fdt);
    namelen = strlen(name) + 1;
    nh = fdt_grab_space_(fdt, sizeof(*nh) + FDT_TAGALIGN(namelen));
    if (! nh)
        return -FDT_ERR_NOSPACE;
    nh->tag = cpu_to_fdt32(FDT_BEGIN_NODE);
    memcpy(nh->name, name, namelen);
    return 0;
}
References cpu_to_fdt32(), FDT_BEGIN_NODE, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_SW_PROBE_STRUCT, FDT_TAGALIGN, memcpy(), fdt_node_header::name, strlen(), and fdt_node_header::tag.
Referenced by fdt_create_empty_tree().
fdt_create()
int fdt_create (void * buf, int bufsize)
fdt_create - begin creation of a new fdt @buf: pointer to memory allocated where fdt will be created @bufsize: size of the memory space at fdt
fdt_create() is equivalent to fdt_create_with_flags() with flags=0.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt
{
    return fdt_create_with_flags(buf, bufsize, 0);
}
References fdt_create_with_flags().
Referenced by fdt_create_empty_tree().
fdt_create_with_flags()
int fdt_create_with_flags (void * buf, int bufsize, uint32_t flags)
fdt_create_with_flags - begin creation of a new fdt @buf: pointer to memory allocated where fdt will be created @bufsize: size of the memory space at fdt @flags: a valid combination of FDT_CREATE_FLAG_ flags, or 0.
fdt_create_with_flags() begins the process of creating a new fdt with the sequential write interface.
fdt creation process must end with fdt_finish() to produce a valid fdt.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient for a minimal fdt -FDT_ERR_BADFLAGS, flags is not valid
{
    const int hdrsize = FDT_ALIGN(sizeof(struct fdt_header),
                      sizeof(struct fdt_reserve_entry));
    void *fdt = buf;
    if (bufsize < hdrsize)
        return -FDT_ERR_NOSPACE;
    if (flags & ~FDT_CREATE_FLAGS_ALL)
        return -FDT_ERR_BADFLAGS;
    memset(buf, 0, bufsize);
    /*
     * magic and last_comp_version keep intermediate state during the fdt
     * creation process, which is replaced with the proper FDT format by
     * fdt_finish().
     *
     * flags should be accessed with sw_flags().
     */
    fdt_set_magic(fdt, FDT_SW_MAGIC);
    fdt_set_version(fdt, FDT_LAST_SUPPORTED_VERSION);
    fdt_set_last_comp_version(fdt, flags);
    fdt_set_totalsize(fdt,  bufsize);
    fdt_set_off_mem_rsvmap(fdt, hdrsize);
    fdt_set_off_dt_struct(fdt, fdt_off_mem_rsvmap(fdt));
    fdt_set_off_dt_strings(fdt, 0);
    return 0;
}
References FDT_ALIGN, FDT_CREATE_FLAGS_ALL, FDT_ERR_BADFLAGS, FDT_ERR_NOSPACE, FDT_LAST_SUPPORTED_VERSION, fdt_off_mem_rsvmap, FDT_SW_MAGIC, and memset().
Referenced by fdt_create().
fdt_del_last_string_()
static void fdt_del_last_string_ (void * fdt, const char * s) static
{
    int strtabsize = fdt_size_dt_strings(fdt);
    int len = strlen(s) + 1;
    fdt_set_size_dt_strings(fdt, strtabsize - len);
}
References fdt_size_dt_strings, and strlen().
Referenced by fdt_property_placeholder().
fdt_end_node()
int fdt_end_node (void * fdt)
{
    fdt32_t *en;
    FDT_SW_PROBE_STRUCT(fdt);
    en = fdt_grab_space_(fdt, FDT_TAGSIZE);
    if (! en)
        return -FDT_ERR_NOSPACE;
    *en = cpu_to_fdt32(FDT_END_NODE);
    return 0;
}
References cpu_to_fdt32(), FDT_END_NODE, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_SW_PROBE_STRUCT, and FDT_TAGSIZE.
Referenced by fdt_create_empty_tree().
fdt_find_add_string_()
static int fdt_find_add_string_ (void * fdt, const char * s, int * allocated) static
{
    char *strtab = (char *)fdt + fdt_totalsize(fdt);
    int strtabsize = fdt_size_dt_strings(fdt);
    const char *p;
    *allocated = 0;
    p = fdt_find_string_(strtab - strtabsize, strtabsize, s);
    if (p)
        return p - strtab;
    *allocated = 1;
    return fdt_add_string_(fdt, s);
}
References fdt_add_string_(), fdt_find_string_(), fdt_size_dt_strings, and fdt_totalsize.
Referenced by fdt_property_placeholder().
fdt_finish()
int fdt_finish (void * fdt)
{
    char *p = (char *)fdt;
    fdt32_t *end;
    int oldstroffset, newstroffset;
    uint32_t tag;
    int offset, nextoffset;
    FDT_SW_PROBE_STRUCT(fdt);
    /* Add terminator */
    end = fdt_grab_space_(fdt, sizeof(*end));
    if (! end)
        return -FDT_ERR_NOSPACE;
    *end = cpu_to_fdt32(FDT_END);
    /* Relocate the string table */
    oldstroffset = fdt_totalsize(fdt) - fdt_size_dt_strings(fdt);
    newstroffset = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
    memmove(p + newstroffset, p + oldstroffset, fdt_size_dt_strings(fdt));
    fdt_set_off_dt_strings(fdt, newstroffset);
    /* Walk the structure, correcting string offsets */
    offset = 0;
    while ((tag = fdt_next_tag(fdt, offset, &nextoffset)) != FDT_END) {
        if (tag == FDT_PROP) {
            struct fdt_property *prop =
                fdt_offset_ptr_w_(fdt, offset);
            int nameoff;
            nameoff = fdt32_to_cpu(prop->nameoff);
            nameoff += fdt_size_dt_strings(fdt);
            prop->nameoff = cpu_to_fdt32(nameoff);
        }
        offset = nextoffset;
    }
    if (nextoffset < 0)
        return nextoffset;
    /* Finally, adjust the header */
    fdt_set_totalsize(fdt, newstroffset + fdt_size_dt_strings(fdt));
    /* And fix up fields that were keeping intermediate state. */
    fdt_set_last_comp_version(fdt, FDT_LAST_COMPATIBLE_VERSION);
    fdt_set_magic(fdt, FDT_MAGIC);
    return 0;
}
References cpu_to_fdt32(), fdt32_to_cpu(), FDT_END, FDT_ERR_NOSPACE, fdt_grab_space_(), FDT_LAST_COMPATIBLE_VERSION, FDT_MAGIC, fdt_next_tag(), fdt_off_dt_struct, fdt_offset_ptr_w_(), FDT_PROP, fdt_size_dt_strings, fdt_size_dt_struct, FDT_SW_PROBE_STRUCT, fdt_totalsize, memmove(), fdt_property::nameoff, and fdt_property::tag.
Referenced by fdt_create_empty_tree().
fdt_finish_reservemap()
int fdt_finish_reservemap (void * fdt)
{
    int err = fdt_add_reservemap_entry(fdt, 0, 0);
    if (err)
        return err;
    fdt_set_off_dt_strings(fdt, fdt_totalsize(fdt));
    return 0;
}
References fdt_add_reservemap_entry(), and fdt_totalsize.
Referenced by fdt_create_empty_tree().
fdt_grab_space_()
static void * fdt_grab_space_ (void * fdt, size_t len) static
{
    unsigned int offset = fdt_size_dt_struct(fdt);
    unsigned int spaceleft;
    spaceleft = fdt_totalsize(fdt) - fdt_off_dt_struct(fdt)
        - fdt_size_dt_strings(fdt);
    if ((offset + len < offset) || (offset + len > spaceleft))
        return NULL;
    fdt_set_size_dt_struct(fdt, offset + len);
    return fdt_offset_ptr_w_(fdt, offset);
}
References fdt_off_dt_struct, fdt_offset_ptr_w_(), fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, and NULL.
Referenced by fdt_begin_node(), fdt_end_node(), fdt_finish(), and fdt_property_placeholder().
fdt_property()
int fdt_property (void * fdt, const char * name, const void * val, int len)
{
    void *ptr;
    int ret;
    ret = fdt_property_placeholder(fdt, name, len, &ptr);
    if (ret)
        return ret;
    memcpy(ptr, val, len);
    return 0;
}
References fdt_property_placeholder(), fdt_property::len, and memcpy().
fdt_property_placeholder()
int fdt_property_placeholder (void * fdt, const char * name, int len, void ** valp)
{
    struct fdt_property *prop;
    int nameoff;
    int allocated;
    FDT_SW_PROBE_STRUCT(fdt);
    /* String de-duplication can be slow, _NO_NAME_DEDUP skips it */
    if (sw_flags(fdt) & FDT_CREATE_FLAG_NO_NAME_DEDUP) {
        allocated = 1;
        nameoff = fdt_add_string_(fdt, name);
    } else {
        nameoff = fdt_find_add_string_(fdt, name, &allocated);
    }
    if (nameoff == 0)
        return -FDT_ERR_NOSPACE;
    prop = fdt_grab_space_(fdt, sizeof(*prop) + FDT_TAGALIGN(len));
    if (! prop) {
        if (allocated)
            fdt_del_last_string_(fdt, name);
        return -FDT_ERR_NOSPACE;
    }
    prop->tag = cpu_to_fdt32(FDT_PROP);
    prop->nameoff = cpu_to_fdt32(nameoff);
    prop->len = cpu_to_fdt32(len);
    *valp = prop->data;
    return 0;
}
References cpu_to_fdt32(), fdt_property::data, fdt_add_string_(), FDT_CREATE_FLAG_NO_NAME_DEDUP, fdt_del_last_string_(), FDT_ERR_NOSPACE, fdt_find_add_string_(), fdt_grab_space_(), FDT_PROP, FDT_SW_PROBE_STRUCT, FDT_TAGALIGN, fdt_property::len, fdt_property::nameoff, sw_flags(), and fdt_property::tag.
Referenced by fdt_property().
fdt_resize()
int fdt_resize (void * fdt, void * buf, int bufsize)
{
    size_t headsize, tailsize;
    char *oldtail, *newtail;
    FDT_SW_PROBE(fdt);
    if (bufsize < 0)
        return -FDT_ERR_NOSPACE;
    headsize = fdt_off_dt_struct(fdt) + fdt_size_dt_struct(fdt);
    tailsize = fdt_size_dt_strings(fdt);
    if (!can_assume(VALID_DTB) &&
        headsize + tailsize > fdt_totalsize(fdt))
        return -FDT_ERR_INTERNAL;
    if ((headsize + tailsize) > (unsigned)bufsize)
        return -FDT_ERR_NOSPACE;
    oldtail = (char *)fdt + fdt_totalsize(fdt) - tailsize;
    newtail = (char *)buf + bufsize - tailsize;
    /* Two cases to avoid clobbering data if the old and new
     * buffers partially overlap */
    if (buf <= fdt) {
        memmove(buf, fdt, headsize);
        memmove(newtail, oldtail, tailsize);
    } else {
        memmove(newtail, oldtail, tailsize);
        memmove(buf, fdt, headsize);
    }
    fdt_set_totalsize(buf, bufsize);
    if (fdt_off_dt_strings(buf))
        fdt_set_off_dt_strings(buf, bufsize);
    return 0;
}
References can_assume, FDT_ERR_INTERNAL, FDT_ERR_NOSPACE, fdt_off_dt_strings, fdt_off_dt_struct, fdt_size_dt_strings, fdt_size_dt_struct, FDT_SW_PROBE, fdt_totalsize, and memmove().
fdt_sw_probe_()
static int fdt_sw_probe_ (void * fdt) static
{
    if (!can_assume(VALID_INPUT)) {
        if (fdt_magic(fdt) == FDT_MAGIC)
            return -FDT_ERR_BADSTATE;
        else if (fdt_magic(fdt) != FDT_SW_MAGIC)
            return -FDT_ERR_BADMAGIC;
    }
    return 0;
}
References can_assume, FDT_ERR_BADMAGIC, FDT_ERR_BADSTATE, FDT_MAGIC, fdt_magic, and FDT_SW_MAGIC.
Referenced by fdt_sw_probe_memrsv_(), and fdt_sw_probe_struct_().
fdt_sw_probe_memrsv_()
static int fdt_sw_probe_memrsv_ (void * fdt) static
{
    int err = fdt_sw_probe_(fdt);
    if (err)
        return err;
    if (!can_assume(VALID_INPUT) && fdt_off_dt_strings(fdt) != 0)
        return -FDT_ERR_BADSTATE;
    return 0;
}
References can_assume, FDT_ERR_BADSTATE, fdt_off_dt_strings, and fdt_sw_probe_().
fdt_sw_probe_struct_()
static int fdt_sw_probe_struct_ (void * fdt) static
{
    int err = fdt_sw_probe_(fdt);
    if (err)
        return err;
    if (!can_assume(VALID_INPUT) &&
        fdt_off_dt_strings(fdt) != fdt_totalsize(fdt))
        return -FDT_ERR_BADSTATE;
    return 0;
}
References can_assume, FDT_ERR_BADSTATE, fdt_off_dt_strings, fdt_sw_probe_(), and fdt_totalsize.
sw_flags()
static uint32_t sw_flags (void * fdt) inline static
{
    /* assert: (fdt_magic(fdt) == FDT_SW_MAGIC) */
    return fdt_last_comp_version(fdt);
}
References fdt_last_comp_version.
Referenced by fdt_property_placeholder().