ko6: src/soft/external/libfdt/fdt_rw.c File Reference
fdt_rw.c File Reference
#include "libfdt_env.h"
#include <external/libfdt/fdt.h>
#include <external/libfdt/libfdt.h>
#include "libfdt_internal.h"
Macros
#define FDT_RW_PROBE(fdt)
Functions
static int fdt_blocks_misordered_ (const void *fdt, int mem_rsv_size, int struct_size)
static int fdt_rw_probe_ (void *fdt)
static unsigned int fdt_data_size_ (void *fdt)
static int fdt_splice_ (void *fdt, void *splicepoint, int oldlen, int newlen)
static int fdt_splice_mem_rsv_ (void *fdt, struct fdt_reserve_entry *p, int oldn, int newn)
static int fdt_splice_struct_ (void *fdt, void *p, int oldlen, int newlen)
static void fdt_del_last_string_ (void *fdt, const char *s)
static int fdt_splice_string_ (void *fdt, int newlen)
static int fdt_find_add_string_ (void *fdt, const char *s, int *allocated)
int fdt_add_mem_rsv (void *fdt, uint64_t address, uint64_t size)
int fdt_del_mem_rsv (void *fdt, int n)
static int fdt_resize_property_ (void *fdt, int nodeoffset, const char *name, int len, struct fdt_property **prop)
static int fdt_add_property_ (void *fdt, int nodeoffset, const char *name, int len, struct fdt_property **prop)
int fdt_set_name (void *fdt, int nodeoffset, const char *name)
int fdt_setprop_placeholder (void *fdt, int nodeoffset, const char *name, int len, void **prop_data)
int fdt_setprop (void *fdt, int nodeoffset, const char *name, const void *val, int len)
int fdt_appendprop (void *fdt, int nodeoffset, const char *name, const void *val, int len)
int fdt_delprop (void *fdt, int nodeoffset, const char *name)
int fdt_add_subnode_namelen (void *fdt, int parentoffset, const char *name, int namelen)
int fdt_add_subnode (void *fdt, int parentoffset, const char *name)
int fdt_del_node (void *fdt, int nodeoffset)
static void fdt_packblocks_ (const char *old, char *new, int mem_rsv_size, int struct_size, int strings_size)
int fdt_open_into (const void *fdt, void *buf, int bufsize)
int fdt_pack (void *fdt)
Macro Definition Documentation
FDT_RW_PROBE
#define FDT_RW_PROBE (fdt)
Value:
    { \
        int err_; \
        if ((err_ = fdt_rw_probe_(fdt)) != 0) \
            return err_; \
    }
Function Documentation
fdt_add_mem_rsv()
int fdt_add_mem_rsv (void * fdt, uint64_t address, uint64_t size)
fdt_add_mem_rsv - add one memory reserve map entry @fdt: pointer to the device tree blob @address: 64-bit start address of the reserve map entry @size: 64-bit size of the reserved region
Adds a reserve map entry to the given blob reserving a region at address address of length size.
This function will insert data into the reserve map and will therefore change the indexes of some entries in the table.
returns: 0, on success -FDT_ERR_NOSPACE, there is insufficient free space in the blob to contain the new reservation entry -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
{
    struct fdt_reserve_entry *re;
    int err;
    FDT_RW_PROBE(fdt);
    re = fdt_mem_rsv_w_(fdt, fdt_num_mem_rsv(fdt));
    err = fdt_splice_mem_rsv_(fdt, re, 0, 1);
    if (err)
        return err;
    re->address = cpu_to_fdt64(address);
    re->size = cpu_to_fdt64(size);
    return 0;
}
References fdt_reserve_entry::address, cpu_to_fdt64(), fdt_mem_rsv_w_(), fdt_num_mem_rsv(), FDT_RW_PROBE, fdt_splice_mem_rsv_(), and fdt_reserve_entry::size.
fdt_add_property_()
static int fdt_add_property_ (void * fdt, int nodeoffset, const char * name, int len, struct fdt_property ** prop) static
{
    int proplen;
    int nextoffset;
    int namestroff;
    int err;
    int allocated;
    if ((nextoffset = fdt_check_node_offset_(fdt, nodeoffset)) < 0)
        return nextoffset;
    namestroff = fdt_find_add_string_(fdt, name, &allocated);
    if (namestroff < 0)
        return namestroff;
    *prop = fdt_offset_ptr_w_(fdt, nextoffset);
    proplen = sizeof(**prop) + FDT_TAGALIGN(len);
    err = fdt_splice_struct_(fdt, *prop, 0, proplen);
    if (err) {
        /* Delete the string if we failed to add it */
        if (!can_assume(NO_ROLLBACK) && allocated)
            fdt_del_last_string_(fdt, name);
        return err;
    }
    (*prop)->tag = cpu_to_fdt32(FDT_PROP);
    (*prop)->nameoff = cpu_to_fdt32(namestroff);
    (*prop)->len = cpu_to_fdt32(len);
    return 0;
}
References can_assume, cpu_to_fdt32(), fdt_check_node_offset_(), fdt_del_last_string_(), fdt_find_add_string_(), fdt_offset_ptr_w_(), FDT_PROP, fdt_splice_struct_(), and FDT_TAGALIGN.
Referenced by fdt_appendprop(), and fdt_setprop_placeholder().
fdt_add_subnode()
int fdt_add_subnode (void * fdt, int parentoffset, const char * name)
{
    return fdt_add_subnode_namelen(fdt, parentoffset, name, strlen(name));
}
References fdt_add_subnode_namelen(), fdt_node_header::name, and strlen().
Referenced by overlay_apply_node(), and overlay_symbol_update().
fdt_add_subnode_namelen()
int fdt_add_subnode_namelen (void * fdt, int parentoffset, const char * name, int namelen)
{
    struct fdt_node_header *nh;
    int offset, nextoffset;
    int nodelen;
    int err;
    uint32_t tag;
    fdt32_t *endtag;
    FDT_RW_PROBE(fdt);
    offset = fdt_subnode_offset_namelen(fdt, parentoffset, name, namelen);
    if (offset >= 0)
        return -FDT_ERR_EXISTS;
    else if (offset != -FDT_ERR_NOTFOUND)
        return offset;
    /* Try to place the new node after the parent's properties */
    tag = fdt_next_tag(fdt, parentoffset, &nextoffset);
    /* the fdt_subnode_offset_namelen() should ensure this never hits */
    if (!can_assume(LIBFDT_FLAWLESS) && (tag != FDT_BEGIN_NODE))
        return -FDT_ERR_INTERNAL;
    do {
        offset = nextoffset;
        tag = fdt_next_tag(fdt, offset, &nextoffset);
    } while ((tag == FDT_PROP) || (tag == FDT_NOP));
    nh = fdt_offset_ptr_w_(fdt, offset);
    nodelen = sizeof(*nh) + FDT_TAGALIGN(namelen+1) + FDT_TAGSIZE;
    err = fdt_splice_struct_(fdt, nh, 0, nodelen);
    if (err)
        return err;
    nh->tag = cpu_to_fdt32(FDT_BEGIN_NODE);
    memset(nh->name, 0, FDT_TAGALIGN(namelen+1));
    memcpy(nh->name, name, namelen);
    endtag = (fdt32_t *)((char *)nh + nodelen - FDT_TAGSIZE);
    *endtag = cpu_to_fdt32(FDT_END_NODE);
    return offset;
}
References can_assume, cpu_to_fdt32(), FDT_BEGIN_NODE, FDT_END_NODE, FDT_ERR_EXISTS, FDT_ERR_INTERNAL, FDT_ERR_NOTFOUND, fdt_next_tag(), FDT_NOP, fdt_offset_ptr_w_(), FDT_PROP, FDT_RW_PROBE, fdt_splice_struct_(), fdt_subnode_offset_namelen(), FDT_TAGALIGN, FDT_TAGSIZE, memcpy(), memset(), fdt_node_header::name, and fdt_node_header::tag.
Referenced by fdt_add_subnode().
fdt_appendprop()
int fdt_appendprop (void * fdt, int nodeoffset, const char * name, const void * val, int len)
{
    struct fdt_property *prop;
    int err, oldlen, newlen;
    FDT_RW_PROBE(fdt);
    prop = fdt_get_property_w(fdt, nodeoffset, name, &oldlen);
    if (prop) {
        newlen = len + oldlen;
        err = fdt_splice_struct_(fdt, prop->data,
                     FDT_TAGALIGN(oldlen),
                     FDT_TAGALIGN(newlen));
        if (err)
            return err;
        prop->len = cpu_to_fdt32(newlen);
        memcpy(prop->data + oldlen, val, len);
    } else {
        err = fdt_add_property_(fdt, nodeoffset, name, len, &prop);
        if (err)
            return err;
        memcpy(prop->data, val, len);
    }
    return 0;
}
References cpu_to_fdt32(), fdt_property::data, fdt_add_property_(), fdt_get_property_w(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, fdt_property::len, and memcpy().
Referenced by fdt_appendprop_addrrange(), fdt_appendprop_u32(), and fdt_appendprop_u64().
fdt_blocks_misordered_()
static int fdt_blocks_misordered_ (const void * fdt, int mem_rsv_size, int struct_size) static
{
    return (fdt_off_mem_rsvmap(fdt) < FDT_ALIGN(sizeof(struct fdt_header), 8))
        || (fdt_off_dt_struct(fdt) <
            (fdt_off_mem_rsvmap(fdt) + mem_rsv_size))
        || (fdt_off_dt_strings(fdt) <
            (fdt_off_dt_struct(fdt) + struct_size))
        || (fdt_totalsize(fdt) <
            (fdt_off_dt_strings(fdt) + fdt_size_dt_strings(fdt)));
}
References FDT_ALIGN, fdt_off_dt_strings, fdt_off_dt_struct, fdt_off_mem_rsvmap, fdt_size_dt_strings, and fdt_totalsize.
Referenced by fdt_open_into(), and fdt_rw_probe_().
fdt_data_size_()
static unsigned int fdt_data_size_ (void * fdt) inline static
{
    return fdt_off_dt_strings(fdt) + fdt_size_dt_strings(fdt);
}
References fdt_off_dt_strings, and fdt_size_dt_strings.
Referenced by fdt_pack(), and fdt_splice_().
fdt_del_last_string_()
static void fdt_del_last_string_ (void * fdt, const char * s) static
{
    int newlen = strlen(s) + 1;
    fdt_set_size_dt_strings(fdt, fdt_size_dt_strings(fdt) - newlen);
}
References fdt_size_dt_strings, and strlen().
Referenced by fdt_add_property_().
fdt_del_mem_rsv()
int fdt_del_mem_rsv (void * fdt, int n)
fdt_del_mem_rsv - remove a memory reserve map entry @fdt: pointer to the device tree blob
: entry to remove
fdt_del_mem_rsv() removes the n-th memory reserve map entry from the blob.
This function will delete data from the reservation table and will therefore change the indexes of some entries in the table.
returns: 0, on success -FDT_ERR_NOTFOUND, there is no entry of the given index (i.e. there are less than n+1 reserve map entries) -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_BADLAYOUT, -FDT_ERR_TRUNCATED, standard meanings
{
    struct fdt_reserve_entry *re = fdt_mem_rsv_w_(fdt, n);
    FDT_RW_PROBE(fdt);
    if (n >= fdt_num_mem_rsv(fdt))
        return -FDT_ERR_NOTFOUND;
    return fdt_splice_mem_rsv_(fdt, re, 1, 0);
}
References FDT_ERR_NOTFOUND, fdt_mem_rsv_w_(), fdt_num_mem_rsv(), FDT_RW_PROBE, and fdt_splice_mem_rsv_().
fdt_del_node()
int fdt_del_node (void * fdt, int nodeoffset)
fdt_del_node - delete a node (subtree) @fdt: pointer to the device tree blob @nodeoffset: offset of the node to nop
fdt_del_node() will remove the given node, including all its subnodes if any, from the blob.
This function will delete data from the blob, and will therefore change the offsets of some existing nodes.
returns: 0, on success -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADLAYOUT, -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
{
    int endoffset;
    FDT_RW_PROBE(fdt);
    endoffset = fdt_node_end_offset_(fdt, nodeoffset);
    if (endoffset < 0)
        return endoffset;
    return fdt_splice_struct_(fdt, fdt_offset_ptr_w_(fdt, nodeoffset),
                  endoffset - nodeoffset, 0);
}
References fdt_node_end_offset_(), fdt_offset_ptr_w_(), FDT_RW_PROBE, and fdt_splice_struct_().
fdt_delprop()
int fdt_delprop (void * fdt, int nodeoffset, const char * name)
{
    struct fdt_property *prop;
    int len, proplen;
    FDT_RW_PROBE(fdt);
    prop = fdt_get_property_w(fdt, nodeoffset, name, &len);
    if (!prop)
        return len;
    proplen = sizeof(*prop) + FDT_TAGALIGN(len);
    return fdt_splice_struct_(fdt, prop, proplen, 0);
}
References fdt_get_property_w(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, and fdt_property::len.
fdt_find_add_string_()
static int fdt_find_add_string_ (void * fdt, const char * s, int * allocated) static
fdt_find_add_string_() - Find or allocate a string
@fdt: pointer to the device tree to check/adjust @s: string to find/add @allocated: Set to 0 if the string was found, 1 if not found and so allocated. Ignored if can_assume(NO_ROLLBACK)
Returns
offset of string in the string table (whether found or added)
{
    char *strtab = (char *)fdt + fdt_off_dt_strings(fdt);
    const char *p;
    char *new;
    int len = strlen(s) + 1;
    int err;
    if (!can_assume(NO_ROLLBACK))
        *allocated = 0;
    p = fdt_find_string_(strtab, fdt_size_dt_strings(fdt), s);
    if (p)
        /* found it */
        return (p - strtab);
    new = strtab + fdt_size_dt_strings(fdt);
    err = fdt_splice_string_(fdt, len);
    if (err)
        return err;
    if (!can_assume(NO_ROLLBACK))
        *allocated = 1;
    memcpy(new, s, len);
    return (new - strtab);
}
References can_assume, fdt_find_string_(), fdt_off_dt_strings, fdt_size_dt_strings, fdt_splice_string_(), memcpy(), and strlen().
Referenced by fdt_add_property_().
fdt_open_into()
int fdt_open_into (const void * fdt, void * buf, int bufsize)
{
    int err;
    int mem_rsv_size, struct_size;
    int newsize;
    const char *fdtstart = fdt;
    const char *fdtend = fdtstart + fdt_totalsize(fdt);
    char *tmp;
    FDT_RO_PROBE(fdt);
    mem_rsv_size = (fdt_num_mem_rsv(fdt)+1)
        * sizeof(struct fdt_reserve_entry);
    if (can_assume(LATEST) || fdt_version(fdt) >= 17) {
        struct_size = fdt_size_dt_struct(fdt);
    } else if (fdt_version(fdt) == 16) {
        struct_size = 0;
        while (fdt_next_tag(fdt, struct_size, &struct_size) != FDT_END)
            ;
        if (struct_size < 0)
            return struct_size;
    } else {
        return -FDT_ERR_BADVERSION;
    }
    if (can_assume(LIBFDT_ORDER) ||
        !fdt_blocks_misordered_(fdt, mem_rsv_size, struct_size)) {
        /* no further work necessary */
        err = fdt_move(fdt, buf, bufsize);
        if (err)
            return err;
        fdt_set_version(buf, 17);
        fdt_set_size_dt_struct(buf, struct_size);
        fdt_set_totalsize(buf, bufsize);
        return 0;
    }
    /* Need to reorder */
    newsize = FDT_ALIGN(sizeof(struct fdt_header), 8) + mem_rsv_size
        + struct_size + fdt_size_dt_strings(fdt);
    if (bufsize < newsize)
        return -FDT_ERR_NOSPACE;
    /* First attempt to build converted tree at beginning of buffer */
    tmp = buf;
    /* But if that overlaps with the old tree... */
    if (((tmp + newsize) > fdtstart) && (tmp < fdtend)) {
        /* Try right after the old tree instead */
        tmp = (char *)(uintptr_t)fdtend;
        if ((tmp + newsize) > ((char *)buf + bufsize))
            return -FDT_ERR_NOSPACE;
    }
    fdt_packblocks_(fdt, tmp, mem_rsv_size, struct_size,
            fdt_size_dt_strings(fdt));
    memmove(buf, tmp, newsize);
    fdt_set_magic(buf, FDT_MAGIC);
    fdt_set_totalsize(buf, bufsize);
    fdt_set_version(buf, 17);
    fdt_set_last_comp_version(buf, 16);
    fdt_set_boot_cpuid_phys(buf, fdt_boot_cpuid_phys(fdt));
    return 0;
}
References can_assume, FDT_ALIGN, fdt_blocks_misordered_(), fdt_boot_cpuid_phys, FDT_END, FDT_ERR_BADVERSION, FDT_ERR_NOSPACE, FDT_MAGIC, fdt_move(), fdt_next_tag(), fdt_num_mem_rsv(), fdt_packblocks_(), FDT_RO_PROBE, fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, fdt_version, and memmove().
Referenced by fdt_create_empty_tree().
fdt_pack()
int fdt_pack (void * fdt)
{
    int mem_rsv_size;
    FDT_RW_PROBE(fdt);
    mem_rsv_size = (fdt_num_mem_rsv(fdt)+1)
        * sizeof(struct fdt_reserve_entry);
    fdt_packblocks_(fdt, fdt, mem_rsv_size, fdt_size_dt_struct(fdt),
            fdt_size_dt_strings(fdt));
    fdt_set_totalsize(fdt, fdt_data_size_(fdt));
    return 0;
}
References fdt_data_size_(), fdt_num_mem_rsv(), fdt_packblocks_(), FDT_RW_PROBE, fdt_size_dt_strings, and fdt_size_dt_struct.
fdt_packblocks_()
static void fdt_packblocks_ (const char * old, char * new, int mem_rsv_size, int struct_size, int strings_size) static
{
    int mem_rsv_off, struct_off, strings_off;
    mem_rsv_off = FDT_ALIGN(sizeof(struct fdt_header), 8);
    struct_off = mem_rsv_off + mem_rsv_size;
    strings_off = struct_off + struct_size;
    memmove(new + mem_rsv_off, old + fdt_off_mem_rsvmap(old), mem_rsv_size);
    fdt_set_off_mem_rsvmap(new, mem_rsv_off);
    memmove(new + struct_off, old + fdt_off_dt_struct(old), struct_size);
    fdt_set_off_dt_struct(new, struct_off);
    fdt_set_size_dt_struct(new, struct_size);
    memmove(new + strings_off, old + fdt_off_dt_strings(old), strings_size);
    fdt_set_off_dt_strings(new, strings_off);
    fdt_set_size_dt_strings(new, fdt_size_dt_strings(old));
}
References FDT_ALIGN, fdt_off_dt_strings, fdt_off_dt_struct, fdt_off_mem_rsvmap, fdt_size_dt_strings, and memmove().
Referenced by fdt_open_into(), and fdt_pack().
fdt_resize_property_()
static int fdt_resize_property_ (void * fdt, int nodeoffset, const char * name, int len, struct fdt_property ** prop) static
{
    int oldlen;
    int err;
    *prop = fdt_get_property_w(fdt, nodeoffset, name, &oldlen);
    if (!*prop)
        return oldlen;
    if ((err = fdt_splice_struct_(fdt, (*prop)->data, FDT_TAGALIGN(oldlen),
                      FDT_TAGALIGN(len))))
        return err;
    (*prop)->len = cpu_to_fdt32(len);
    return 0;
}
References cpu_to_fdt32(), fdt_get_property_w(), fdt_splice_struct_(), and FDT_TAGALIGN.
Referenced by fdt_setprop_placeholder().
fdt_rw_probe_()
static int fdt_rw_probe_ (void * fdt) static
{
    if (can_assume(VALID_DTB))
        return 0;
    FDT_RO_PROBE(fdt);
    if (!can_assume(LATEST) && fdt_version(fdt) < 17)
        return -FDT_ERR_BADVERSION;
    if (fdt_blocks_misordered_(fdt, sizeof(struct fdt_reserve_entry),
                   fdt_size_dt_struct(fdt)))
        return -FDT_ERR_BADLAYOUT;
    if (!can_assume(LATEST) && fdt_version(fdt) > 17)
        fdt_set_version(fdt, 17);
    return 0;
}
References can_assume, fdt_blocks_misordered_(), FDT_ERR_BADLAYOUT, FDT_ERR_BADVERSION, FDT_RO_PROBE, fdt_size_dt_struct, and fdt_version.
fdt_set_name()
int fdt_set_name (void * fdt, int nodeoffset, const char * name)
{
    char *namep;
    int oldlen, newlen;
    int err;
    FDT_RW_PROBE(fdt);
    namep = (char *)(uintptr_t)fdt_get_name(fdt, nodeoffset, &oldlen);
    if (!namep)
        return oldlen;
    newlen = strlen(name);
    err = fdt_splice_struct_(fdt, namep, FDT_TAGALIGN(oldlen+1),
                 FDT_TAGALIGN(newlen+1));
    if (err)
        return err;
    memcpy(namep, name, newlen+1);
    return 0;
}
References fdt_get_name(), FDT_RW_PROBE, fdt_splice_struct_(), FDT_TAGALIGN, memcpy(), and strlen().
fdt_setprop()
int fdt_setprop (void * fdt, int nodeoffset, const char * name, const void * val, int len)
{
    void *prop_data;
    int err;
    err = fdt_setprop_placeholder(fdt, nodeoffset, name, len, &prop_data);
    if (err)
        return err;
    if (len)
        memcpy(prop_data, val, len);
    return 0;
}
References fdt_setprop_placeholder(), fdt_property::len, and memcpy().
Referenced by fdt_setprop_u32(), fdt_setprop_u64(), and overlay_apply_node().
fdt_setprop_placeholder()
int fdt_setprop_placeholder (void * fdt, int nodeoffset, const char * name, int len, void ** prop_data)
{
    struct fdt_property *prop;
    int err;
    FDT_RW_PROBE(fdt);
    err = fdt_resize_property_(fdt, nodeoffset, name, len, &prop);
    if (err == -FDT_ERR_NOTFOUND)
        err = fdt_add_property_(fdt, nodeoffset, name, len, &prop);
    if (err)
        return err;
    *prop_data = prop->data;
    return 0;
}
References fdt_property::data, fdt_add_property_(), FDT_ERR_NOTFOUND, fdt_resize_property_(), FDT_RW_PROBE, and fdt_property::len.
Referenced by fdt_setprop(), and overlay_symbol_update().
fdt_splice_()
static int fdt_splice_ (void * fdt, void * splicepoint, int oldlen, int newlen) static
{
    char *p = splicepoint;
    unsigned int dsize = fdt_data_size_(fdt);
    size_t soff = p - (char *)fdt;
    if ((oldlen < 0) || (soff + oldlen < soff) || (soff + oldlen > dsize))
        return -FDT_ERR_BADOFFSET;
    if ((p < (char *)fdt) || (dsize + newlen < (unsigned)oldlen))
        return -FDT_ERR_BADOFFSET;
    if (dsize - oldlen + newlen > fdt_totalsize(fdt))
        return -FDT_ERR_NOSPACE;
    memmove(p + newlen, p + oldlen, ((char *)fdt + dsize) - (p + oldlen));
    return 0;
}
References fdt_data_size_(), FDT_ERR_BADOFFSET, FDT_ERR_NOSPACE, fdt_totalsize, and memmove().
Referenced by fdt_splice_mem_rsv_(), fdt_splice_string_(), and fdt_splice_struct_().
fdt_splice_mem_rsv_()
static int fdt_splice_mem_rsv_ (void * fdt, struct fdt_reserve_entry * p, int oldn, int newn) static
{
    int delta = (newn - oldn) * sizeof(*p);
    int err;
    err = fdt_splice_(fdt, p, oldn * sizeof(*p), newn * sizeof(*p));
    if (err)
        return err;
    fdt_set_off_dt_struct(fdt, fdt_off_dt_struct(fdt) + delta);
    fdt_set_off_dt_strings(fdt, fdt_off_dt_strings(fdt) + delta);
    return 0;
}
References fdt_off_dt_strings, fdt_off_dt_struct, and fdt_splice_().
Referenced by fdt_add_mem_rsv(), and fdt_del_mem_rsv().
fdt_splice_string_()
static int fdt_splice_string_ (void * fdt, int newlen) static
{
    void *p = (char *)fdt
        + fdt_off_dt_strings(fdt) + fdt_size_dt_strings(fdt);
    int err;
    if ((err = fdt_splice_(fdt, p, 0, newlen)))
        return err;
    fdt_set_size_dt_strings(fdt, fdt_size_dt_strings(fdt) + newlen);
    return 0;
}
References fdt_off_dt_strings, fdt_size_dt_strings, and fdt_splice_().
Referenced by fdt_find_add_string_().
fdt_splice_struct_()
static int fdt_splice_struct_ (void * fdt, void * p, int oldlen, int newlen) static
{
    int delta = newlen - oldlen;
    int err;
    if ((err = fdt_splice_(fdt, p, oldlen, newlen)))
        return err;
    fdt_set_size_dt_struct(fdt, fdt_size_dt_struct(fdt) + delta);
    fdt_set_off_dt_strings(fdt, fdt_off_dt_strings(fdt) + delta);
    return 0;
}
References fdt_off_dt_strings, fdt_size_dt_struct, and fdt_splice_().
Referenced by fdt_add_property_(), fdt_add_subnode_namelen(), fdt_appendprop(), fdt_del_node(), fdt_delprop(), fdt_resize_property_(), and fdt_set_name().