ko6: src/soft/external/libfdt/fdt_addresses.c File Reference
fdt_addresses.c File Reference
#include "libfdt_env.h"
#include <external/libfdt/fdt.h>
#include <external/libfdt/libfdt.h>
#include "libfdt_internal.h"
Functions
static int fdt_cells (const void *fdt, int nodeoffset, const char *name)
int fdt_address_cells (const void *fdt, int nodeoffset)
int fdt_size_cells (const void *fdt, int nodeoffset)
int fdt_appendprop_addrrange (void *fdt, int parent, int nodeoffset, const char *name, uint64_t addr, uint64_t size)
Function Documentation
fdt_address_cells()
int fdt_address_cells (const void * fdt, int nodeoffset)
fdt_address_cells - retrieve address size for a bus represented in the tree @fdt: pointer to the device tree blob @nodeoffset: offset of the node to find the address size for
When the node has a valid #address-cells property, returns its value.
returns: 0 <= n < FDT_MAX_NCELLS, on success 2, if the node has no #address-cells property -FDT_ERR_BADNCELLS, if the node has a badly formatted or invalid #address-cells property -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
{
    int val;
    val = fdt_cells(fdt, nodeoffset, "#address-cells");
    if (val == 0)
        return -FDT_ERR_BADNCELLS;
    if (val == -FDT_ERR_NOTFOUND)
        return 2;
    return val;
}
References fdt_cells(), FDT_ERR_BADNCELLS, and FDT_ERR_NOTFOUND.
Referenced by fdt_appendprop_addrrange().
fdt_appendprop_addrrange()
int fdt_appendprop_addrrange (void * fdt, int parent, int nodeoffset, const char * name, uint64_t addr, uint64_t size)
{
    int addr_cells, size_cells, ret;
    uint8_t data[sizeof(fdt64_t) * 2], *prop;
    ret = fdt_address_cells(fdt, parent);
    if (ret < 0)
        return ret;
    addr_cells = ret;
    ret = fdt_size_cells(fdt, parent);
    if (ret < 0)
        return ret;
    size_cells = ret;
    /* check validity of address */
    prop = data;
    if (addr_cells == 1) {
        if ((addr > UINT32_MAX) || (((uint64_t) UINT32_MAX + 1 - addr) < size))
            return -FDT_ERR_BADVALUE;
        fdt32_st(prop, (uint32_t)addr);
    } else if (addr_cells == 2) {
        fdt64_st(prop, addr);
    } else {
        return -FDT_ERR_BADNCELLS;
    }
    /* check validity of size */
    prop += addr_cells * sizeof(fdt32_t);
    if (size_cells == 1) {
        if (size > UINT32_MAX)
            return -FDT_ERR_BADVALUE;
        fdt32_st(prop, (uint32_t)size);
    } else if (size_cells == 2) {
        fdt64_st(prop, size);
    } else {
        return -FDT_ERR_BADNCELLS;
    }
    return fdt_appendprop(fdt, nodeoffset, name, data,
                  (addr_cells + size_cells) * sizeof(fdt32_t));
}
References fdt32_st(), fdt64_st(), fdt_address_cells(), fdt_appendprop(), FDT_ERR_BADNCELLS, FDT_ERR_BADVALUE, fdt_size_cells(), and UINT32_MAX.
fdt_cells()
static int fdt_cells (const void * fdt, int nodeoffset, const char * name) static
{
    const fdt32_t *c;
    uint32_t val;
    int len;
    c = fdt_getprop(fdt, nodeoffset, name, &len);
    if (!c)
        return len;
    if (len != sizeof(*c))
        return -FDT_ERR_BADNCELLS;
    val = fdt32_to_cpu(*c);
    if (val > FDT_MAX_NCELLS)
        return -FDT_ERR_BADNCELLS;
    return (int)val;
}
References fdt32_to_cpu(), FDT_ERR_BADNCELLS, fdt_getprop(), and FDT_MAX_NCELLS.
Referenced by fdt_address_cells(), and fdt_size_cells().
fdt_size_cells()
int fdt_size_cells (const void * fdt, int nodeoffset)
fdt_size_cells - retrieve address range size for a bus represented in the tree @fdt: pointer to the device tree blob @nodeoffset: offset of the node to find the address range size for
When the node has a valid #size-cells property, returns its value.
returns: 0 <= n < FDT_MAX_NCELLS, on success 1, if the node has no #size-cells property -FDT_ERR_BADNCELLS, if the node has a badly formatted or invalid #size-cells property -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
{
    int val;
    val = fdt_cells(fdt, nodeoffset, "#size-cells");
    if (val == -FDT_ERR_NOTFOUND)
        return 1;
    return val;
}
References fdt_cells(), and FDT_ERR_NOTFOUND.
Referenced by fdt_appendprop_addrrange().