ko6: src/soft/external/libfdt/fdt_ro.c File Reference
fdt_ro.c File Reference
#include "libfdt_env.h"
#include <external/libfdt/fdt.h>
#include <external/libfdt/libfdt.h>
#include "libfdt_internal.h"
Functions
static int fdt_nodename_eq_ (const void *fdt, int offset, const char *s, int len)
const char * fdt_get_string (const void *fdt, int stroffset, int *lenp)
const char * fdt_string (const void *fdt, int stroffset)
static int fdt_string_eq_ (const void *fdt, int stroffset, const char *s, int len)
int fdt_find_max_phandle (const void *fdt, uint32_t *phandle)
int fdt_generate_phandle (const void *fdt, uint32_t *phandle)
static const struct fdt_reserve_entry * fdt_mem_rsv (const void *fdt, int n)
int fdt_get_mem_rsv (const void *fdt, int n, uint64_t *address, uint64_t *size)
int fdt_num_mem_rsv (const void *fdt)
static int nextprop_ (const void *fdt, int offset)
int fdt_subnode_offset_namelen (const void *fdt, int offset, const char *name, int namelen)
int fdt_subnode_offset (const void *fdt, int parentoffset, const char *name)
int fdt_path_offset_namelen (const void *fdt, const char *path, int namelen)
int fdt_path_offset (const void *fdt, const char *path)
const char * fdt_get_name (const void *fdt, int nodeoffset, int *len)
int fdt_first_property_offset (const void *fdt, int nodeoffset)
int fdt_next_property_offset (const void *fdt, int offset)
static const struct fdt_property * fdt_get_property_by_offset_ (const void *fdt, int offset, int *lenp)
const struct fdt_property * fdt_get_property_by_offset (const void *fdt, int offset, int *lenp)
static const struct fdt_property * fdt_get_property_namelen_ (const void *fdt, int offset, const char *name, int namelen, int *lenp, int *poffset)
const struct fdt_property * fdt_get_property_namelen (const void *fdt, int offset, const char *name, int namelen, int *lenp)
const struct fdt_property * fdt_get_property (const void *fdt, int nodeoffset, const char *name, int *lenp)
const void * fdt_getprop_namelen (const void *fdt, int nodeoffset, const char *name, int namelen, int *lenp)
const void * fdt_getprop_by_offset (const void *fdt, int offset, const char **namep, int *lenp)
const void * fdt_getprop (const void *fdt, int nodeoffset, const char *name, int *lenp)
uint32_t fdt_get_phandle (const void *fdt, int nodeoffset)
static const void * fdt_path_getprop_namelen (const void *fdt, const char *path, const char *propname, int propnamelen, int *lenp)
const char * fdt_get_alias_namelen (const void *fdt, const char *name, int namelen)
const char * fdt_get_alias (const void *fdt, const char *name)
const char * fdt_get_symbol_namelen (const void *fdt, const char *name, int namelen)
const char * fdt_get_symbol (const void *fdt, const char *name)
int fdt_get_path (const void *fdt, int nodeoffset, char *buf, int buflen)
int fdt_supernode_atdepth_offset (const void *fdt, int nodeoffset, int supernodedepth, int *nodedepth)
int fdt_node_depth (const void *fdt, int nodeoffset)
int fdt_parent_offset (const void *fdt, int nodeoffset)
int fdt_node_offset_by_prop_value (const void *fdt, int startoffset, const char *propname, const void *propval, int proplen)
int fdt_node_offset_by_phandle (const void *fdt, uint32_t phandle)
int fdt_stringlist_contains (const char *strlist, int listlen, const char *str)
int fdt_stringlist_count (const void *fdt, int nodeoffset, const char *property)
int fdt_stringlist_search (const void *fdt, int nodeoffset, const char *property, const char *string)
const char * fdt_stringlist_get (const void *fdt, int nodeoffset, const char *property, int idx, int *lenp)
int fdt_node_check_compatible (const void *fdt, int nodeoffset, const char *compatible)
int fdt_node_offset_by_compatible (const void *fdt, int startoffset, const char *compatible)
Function Documentation
fdt_find_max_phandle()
int fdt_find_max_phandle (const void * fdt, uint32_t * phandle)
fdt_find_max_phandle - find and return the highest phandle in a tree @fdt: pointer to the device tree blob @phandle: return location for the highest phandle value found in the tree
fdt_find_max_phandle() finds the highest phandle value in the given device tree. The value returned in @phandle is only valid if the function returns success.
returns: 0 on success or a negative error code on failure
{
    uint32_t max = 0;
    int offset = -1;
    while (true) {
        uint32_t value;
        offset = fdt_next_node(fdt, offset, NULL);
        if (offset < 0) {
            if (offset == -FDT_ERR_NOTFOUND)
                break;
            return offset;
        }
        value = fdt_get_phandle(fdt, offset);
        if (value > max)
            max = value;
    }
    if (phandle)
        *phandle = max;
    return 0;
}
References FDT_ERR_NOTFOUND, fdt_get_phandle(), fdt_next_node(), and NULL.
Referenced by fdt_generate_phandle(), fdt_get_max_phandle(), and fdt_overlay_apply().
fdt_first_property_offset()
int fdt_first_property_offset (const void * fdt, int nodeoffset)
fdt_first_property_offset - find the offset of a node's first property @fdt: pointer to the device tree blob @nodeoffset: structure block offset of a node
fdt_first_property_offset() finds the first property of the node at the given structure block offset.
returns: structure block offset of the property (>=0), on success -FDT_ERR_NOTFOUND, if the requested node has no properties -FDT_ERR_BADOFFSET, if nodeoffset did not point to an FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
{
    int offset;
    if ((offset = fdt_check_node_offset_(fdt, nodeoffset)) < 0)
        return offset;
    return nextprop_(fdt, offset);
}
References fdt_check_node_offset_(), and nextprop_().
Referenced by fdt_get_property_namelen_().
fdt_generate_phandle()
int fdt_generate_phandle (const void * fdt, uint32_t * phandle)
fdt_generate_phandle - return a new, unused phandle for a device tree blob @fdt: pointer to the device tree blob @phandle: return location for the new phandle
Walks the device tree blob and looks for the highest phandle value. On success, the new, unused phandle value (one higher than the previously highest phandle value in the device tree blob) will be returned in the @phandle parameter.
Return: 0 on success or a negative error-code on failure
{
    uint32_t max;
    int err;
    err = fdt_find_max_phandle(fdt, &max);
    if (err < 0)
        return err;
    if (max == FDT_MAX_PHANDLE)
        return -FDT_ERR_NOPHANDLES;
    if (phandle)
        *phandle = max + 1;
    return 0;
}
References FDT_ERR_NOPHANDLES, fdt_find_max_phandle(), and FDT_MAX_PHANDLE.
fdt_get_alias()
const char * fdt_get_alias (const void * fdt, const char * name)
{
    return fdt_get_alias_namelen(fdt, name, strlen(name));
}
References fdt_get_alias_namelen(), and strlen().
fdt_get_alias_namelen()
const char * fdt_get_alias_namelen (const void * fdt, const char * name, int namelen)
{
    return fdt_path_getprop_namelen(fdt, "/aliases", name, namelen, NULL);
}
References fdt_path_getprop_namelen(), and NULL.
Referenced by fdt_get_alias(), and fdt_path_offset_namelen().
fdt_get_mem_rsv()
int fdt_get_mem_rsv (const void * fdt, int n, uint64_t * address, uint64_t * size)
fdt_get_mem_rsv - retrieve one memory reserve map entry @fdt: pointer to the device tree blob
: index of reserve map entry @address: pointer to 64-bit variable to hold the start address @size: pointer to 64-bit variable to hold the size of the entry
On success, @address and @size will contain the address and size of the n-th reserve map entry from the device tree blob, in native-endian format.
returns: 0, on success -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
{
    const struct fdt_reserve_entry *re;
    FDT_RO_PROBE(fdt);
    re = fdt_mem_rsv(fdt, n);
    if (!can_assume(VALID_INPUT) && !re)
        return -FDT_ERR_BADOFFSET;
    *address = fdt64_ld_(&re->address);
    *size = fdt64_ld_(&re->size);
    return 0;
}
References fdt_reserve_entry::address, can_assume, fdt64_ld_(), FDT_ERR_BADOFFSET, fdt_mem_rsv(), FDT_RO_PROBE, and fdt_reserve_entry::size.
fdt_get_name()
const char * fdt_get_name (const void * fdt, int nodeoffset, int * lenp)
fdt_get_name - retrieve the name of a given node @fdt: pointer to the device tree blob @nodeoffset: structure block offset of the starting node @lenp: pointer to an integer variable (will be overwritten) or NULL
fdt_get_name() retrieves the name (including unit address) of the device tree node at structure block offset nodeoffset. If lenp is non-NULL, the length of this name is also returned, in the integer pointed to by lenp.
returns: pointer to the node's name, on success If lenp is non-NULL, *lenp contains the length of that name (>=0) NULL, on error if lenp is non-NULL *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
{
    const struct fdt_node_header *nh = fdt_offset_ptr_(fdt, nodeoffset);
    const char *nameptr;
    int err;
    if (((err = fdt_ro_probe_(fdt)) < 0)
        || ((err = fdt_check_node_offset_(fdt, nodeoffset)) < 0))
            goto fail;
    nameptr = nh->name;
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        /*
         * For old FDT versions, match the naming conventions of V16:
         * give only the leaf name (after all /). The actual tree
         * contents are loosely checked.
         */
        const char *leaf;
        leaf = strrchr(nameptr, '/');
        if (leaf == NULL) {
            err = -FDT_ERR_BADSTRUCTURE;
            goto fail;
        }
        nameptr = leaf+1;
    }
    if (len)
        *len = strlen(nameptr);
    return nameptr;
 fail:
    if (len)
        *len = err;
    return NULL;
}
References can_assume, fdt_check_node_offset_(), FDT_ERR_BADSTRUCTURE, fdt_offset_ptr_(), fdt_ro_probe_(), fdt_version, fdt_node_header::name, NULL, strlen(), and strrchr().
Referenced by fdt_check_full(), fdt_get_path(), fdt_nodename_eq_(), fdt_set_name(), get_path_len(), overlay_apply_node(), and overlay_update_local_node_references().
fdt_get_path()
int fdt_get_path (const void * fdt, int nodeoffset, char * buf, int buflen)
fdt_get_path - determine the full path of a node @fdt: pointer to the device tree blob @nodeoffset: offset of the node whose path to find @buf: character buffer to contain the returned path (will be overwritten) @buflen: size of the character buffer at buf
fdt_get_path() computes the full path of the node at offset nodeoffset, and records that path in the buffer at buf.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: 0, on success buf contains the absolute path of the node at nodeoffset, as a NUL-terminated string. -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_NOSPACE, the path of the given node is longer than (bufsize-1) characters and will not fit in the given buffer. -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int pdepth = 0, p = 0;
    int offset, depth, namelen;
    const char *name;
    FDT_RO_PROBE(fdt);
    if (buflen < 2)
        return -FDT_ERR_NOSPACE;
    for (offset = 0, depth = 0;
         (offset >= 0) && (offset <= nodeoffset);
         offset = fdt_next_node(fdt, offset, &depth)) {
        while (pdepth > depth) {
            do {
                p--;
            } while (buf[p-1] != '/');
            pdepth--;
        }
        if (pdepth >= depth) {
            name = fdt_get_name(fdt, offset, &namelen);
            if (!name)
                return namelen;
            if ((p + namelen + 1) <= buflen) {
                memcpy(buf + p, name, namelen);
                p += namelen;
                buf[p++] = '/';
                pdepth++;
            }
        }
        if (offset == nodeoffset) {
            if (pdepth < (depth + 1))
                return -FDT_ERR_NOSPACE;
            if (p > 1) /* special case so that root path is "/", not "" */
                p--;
            buf[p] = '\0';
            return 0;
        }
    }
    if ((offset == -FDT_ERR_NOTFOUND) || (offset >= 0))
        return -FDT_ERR_BADOFFSET;
    else if (offset == -FDT_ERR_BADOFFSET)
        return -FDT_ERR_BADSTRUCTURE;
    return offset; /* error from fdt_next_node() */
}
References FDT_ERR_BADOFFSET, FDT_ERR_BADSTRUCTURE, FDT_ERR_NOSPACE, FDT_ERR_NOTFOUND, fdt_get_name(), fdt_next_node(), FDT_RO_PROBE, and memcpy().
Referenced by overlay_symbol_update().
fdt_get_phandle()
uint32_t fdt_get_phandle (const void * fdt, int nodeoffset)
fdt_get_phandle - retrieve the phandle of a given node @fdt: pointer to the device tree blob @nodeoffset: structure block offset of the node
fdt_get_phandle() retrieves the phandle of the device tree node at structure block offset nodeoffset.
returns: the phandle of the node at nodeoffset, on success (!= 0, != -1) 0, if the node has no phandle, or another error occurs
{
    const fdt32_t *php;
    int len;
    /* FIXME: This is a bit sub-optimal, since we potentially scan
     * over all the properties twice. */
    php = fdt_getprop(fdt, nodeoffset, "phandle", &len);
    if (!php || (len != sizeof(*php))) {
        php = fdt_getprop(fdt, nodeoffset, "linux,phandle", &len);
        if (!php || (len != sizeof(*php)))
            return 0;
    }
    return fdt32_ld_(php);
}
References fdt32_ld_(), fdt_getprop(), and fdt_property::len.
Referenced by fdt_find_max_phandle(), fdt_node_offset_by_phandle(), and overlay_fixup_one_phandle().
fdt_get_property()
const struct fdt_property * fdt_get_property (const void * fdt, int nodeoffset, const char * name, int * lenp)
{
    return fdt_get_property_namelen(fdt, nodeoffset, name,
                    strlen(name), lenp);
}
References fdt_get_property_namelen(), and strlen().
Referenced by fdt_get_property_w().
fdt_get_property_by_offset()
const struct fdt_property * fdt_get_property_by_offset (const void * fdt, int offset, int * lenp)
fdt_get_property_by_offset - retrieve the property at a given offset @fdt: pointer to the device tree blob @offset: offset of the property to retrieve @lenp: pointer to an integer variable (will be overwritten) or NULL
fdt_get_property_by_offset() retrieves a pointer to the fdt_property structure within the device tree blob at the given offset. If lenp is non-NULL, the length of the property value is also returned, in the integer pointed to by lenp.
Note that this code only works on device tree versions >= 16. fdt_getprop() works on all versions.
returns: pointer to the structure representing the property if lenp is non-NULL, *lenp contains the length of the property value (>=0) NULL, on error if lenp is non-NULL, *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
{
    /* Prior to version 16, properties may need realignment
     * and this API does not work. fdt_getprop_*() will, however. */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        if (lenp)
            *lenp = -FDT_ERR_BADVERSION;
        return NULL;
    }
    return fdt_get_property_by_offset_(fdt, offset, lenp);
}
References can_assume, FDT_ERR_BADVERSION, fdt_get_property_by_offset_(), fdt_version, and NULL.
Referenced by fdt_get_property_by_offset_w().
fdt_get_property_by_offset_()
static const struct fdt_property * fdt_get_property_by_offset_ (const void * fdt, int offset, int * lenp) static
{
    int err;
    const struct fdt_property *prop;
    if (!can_assume(VALID_INPUT) &&
        (err = fdt_check_prop_offset_(fdt, offset)) < 0) {
        if (lenp)
            *lenp = err;
        return NULL;
    }
    prop = fdt_offset_ptr_(fdt, offset);
    if (lenp)
        *lenp = fdt32_ld_(&prop->len);
    return prop;
}
References can_assume, fdt32_ld_(), fdt_check_prop_offset_(), fdt_offset_ptr_(), fdt_property::len, and NULL.
Referenced by fdt_get_property_by_offset(), fdt_get_property_namelen_(), and fdt_getprop_by_offset().
fdt_get_property_namelen()
const struct fdt_property * fdt_get_property_namelen (const void * fdt, int offset, const char * name, int namelen, int * lenp)
{
    /* Prior to version 16, properties may need realignment
     * and this API does not work. fdt_getprop_*() will, however. */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10) {
        if (lenp)
            *lenp = -FDT_ERR_BADVERSION;
        return NULL;
    }
    return fdt_get_property_namelen_(fdt, offset, name, namelen, lenp,
                     NULL);
}
References can_assume, FDT_ERR_BADVERSION, fdt_get_property_namelen_(), fdt_version, and NULL.
Referenced by fdt_get_property().
fdt_get_property_namelen_()
static const struct fdt_property * fdt_get_property_namelen_ (const void * fdt, int offset, const char * name, int namelen, int * lenp, int * poffset) static
{
    for (offset = fdt_first_property_offset(fdt, offset);
         (offset >= 0);
         (offset = fdt_next_property_offset(fdt, offset))) {
        const struct fdt_property *prop;
        prop = fdt_get_property_by_offset_(fdt, offset, lenp);
        if (!can_assume(LIBFDT_FLAWLESS) && !prop) {
            offset = -FDT_ERR_INTERNAL;
            break;
        }
        if (fdt_string_eq_(fdt, fdt32_ld_(&prop->nameoff),
                   name, namelen)) {
            if (poffset)
                *poffset = offset;
            return prop;
        }
    }
    if (lenp)
        *lenp = offset;
    return NULL;
}
References can_assume, fdt32_ld_(), FDT_ERR_INTERNAL, fdt_first_property_offset(), fdt_get_property_by_offset_(), fdt_next_property_offset(), fdt_string_eq_(), fdt_property::nameoff, and NULL.
Referenced by fdt_get_property_namelen(), and fdt_getprop_namelen().
fdt_get_string()
const char * fdt_get_string (const void * fdt, int stroffset, int * lenp)
fdt_get_string - retrieve a string from the strings block of a device tree @fdt: pointer to the device tree blob @stroffset: offset of the string within the strings block (native endian) @lenp: optional pointer to return the string's length
fdt_get_string() retrieves a pointer to a single string from the strings block of the device tree blob at fdt, and optionally also returns the string's length in *lenp.
returns: a pointer to the string, on success NULL, if stroffset is out of bounds, or doesn't point to a valid string
{
    int32_t totalsize;
    uint32_t absoffset;
    size_t len;
    int err;
    const char *s, *n;
    if (can_assume(VALID_INPUT)) {
        s = (const char *)fdt + fdt_off_dt_strings(fdt) + stroffset;
        if (lenp)
            *lenp = strlen(s);
        return s;
    }
    totalsize = fdt_ro_probe_(fdt);
    err = totalsize;
    if (totalsize < 0)
        goto fail;
    err = -FDT_ERR_BADOFFSET;
    absoffset = stroffset + fdt_off_dt_strings(fdt);
    if (absoffset >= (unsigned)totalsize)
        goto fail;
    len = totalsize - absoffset;
    if (fdt_magic(fdt) == FDT_MAGIC) {
        if (stroffset < 0)
            goto fail;
        if (can_assume(LATEST) || fdt_version(fdt) >= 17) {
            if ((unsigned)stroffset >= fdt_size_dt_strings(fdt))
                goto fail;
            if ((fdt_size_dt_strings(fdt) - stroffset) < len)
                len = fdt_size_dt_strings(fdt) - stroffset;
        }
    } else if (fdt_magic(fdt) == FDT_SW_MAGIC) {
        unsigned int sw_stroffset = -stroffset;
        if ((stroffset >= 0) ||
            (sw_stroffset > fdt_size_dt_strings(fdt)))
            goto fail;
        if (sw_stroffset < len)
            len = sw_stroffset;
    } else {
        err = -FDT_ERR_INTERNAL;
        goto fail;
    }
    s = (const char *)fdt + absoffset;
    n = memchr(s, '\0', len);
    if (!n) {
        /* missing terminating NULL */
        err = -FDT_ERR_TRUNCATED;
        goto fail;
    }
    if (lenp)
        *lenp = n - s;
    return s;
fail:
    if (lenp)
        *lenp = err;
    return NULL;
}
References can_assume, FDT_ERR_BADOFFSET, FDT_ERR_INTERNAL, FDT_ERR_TRUNCATED, FDT_MAGIC, fdt_magic, fdt_off_dt_strings, fdt_ro_probe_(), fdt_size_dt_strings, FDT_SW_MAGIC, fdt_version, memchr(), NULL, and strlen().
Referenced by fdt_getprop_by_offset(), fdt_string(), and fdt_string_eq_().
fdt_get_symbol()
const char * fdt_get_symbol (const void * fdt, const char * name)
{
    return fdt_get_symbol_namelen(fdt, name, strlen(name));
}
References fdt_get_symbol_namelen(), and strlen().
fdt_get_symbol_namelen()
const char * fdt_get_symbol_namelen (const void * fdt, const char * name, int namelen)
{
    return fdt_path_getprop_namelen(fdt, "/__symbols__", name, namelen, NULL);
}
References fdt_path_getprop_namelen(), and NULL.
Referenced by fdt_get_symbol().
fdt_getprop()
const void * fdt_getprop (const void * fdt, int nodeoffset, const char * name, int * lenp)
{
    return fdt_getprop_namelen(fdt, nodeoffset, name, strlen(name), lenp);
}
References fdt_getprop_namelen(), and strlen().
Referenced by fdt_cells(), fdt_get_phandle(), fdt_getprop_w(), fdt_node_check_compatible(), fdt_node_offset_by_prop_value(), fdt_overlay_target_offset(), fdt_setprop_inplace(), fdt_stringlist_count(), fdt_stringlist_get(), fdt_stringlist_search(), get_base_address(), get_irq(), overlay_fixup_one_phandle(), overlay_get_target_phandle(), overlay_phandle_add_offset(), and overlay_update_local_node_references().
fdt_getprop_by_offset()
const void * fdt_getprop_by_offset (const void * fdt, int offset, const char ** namep, int * lenp)
fdt_getprop_by_offset - retrieve the value of a property at a given offset @fdt: pointer to the device tree blob @offset: offset of the property to read @namep: pointer to a string variable (will be overwritten) or NULL @lenp: pointer to an integer variable (will be overwritten) or NULL
fdt_getprop_by_offset() retrieves a pointer to the value of the property at structure block offset 'offset' (this will be a pointer to within the device blob itself, not a copy of the value). If lenp is non-NULL, the length of the property value is also returned, in the integer pointed to by lenp. If namep is non-NULL, the property's namne will also be returned in the char * pointed to by namep (this will be a pointer to within the device tree's string block, not a new copy of the name).
returns: pointer to the property's value if lenp is non-NULL, *lenp contains the length of the property value (>=0) if namep is non-NULL *namep contiains a pointer to the property name. NULL, on error if lenp is non-NULL, *lenp contains an error code (<0): -FDT_ERR_BADOFFSET, nodeoffset did not point to FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings
{
    const struct fdt_property *prop;
    prop = fdt_get_property_by_offset_(fdt, offset, lenp);
    if (!prop)
        return NULL;
    if (namep) {
        const char *name;
        int namelen;
        if (!can_assume(VALID_INPUT)) {
            name = fdt_get_string(fdt, fdt32_ld_(&prop->nameoff),
                          &namelen);
            *namep = name;
            if (!name) {
                if (lenp)
                    *lenp = namelen;
                return NULL;
            }
        } else {
            *namep = fdt_string(fdt, fdt32_ld_(&prop->nameoff));
        }
    }
    /* Handle realignment */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10 &&
        (offset + sizeof(*prop)) % 8 && fdt32_ld_(&prop->len) >= 8)
        return prop->data + 4;
    return prop->data;
}
References can_assume, fdt_property::data, fdt32_ld_(), fdt_get_property_by_offset_(), fdt_get_string(), fdt_string(), fdt_version, fdt_property::len, fdt_property::nameoff, and NULL.
Referenced by fdt_check_full(), overlay_apply_node(), overlay_fixup_phandle(), overlay_symbol_update(), and overlay_update_local_node_references().
fdt_getprop_namelen()
const void * fdt_getprop_namelen (const void * fdt, int nodeoffset, const char * name, int namelen, int * lenp)
{
    int poffset;
    const struct fdt_property *prop;
    prop = fdt_get_property_namelen_(fdt, nodeoffset, name, namelen, lenp,
                     &poffset);
    if (!prop)
        return NULL;
    /* Handle realignment */
    if (!can_assume(LATEST) && fdt_version(fdt) < 0x10 &&
        (poffset + sizeof(*prop)) % 8 && fdt32_ld_(&prop->len) >= 8)
        return prop->data + 4;
    return prop->data;
}
References can_assume, fdt_property::data, fdt32_ld_(), fdt_get_property_namelen_(), fdt_version, fdt_property::len, and NULL.
Referenced by fdt_getprop(), fdt_getprop_namelen_w(), and fdt_path_getprop_namelen().
fdt_mem_rsv()
static const struct fdt_reserve_entry * fdt_mem_rsv (const void * fdt, int n) static
{
    unsigned int offset = n * sizeof(struct fdt_reserve_entry);
    unsigned int absoffset = fdt_off_mem_rsvmap(fdt) + offset;
    if (!can_assume(VALID_INPUT)) {
        if (absoffset < fdt_off_mem_rsvmap(fdt))
            return NULL;
        if (absoffset > fdt_totalsize(fdt) -
            sizeof(struct fdt_reserve_entry))
            return NULL;
    }
    return fdt_mem_rsv_(fdt, n);
}
References can_assume, fdt_mem_rsv_(), fdt_off_mem_rsvmap, fdt_totalsize, and NULL.
Referenced by fdt_get_mem_rsv(), and fdt_num_mem_rsv().
fdt_next_property_offset()
int fdt_next_property_offset (const void * fdt, int offset)
fdt_next_property_offset - step through a node's properties @fdt: pointer to the device tree blob @offset: structure block offset of a property
fdt_next_property_offset() finds the property immediately after the one at the given structure block offset. This will be a property of the same node as the given property.
returns: structure block offset of the next property (>=0), on success -FDT_ERR_NOTFOUND, if the given property is the last in its node -FDT_ERR_BADOFFSET, if nodeoffset did not point to an FDT_PROP tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
{
    if ((offset = fdt_check_prop_offset_(fdt, offset)) < 0)
        return offset;
    return nextprop_(fdt, offset);
}
References fdt_check_prop_offset_(), and nextprop_().
Referenced by fdt_get_property_namelen_().
fdt_node_check_compatible()
int fdt_node_check_compatible (const void * fdt, int nodeoffset, const char * compatible)
fdt_node_check_compatible - check a node's compatible property @fdt: pointer to the device tree blob @nodeoffset: offset of a tree node @compatible: string to match against
fdt_node_check_compatible() returns 0 if the given node contains a @compatible property with the given string as one of its elements, it returns non-zero otherwise, or on error.
returns: 0, if the node has a 'compatible' property listing the given string 1, if the node has a 'compatible' property, but it does not list the given string -FDT_ERR_NOTFOUND, if the given node has no 'compatible' property -FDT_ERR_BADOFFSET, if nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    const void *prop;
    int len;
    prop = fdt_getprop(fdt, nodeoffset, "compatible", &len);
    if (!prop)
        return len;
    return !fdt_stringlist_contains(prop, len, compatible);
}
References fdt_getprop(), fdt_stringlist_contains(), and fdt_property::len.
Referenced by fdt_node_offset_by_compatible().
fdt_node_depth()
int fdt_node_depth (const void * fdt, int nodeoffset)
fdt_node_depth - find the depth of a given node @fdt: pointer to the device tree blob @nodeoffset: offset of the node whose parent to find
fdt_node_depth() finds the depth of a given node. The root node has depth 0, its immediate subnodes depth 1 and so forth.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: depth of the node at nodeoffset (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int nodedepth;
    int err;
    err = fdt_supernode_atdepth_offset(fdt, nodeoffset, 0, &nodedepth);
    if (err)
        return (can_assume(LIBFDT_FLAWLESS) || err < 0) ? err :
            -FDT_ERR_INTERNAL;
    return nodedepth;
}
References can_assume, FDT_ERR_INTERNAL, and fdt_supernode_atdepth_offset().
Referenced by fdt_parent_offset().
fdt_node_offset_by_compatible()
int fdt_node_offset_by_compatible (const void * fdt, int startoffset, const char * compatible)
fdt_node_offset_by_compatible - find nodes with a given 'compatible' value @fdt: pointer to the device tree blob @startoffset: only find nodes after this offset @compatible: 'compatible' string to match against
fdt_node_offset_by_compatible() returns the offset of the first node after startoffset, which has a 'compatible' property which lists the given compatible string; or if startoffset is -1, the very first such node in the tree.
To iterate through all nodes matching the criterion, the following idiom can be used: offset = fdt_node_offset_by_compatible(fdt, -1, compatible); while (offset != -FDT_ERR_NOTFOUND) { // other code here offset = fdt_node_offset_by_compatible(fdt, offset, compatible); }
Note the -1 in the first call to the function, if 0 is used here instead, the function will never locate the root node, even if it matches the criterion.
returns: structure block offset of the located node (>= 0, >startoffset), on success -FDT_ERR_NOTFOUND, no node matching the criterion exists in the tree after startoffset -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int offset, err;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we scan each
     * property of a node in fdt_node_check_compatible(), then if
     * that didn't find what we want, we scan over them again
     * making our way to the next node.  Still it's the easiest to
     * implement approach; performance can come later. */
    for (offset = fdt_next_node(fdt, startoffset, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        err = fdt_node_check_compatible(fdt, offset, compatible);
        if ((err < 0) && (err != -FDT_ERR_NOTFOUND))
            return err;
        else if (err == 0)
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
References FDT_ERR_NOTFOUND, fdt_next_node(), fdt_node_check_compatible(), FDT_RO_PROBE, and NULL.
Referenced by soc_dma_init(), soc_icu_init(), soc_timer_init(), and soc_tty_init().
fdt_node_offset_by_phandle()
int fdt_node_offset_by_phandle (const void * fdt, uint32_t phandle)
fdt_node_offset_by_phandle - find the node with a given phandle @fdt: pointer to the device tree blob @phandle: phandle value
fdt_node_offset_by_phandle() returns the offset of the node which has the given phandle value. If there is more than one node in the tree with the given phandle (an invalid tree), results are undefined.
returns: structure block offset of the located node (>= 0), on success -FDT_ERR_NOTFOUND, no node with that phandle exists -FDT_ERR_BADPHANDLE, given phandle value was invalid (0 or -1) -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int offset;
    if ((phandle == 0) || (phandle == ~0U))
        return -FDT_ERR_BADPHANDLE;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we
     * potentially scan each property of a node in
     * fdt_get_phandle(), then if that didn't find what
     * we want, we scan over them again making our way to the next
     * node.  Still it's the easiest to implement approach;
     * performance can come later. */
    for (offset = fdt_next_node(fdt, -1, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        if (fdt_get_phandle(fdt, offset) == phandle)
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
References FDT_ERR_BADPHANDLE, fdt_get_phandle(), fdt_next_node(), FDT_RO_PROBE, and NULL.
Referenced by fdt_overlay_target_offset().
fdt_node_offset_by_prop_value()
int fdt_node_offset_by_prop_value (const void * fdt, int startoffset, const char * propname, const void * propval, int proplen)
fdt_node_offset_by_prop_value - find nodes with a given property value @fdt: pointer to the device tree blob @startoffset: only find nodes after this offset @propname: property name to check @propval: property value to search for @proplen: length of the value in propval
fdt_node_offset_by_prop_value() returns the offset of the first node after startoffset, which has a property named propname whose value is of length proplen and has value equal to propval; or if startoffset is -1, the very first such node in the tree.
To iterate through all nodes matching the criterion, the following idiom can be used: offset = fdt_node_offset_by_prop_value(fdt, -1, propname, propval, proplen); while (offset != -FDT_ERR_NOTFOUND) { // other code here offset = fdt_node_offset_by_prop_value(fdt, offset, propname, propval, proplen); }
Note the -1 in the first call to the function, if 0 is used here instead, the function will never locate the root node, even if it matches the criterion.
returns: structure block offset of the located node (>= 0, >startoffset), on success -FDT_ERR_NOTFOUND, no node matching the criterion exists in the tree after startoffset -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int offset;
    const void *val;
    int len;
    FDT_RO_PROBE(fdt);
    /* FIXME: The algorithm here is pretty horrible: we scan each
     * property of a node in fdt_getprop(), then if that didn't
     * find what we want, we scan over them again making our way
     * to the next node.  Still it's the easiest to implement
     * approach; performance can come later. */
    for (offset = fdt_next_node(fdt, startoffset, NULL);
         offset >= 0;
         offset = fdt_next_node(fdt, offset, NULL)) {
        val = fdt_getprop(fdt, offset, propname, &len);
        if (val && (len == proplen)
            && (memcmp(val, propval, len) == 0))
            return offset;
    }
    return offset; /* error from fdt_next_node() */
}
References fdt_getprop(), fdt_next_node(), FDT_RO_PROBE, fdt_property::len, memcmp(), and NULL.
fdt_nodename_eq_()
static int fdt_nodename_eq_ (const void * fdt, int offset, const char * s, int len) static
{
    int olen;
    const char *p = fdt_get_name(fdt, offset, &olen);
    if (!p || olen < len)
        /* short match */
        return 0;
    if (memcmp(p, s, len) != 0)
        return 0;
    if (p[len] == '\0')
        return 1;
    else if (!memchr(s, '@', len) && (p[len] == '@'))
        return 1;
    else
        return 0;
}
References fdt_get_name(), memchr(), and memcmp().
Referenced by fdt_subnode_offset_namelen().
fdt_num_mem_rsv()
int fdt_num_mem_rsv (const void * fdt)
fdt_num_mem_rsv - retrieve the number of memory reserve map entries @fdt: pointer to the device tree blob
Returns the number of entries in the device tree blob's memory reservation map. This does not include the terminating 0,0 entry or any other (0,0) entries reserved for expansion.
returns: the number of entries
{
    int i;
    const struct fdt_reserve_entry *re;
    for (i = 0; (re = fdt_mem_rsv(fdt, i)) != NULL; i++) {
        if (fdt64_ld_(&re->size) == 0)
            return i;
    }
    return -FDT_ERR_TRUNCATED;
}
References fdt64_ld_(), FDT_ERR_TRUNCATED, fdt_mem_rsv(), NULL, and fdt_reserve_entry::size.
Referenced by fdt_add_mem_rsv(), fdt_check_full(), fdt_del_mem_rsv(), fdt_open_into(), and fdt_pack().
fdt_parent_offset()
int fdt_parent_offset (const void * fdt, int nodeoffset)
fdt_parent_offset - find the parent of a given node @fdt: pointer to the device tree blob @nodeoffset: offset of the node whose parent to find
fdt_parent_offset() locates the parent node of a given node (that is, it finds the offset of the node which contains the node at nodeoffset as a subnode).
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset, twice.
returns: structure block offset of the parent of the node at nodeoffset (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int nodedepth = fdt_node_depth(fdt, nodeoffset);
    if (nodedepth < 0)
        return nodedepth;
    return fdt_supernode_atdepth_offset(fdt, nodeoffset,
                        nodedepth - 1, NULL);
}
References fdt_node_depth(), fdt_supernode_atdepth_offset(), and NULL.
Referenced by get_path_len().
fdt_path_getprop_namelen()
static const void * fdt_path_getprop_namelen (const void * fdt, const char * path, const char * propname, int propnamelen, int * lenp) static
{
    int offset = fdt_path_offset(fdt, path);
    if (offset < 0)
        return NULL;
    return fdt_getprop_namelen(fdt, offset, propname, propnamelen, lenp);
}
References fdt_getprop_namelen(), fdt_path_offset(), and NULL.
Referenced by fdt_get_alias_namelen(), and fdt_get_symbol_namelen().
fdt_path_offset()
int fdt_path_offset (const void * fdt, const char * path)
fdt_path_offset - find a tree node by its full path @fdt: pointer to the device tree blob @path: full path of the node to locate
fdt_path_offset() finds a node of a given path in the device tree. Each path component may omit the unit address portion, but the results of this are undefined if any such path component is ambiguous (that is if there are multiple nodes at the relevant level matching the given component, differentiated only by unit address).
If the path is not absolute (i.e. does not begin with '/'), the first component is treated as an alias. That is, the property by that name is looked up in the /aliases node, and the value of that property used in place of that first component.
For example, for this small fragment
/ { aliases { i2c2 = &foo; // RHS compiles to "/soc@0/i2c@30a40000/eeprom@52" }; soc@0 { foo: i2c@30a40000 { bar: eeprom@52 { }; }; }; };
these would be equivalent:
/soc@0/i2c@30a40000/eeprom@52 i2c2/eeprom@52
returns: structure block offset of the node with the requested path (>=0), on success -FDT_ERR_BADPATH, given path does not begin with '/' and the first component is not a valid alias -FDT_ERR_NOTFOUND, if the requested node does not exist -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, -FDT_ERR_TRUNCATED, standard meanings.
{
    return fdt_path_offset_namelen(fdt, path, strlen(path));
}
References fdt_path_offset_namelen(), and strlen().
Referenced by fdt_overlay_target_offset(), fdt_path_getprop_namelen(), fdt_path_offset_namelen(), overlay_fixup_one_phandle(), overlay_fixup_phandles(), and overlay_update_local_references().
fdt_path_offset_namelen()
int fdt_path_offset_namelen (const void * fdt, const char * path, int namelen)
fdt_path_offset_namelen - find a tree node by its full path @fdt: pointer to the device tree blob @path: full path of the node to locate @namelen: number of characters of path to consider
Identical to fdt_path_offset(), but only consider the first namelen characters of path as the path name.
Return: offset of the node or negative libfdt error value otherwise
{
    const char *end = path + namelen;
    const char *p = path;
    int offset = 0;
    FDT_RO_PROBE(fdt);
    /* see if we have an alias */
    if (*path != '/') {
        const char *q = memchr(path, '/', end - p);
        if (!q)
            q = end;
        p = fdt_get_alias_namelen(fdt, p, q - p);
        if (!p)
            return -FDT_ERR_BADPATH;
        offset = fdt_path_offset(fdt, p);
        p = q;
    }
    while (p < end) {
        const char *q;
        while (*p == '/') {
            p++;
            if (p == end)
                return offset;
        }
        q = memchr(p, '/', end - p);
        if (! q)
            q = end;
        offset = fdt_subnode_offset_namelen(fdt, offset, p, q-p);
        if (offset < 0)
            return offset;
        p = q;
    }
    return offset;
}
References FDT_ERR_BADPATH, fdt_get_alias_namelen(), fdt_path_offset(), FDT_RO_PROBE, fdt_subnode_offset_namelen(), and memchr().
Referenced by fdt_path_offset(), and overlay_fixup_one_phandle().
fdt_string()
const char * fdt_string (const void * fdt, int stroffset)
fdt_string - retrieve a string from the strings block of a device tree @fdt: pointer to the device tree blob @stroffset: offset of the string within the strings block (native endian)
fdt_string() retrieves a pointer to a single string from the strings block of the device tree blob at fdt.
returns: a pointer to the string, on success NULL, if stroffset is out of bounds, or doesn't point to a valid string
{
    return fdt_get_string(fdt, stroffset, NULL);
}
References fdt_get_string(), and NULL.
Referenced by fdt_getprop_by_offset().
fdt_string_eq_()
static int fdt_string_eq_ (const void * fdt, int stroffset, const char * s, int len) static
{
    int slen;
    const char *p = fdt_get_string(fdt, stroffset, &slen);
    return p && (slen == len) && (memcmp(p, s, len) == 0);
}
References fdt_get_string(), and memcmp().
Referenced by fdt_get_property_namelen_().
fdt_stringlist_contains()
int fdt_stringlist_contains (const char * strlist, int listlen, const char * str)
fdt_stringlist_contains - check a string list property for a string @strlist: Property containing a list of strings to check @listlen: Length of property @str: String to search for
This is a utility function provided for convenience. The list contains one or more strings, each terminated by \0, as is found in a device tree "compatible" property.
Return: 1 if the string is found in the list, 0 not found, or invalid list
{
    int len = strlen(str);
    const char *p;
    while (listlen >= len) {
        if (memcmp(str, strlist, len+1) == 0)
            return 1;
        p = memchr(strlist, '\0', listlen);
        if (!p)
            return 0; /* malformed strlist.. */
        listlen -= (p-strlist) + 1;
        strlist = p + 1;
    }
    return 0;
}
References fdt_property::len, memchr(), memcmp(), and strlen().
Referenced by fdt_node_check_compatible().
fdt_stringlist_count()
int fdt_stringlist_count (const void * fdt, int nodeoffset, const char * property)
{
    const char *list, *end;
    int length, count = 0;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list)
        return length;
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end)
            return -FDT_ERR_BADVALUE;
        list += length;
        count++;
    }
    return count;
}
References FDT_ERR_BADVALUE, fdt_getprop(), and strnlen().
fdt_stringlist_get()
const char * fdt_stringlist_get (const void * fdt, int nodeoffset, const char * property, int idx, int * lenp)
{
    const char *list, *end;
    int length;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list) {
        if (lenp)
            *lenp = length;
        return NULL;
    }
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end) {
            if (lenp)
                *lenp = -FDT_ERR_BADVALUE;
            return NULL;
        }
        if (idx == 0) {
            if (lenp)
                *lenp = length - 1;
            return list;
        }
        list += length;
        idx--;
    }
    if (lenp)
        *lenp = -FDT_ERR_NOTFOUND;
    return NULL;
}
References FDT_ERR_BADVALUE, FDT_ERR_NOTFOUND, fdt_getprop(), NULL, and strnlen().
fdt_stringlist_search()
int fdt_stringlist_search (const void * fdt, int nodeoffset, const char * property, const char * string)
{
    int length, len, idx = 0;
    const char *list, *end;
    list = fdt_getprop(fdt, nodeoffset, property, &length);
    if (!list)
        return length;
    len = strlen(string) + 1;
    end = list + length;
    while (list < end) {
        length = strnlen(list, end - list) + 1;
        /* Abort if the last string isn't properly NUL-terminated. */
        if (list + length > end)
            return -FDT_ERR_BADVALUE;
        if (length == len && memcmp(list, string, length) == 0)
            return idx;
        list += length;
        idx++;
    }
    return -FDT_ERR_NOTFOUND;
}
References FDT_ERR_BADVALUE, FDT_ERR_NOTFOUND, fdt_getprop(), fdt_property::len, memcmp(), strlen(), and strnlen().
fdt_subnode_offset()
int fdt_subnode_offset (const void * fdt, int parentoffset, const char * name)
{
    return fdt_subnode_offset_namelen(fdt, parentoffset, name, strlen(name));
}
References fdt_subnode_offset_namelen(), and strlen().
Referenced by overlay_apply_node(), overlay_merge(), overlay_symbol_update(), and overlay_update_local_node_references().
fdt_subnode_offset_namelen()
int fdt_subnode_offset_namelen (const void * fdt, int offset, const char * name, int namelen)
{
    int depth;
    FDT_RO_PROBE(fdt);
    for (depth = 0;
         (offset >= 0) && (depth >= 0);
         offset = fdt_next_node(fdt, offset, &depth))
        if ((depth == 1)
            && fdt_nodename_eq_(fdt, offset, name, namelen))
            return offset;
    if (depth < 0)
        return -FDT_ERR_NOTFOUND;
    return offset; /* error */
}
References FDT_ERR_NOTFOUND, fdt_next_node(), fdt_nodename_eq_(), and FDT_RO_PROBE.
Referenced by fdt_add_subnode_namelen(), fdt_path_offset_namelen(), fdt_subnode_offset(), and overlay_symbol_update().
fdt_supernode_atdepth_offset()
int fdt_supernode_atdepth_offset (const void * fdt, int nodeoffset, int supernodedepth, int * nodedepth)
fdt_supernode_atdepth_offset - find a specific ancestor of a node @fdt: pointer to the device tree blob @nodeoffset: offset of the node whose parent to find @supernodedepth: depth of the ancestor to find @nodedepth: pointer to an integer variable (will be overwritten) or NULL
fdt_supernode_atdepth_offset() finds an ancestor of the given node at a specific depth from the root (where the root itself has depth 0, its immediate subnodes depth 1 and so forth). So fdt_supernode_atdepth_offset(fdt, nodeoffset, 0, NULL); will always return 0, the offset of the root node. If the node at nodeoffset has depth D, then: fdt_supernode_atdepth_offset(fdt, nodeoffset, D, NULL); will return nodeoffset itself.
NOTE: This function is expensive, as it must scan the device tree structure from the start to nodeoffset.
returns: structure block offset of the node at node offset's ancestor of depth supernodedepth (>=0), on success -FDT_ERR_BADOFFSET, nodeoffset does not refer to a BEGIN_NODE tag -FDT_ERR_NOTFOUND, supernodedepth was greater than the depth of nodeoffset -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_BADSTRUCTURE, standard meanings
{
    int offset, depth;
    int supernodeoffset = -FDT_ERR_INTERNAL;
    FDT_RO_PROBE(fdt);
    if (supernodedepth < 0)
        return -FDT_ERR_NOTFOUND;
    for (offset = 0, depth = 0;
         (offset >= 0) && (offset <= nodeoffset);
         offset = fdt_next_node(fdt, offset, &depth)) {
        if (depth == supernodedepth)
            supernodeoffset = offset;
        if (offset == nodeoffset) {
            if (nodedepth)
                *nodedepth = depth;
            if (supernodedepth > depth)
                return -FDT_ERR_NOTFOUND;
            else
                return supernodeoffset;
        }
    }
    if (!can_assume(VALID_INPUT)) {
        if ((offset == -FDT_ERR_NOTFOUND) || (offset >= 0))
            return -FDT_ERR_BADOFFSET;
        else if (offset == -FDT_ERR_BADOFFSET)
            return -FDT_ERR_BADSTRUCTURE;
    }
    return offset; /* error from fdt_next_node() */
}
References can_assume, FDT_ERR_BADOFFSET, FDT_ERR_BADSTRUCTURE, FDT_ERR_INTERNAL, FDT_ERR_NOTFOUND, fdt_next_node(), and FDT_RO_PROBE.
Referenced by fdt_node_depth(), and fdt_parent_offset().
nextprop_()
static int nextprop_ (const void * fdt, int offset) static
{
    uint32_t tag;
    int nextoffset;
    do {
        tag = fdt_next_tag(fdt, offset, &nextoffset);
        switch (tag) {
        case FDT_END:
            if (nextoffset >= 0)
                return -FDT_ERR_BADSTRUCTURE;
            else
                return nextoffset;
        case FDT_PROP:
            return offset;
        }
        offset = nextoffset;
    } while (tag == FDT_NOP);
    return -FDT_ERR_NOTFOUND;
}
References FDT_END, FDT_ERR_BADSTRUCTURE, FDT_ERR_NOTFOUND, fdt_next_tag(), FDT_NOP, and FDT_PROP.
Referenced by fdt_first_property_offset(), and fdt_next_property_offset().