ko6: src/soft/external/libfdt/fdt.c File Reference
fdt.c File Reference
#include "libfdt_env.h"
#include <external/libfdt/fdt.h>
#include <external/libfdt/libfdt.h>
#include "libfdt_internal.h"
Functions
int32_t fdt_ro_probe_ (const void *fdt)
static int check_off_ (uint32_t hdrsize, uint32_t totalsize, uint32_t off)
static int check_block_ (uint32_t hdrsize, uint32_t totalsize, uint32_t base, uint32_t size)
size_t fdt_header_size_ (uint32_t version)
size_t fdt_header_size (const void *fdt)
int fdt_check_header (const void *fdt)
const void * fdt_offset_ptr (const void *fdt, int offset, unsigned int len)
uint32_t fdt_next_tag (const void *fdt, int startoffset, int *nextoffset)
int fdt_check_node_offset_ (const void *fdt, int offset)
int fdt_check_prop_offset_ (const void *fdt, int offset)
int fdt_next_node (const void *fdt, int offset, int *depth)
int fdt_first_subnode (const void *fdt, int offset)
int fdt_next_subnode (const void *fdt, int offset)
const char * fdt_find_string_ (const char *strtab, int tabsize, const char *s)
int fdt_move (const void *fdt, void *buf, int bufsize)
Function Documentation
check_block_()
static int check_block_ (uint32_t hdrsize, uint32_t totalsize, uint32_t base, uint32_t size) static
{
    if (!check_off_(hdrsize, totalsize, base))
        return 0; /* block start out of bounds */
    if ((base + size) < base)
        return 0; /* overflow */
    if (!check_off_(hdrsize, totalsize, base + size))
        return 0; /* block end out of bounds */
    return 1;
}
References check_off_().
Referenced by fdt_check_header().
check_off_()
static int check_off_ (uint32_t hdrsize, uint32_t totalsize, uint32_t off) static
{
    return (off >= hdrsize) && (off <= totalsize);
}
Referenced by check_block_(), and fdt_check_header().
fdt_check_header()
int fdt_check_header (const void * fdt)
fdt_check_header - sanity check a device tree header @fdt: pointer to data which might be a flattened device tree
fdt_check_header() checks that the given buffer contains what appears to be a flattened device tree, and that the header contains valid information (to the extent that can be determined from the header alone).
returns: 0, if the buffer appears to contain a valid device tree -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, -FDT_ERR_TRUNCATED, standard meanings, as above
{
    size_t hdrsize;
    /* The device tree must be at an 8-byte aligned address */
    if ((uintptr_t)fdt & 7)
        return -FDT_ERR_ALIGNMENT;
    if (fdt_magic(fdt) != FDT_MAGIC)
        return -FDT_ERR_BADMAGIC;
    if (!can_assume(LATEST)) {
        if ((fdt_version(fdt) < FDT_FIRST_SUPPORTED_VERSION)
            || (fdt_last_comp_version(fdt) >
            FDT_LAST_SUPPORTED_VERSION))
            return -FDT_ERR_BADVERSION;
        if (fdt_version(fdt) < fdt_last_comp_version(fdt))
            return -FDT_ERR_BADVERSION;
    }
    hdrsize = fdt_header_size(fdt);
    if (!can_assume(VALID_DTB)) {
        if ((fdt_totalsize(fdt) < hdrsize)
            || (fdt_totalsize(fdt) > INT_MAX))
            return -FDT_ERR_TRUNCATED;
        /* Bounds check memrsv block */
        if (!check_off_(hdrsize, fdt_totalsize(fdt),
                fdt_off_mem_rsvmap(fdt)))
            return -FDT_ERR_TRUNCATED;
        /* Bounds check structure block */
        if (!can_assume(LATEST) && fdt_version(fdt) < 17) {
            if (!check_off_(hdrsize, fdt_totalsize(fdt),
                    fdt_off_dt_struct(fdt)))
                return -FDT_ERR_TRUNCATED;
        } else {
            if (!check_block_(hdrsize, fdt_totalsize(fdt),
                      fdt_off_dt_struct(fdt),
                      fdt_size_dt_struct(fdt)))
                return -FDT_ERR_TRUNCATED;
        }
        /* Bounds check strings block */
        if (!check_block_(hdrsize, fdt_totalsize(fdt),
                  fdt_off_dt_strings(fdt),
                  fdt_size_dt_strings(fdt)))
            return -FDT_ERR_TRUNCATED;
    }
    return 0;
}
References can_assume, check_block_(), check_off_(), FDT_ERR_ALIGNMENT, FDT_ERR_BADMAGIC, FDT_ERR_BADVERSION, FDT_ERR_TRUNCATED, FDT_FIRST_SUPPORTED_VERSION, fdt_header_size(), fdt_last_comp_version, FDT_LAST_SUPPORTED_VERSION, FDT_MAGIC, fdt_magic, fdt_off_dt_strings, fdt_off_dt_struct, fdt_off_mem_rsvmap, fdt_size_dt_strings, fdt_size_dt_struct, fdt_totalsize, fdt_version, and INT_MAX.
Referenced by fdt_check_full().
fdt_check_node_offset_()
int fdt_check_node_offset_ (const void * fdt, int offset)
{
    if (!can_assume(VALID_INPUT)
        && ((offset < 0) || (offset % FDT_TAGSIZE)))
        return -FDT_ERR_BADOFFSET;
    if (fdt_next_tag(fdt, offset, &offset) != FDT_BEGIN_NODE)
        return -FDT_ERR_BADOFFSET;
    return offset;
}
References can_assume, FDT_BEGIN_NODE, FDT_ERR_BADOFFSET, fdt_next_tag(), and FDT_TAGSIZE.
Referenced by fdt_add_property_(), fdt_first_property_offset(), fdt_get_name(), and fdt_next_node().
fdt_check_prop_offset_()
int fdt_check_prop_offset_ (const void * fdt, int offset)
{
    if (!can_assume(VALID_INPUT)
        && ((offset < 0) || (offset % FDT_TAGSIZE)))
        return -FDT_ERR_BADOFFSET;
    if (fdt_next_tag(fdt, offset, &offset) != FDT_PROP)
        return -FDT_ERR_BADOFFSET;
    return offset;
}
References can_assume, FDT_ERR_BADOFFSET, fdt_next_tag(), FDT_PROP, and FDT_TAGSIZE.
Referenced by fdt_get_property_by_offset_(), and fdt_next_property_offset().
fdt_find_string_()
const char * fdt_find_string_ (const char * strtab, int tabsize, const char * s)
{
    int len = strlen(s) + 1;
    const char *last = strtab + tabsize - len;
    const char *p;
    for (p = strtab; p <= last; p++)
        if (memcmp(p, s, len) == 0)
            return p;
    return NULL;
}
References fdt_property::len, memcmp(), NULL, and strlen().
Referenced by fdt_find_add_string_().
fdt_first_subnode()
int fdt_first_subnode (const void * fdt, int offset)
fdt_first_subnode() - get offset of first direct subnode @fdt: FDT blob @offset: Offset of node to check
Return: offset of first subnode, or -FDT_ERR_NOTFOUND if there is none
{
    int depth = 0;
    offset = fdt_next_node(fdt, offset, &depth);
    if (offset < 0 || depth != 1)
        return -FDT_ERR_NOTFOUND;
    return offset;
}
References FDT_ERR_NOTFOUND, and fdt_next_node().
fdt_header_size()
size_t fdt_header_size (const void * fdt)
fdt_header_size - return the size of the tree's header @fdt: pointer to a flattened device tree
Return: size of DTB header in bytes
{
    return can_assume(LATEST) ? FDT_V17_SIZE :
        fdt_header_size_(fdt_version(fdt));
}
References can_assume, fdt_header_size_(), FDT_V17_SIZE, and fdt_version.
Referenced by fdt_check_full(), and fdt_check_header().
fdt_header_size_()
size_t fdt_header_size_ (uint32_t version)
fdt_header_size_ - internal function to get header size from a version number
Version
: devicetree version number
Return: size of DTB header in bytes
{
    if (version <= 1)
        return FDT_V1_SIZE;
    else if (version <= 2)
        return FDT_V2_SIZE;
    else if (version <= 3)
        return FDT_V3_SIZE;
    else if (version <= 16)
        return FDT_V16_SIZE;
    else
        return FDT_V17_SIZE;
}
References FDT_V16_SIZE, FDT_V17_SIZE, FDT_V1_SIZE, FDT_V2_SIZE, and FDT_V3_SIZE.
Referenced by fdt_header_size().
fdt_move()
int fdt_move (const void * fdt, void * buf, int bufsize)
fdt_move - move a device tree around in memory @fdt: pointer to the device tree to move @buf: pointer to memory where the device is to be moved @bufsize: size of the memory space at buf
fdt_move() relocates, if possible, the device tree blob located at fdt to the buffer at buf of size bufsize. The buffer may overlap with the existing device tree blob at fdt. Therefore, fdt_move(fdt, fdt, fdt_totalsize(fdt)) should always succeed.
returns: 0, on success -FDT_ERR_NOSPACE, bufsize is insufficient to contain the device tree -FDT_ERR_BADMAGIC, -FDT_ERR_BADVERSION, -FDT_ERR_BADSTATE, standard meanings
{
    if (!can_assume(VALID_INPUT) && bufsize < 0)
        return -FDT_ERR_NOSPACE;
    FDT_RO_PROBE(fdt);
    if (fdt_totalsize(fdt) > (unsigned int)bufsize)
        return -FDT_ERR_NOSPACE;
    memmove(buf, fdt, fdt_totalsize(fdt));
    return 0;
}
References can_assume, FDT_ERR_NOSPACE, FDT_RO_PROBE, fdt_totalsize, and memmove().
Referenced by fdt_open_into().
fdt_next_node()
int fdt_next_node (const void * fdt, int offset, int * depth)
{
    int nextoffset = 0;
    uint32_t tag;
    if (offset >= 0)
        if ((nextoffset = fdt_check_node_offset_(fdt, offset)) < 0)
            return nextoffset;
    do {
        offset = nextoffset;
        tag = fdt_next_tag(fdt, offset, &nextoffset);
        switch (tag) {
        case FDT_PROP:
        case FDT_NOP:
            break;
        case FDT_BEGIN_NODE:
            if (depth)
                (*depth)++;
            break;
        case FDT_END_NODE:
            if (depth && ((--(*depth)) < 0))
                return nextoffset;
            break;
        case FDT_END:
            if ((nextoffset >= 0)
                || ((nextoffset == -FDT_ERR_TRUNCATED) && !depth))
                return -FDT_ERR_NOTFOUND;
            else
                return nextoffset;
        }
    } while (tag != FDT_BEGIN_NODE);
    return offset;
}
References FDT_BEGIN_NODE, fdt_check_node_offset_(), FDT_END, FDT_END_NODE, FDT_ERR_NOTFOUND, FDT_ERR_TRUNCATED, fdt_next_tag(), FDT_NOP, FDT_PROP, and fdt_property::tag.
Referenced by fdt_find_max_phandle(), fdt_first_subnode(), fdt_get_path(), fdt_next_subnode(), fdt_node_end_offset_(), fdt_node_offset_by_compatible(), fdt_node_offset_by_phandle(), fdt_node_offset_by_prop_value(), fdt_subnode_offset_namelen(), and fdt_supernode_atdepth_offset().
fdt_next_subnode()
int fdt_next_subnode (const void * fdt, int offset)
fdt_next_subnode() - get offset of next direct subnode @fdt: FDT blob @offset: Offset of previous subnode
After first calling fdt_first_subnode(), call this function repeatedly to get direct subnodes of a parent node.
Return: offset of next subnode, or -FDT_ERR_NOTFOUND if there are no more subnodes
{
    int depth = 1;
    /*
     * With respect to the parent, the depth of the next subnode will be
     * the same as the last.
     */
    do {
        offset = fdt_next_node(fdt, offset, &depth);
        if (offset < 0 || depth < 1)
            return -FDT_ERR_NOTFOUND;
    } while (depth > 1);
    return offset;
}
References FDT_ERR_NOTFOUND, and fdt_next_node().
fdt_next_tag()
uint32_t fdt_next_tag (const void * fdt, int startoffset, int * nextoffset)
{
    const fdt32_t *tagp, *lenp;
    uint32_t tag, len, sum;
    int offset = startoffset;
    const char *p;
    *nextoffset = -FDT_ERR_TRUNCATED;
    tagp = fdt_offset_ptr(fdt, offset, FDT_TAGSIZE);
    if (!can_assume(VALID_DTB) && !tagp)
        return FDT_END; /* premature end */
    tag = fdt32_to_cpu(*tagp);
    offset += FDT_TAGSIZE;
    *nextoffset = -FDT_ERR_BADSTRUCTURE;
    switch (tag) {
    case FDT_BEGIN_NODE:
        /* skip name */
        do {
            p = fdt_offset_ptr(fdt, offset++, 1);
        } while (p && (*p != '\0'));
        if (!can_assume(VALID_DTB) && !p)
            return FDT_END; /* premature end */
        break;
    case FDT_PROP:
        lenp = fdt_offset_ptr(fdt, offset, sizeof(*lenp));
        if (!can_assume(VALID_DTB) && !lenp)
            return FDT_END; /* premature end */
        len = fdt32_to_cpu(*lenp);
        sum = len + offset;
        if (!can_assume(VALID_DTB) &&
            (INT_MAX <= sum || sum < (uint32_t) offset))
            return FDT_END; /* premature end */
        /* skip-name offset, length and value */
        offset += sizeof(struct fdt_property) - FDT_TAGSIZE + len;
        if (!can_assume(LATEST) &&
            fdt_version(fdt) < 0x10 && len >= 8 &&
            ((offset - len) % 8) != 0)
            offset += 4;
        break;
    case FDT_END:
    case FDT_END_NODE:
    case FDT_NOP:
        break;
    default:
        return FDT_END;
    }
    if (!fdt_offset_ptr(fdt, startoffset, offset - startoffset))
        return FDT_END; /* premature end */
    *nextoffset = FDT_TAGALIGN(offset);
    return tag;
}
References can_assume, fdt32_to_cpu(), FDT_BEGIN_NODE, FDT_END, FDT_END_NODE, FDT_ERR_BADSTRUCTURE, FDT_ERR_TRUNCATED, FDT_NOP, fdt_offset_ptr(), FDT_PROP, FDT_TAGALIGN, FDT_TAGSIZE, fdt_version, INT_MAX, fdt_property::len, and fdt_property::tag.
Referenced by fdt_add_subnode_namelen(), fdt_check_full(), fdt_check_node_offset_(), fdt_check_prop_offset_(), fdt_finish(), fdt_next_node(), fdt_open_into(), and nextprop_().
fdt_offset_ptr()
const void * fdt_offset_ptr (const void * fdt, int offset, unsigned int len)
{
    unsigned int uoffset = offset;
    unsigned int absoffset = offset + fdt_off_dt_struct(fdt);
    if (offset < 0)
        return NULL;
    if (!can_assume(VALID_INPUT))
        if ((absoffset < uoffset)
            || ((absoffset + len) < absoffset)
            || (absoffset + len) > fdt_totalsize(fdt))
            return NULL;
    if (can_assume(LATEST) || fdt_version(fdt) >= 0x11)
        if (((uoffset + len) < uoffset)
            || ((offset + len) > fdt_size_dt_struct(fdt)))
            return NULL;
    return fdt_offset_ptr_(fdt, offset);
}
References can_assume, fdt_off_dt_struct, fdt_offset_ptr_(), fdt_size_dt_struct, fdt_totalsize, fdt_version, and NULL.
Referenced by fdt_next_tag(), and fdt_offset_ptr_w().
fdt_ro_probe_()
int32_t fdt_ro_probe_ (const void * fdt)
{
    uint32_t totalsize = fdt_totalsize(fdt);
    if (can_assume(VALID_DTB))
        return totalsize;
    /* The device tree must be at an 8-byte aligned address */
    if ((uintptr_t)fdt & 7)
        return -FDT_ERR_ALIGNMENT;
    if (fdt_magic(fdt) == FDT_MAGIC) {
        /* Complete tree */
        if (!can_assume(LATEST)) {
            if (fdt_version(fdt) < FDT_FIRST_SUPPORTED_VERSION)
                return -FDT_ERR_BADVERSION;
            if (fdt_last_comp_version(fdt) >
                    FDT_LAST_SUPPORTED_VERSION)
                return -FDT_ERR_BADVERSION;
        }
    } else if (fdt_magic(fdt) == FDT_SW_MAGIC) {
        /* Unfinished sequential-write blob */
        if (!can_assume(VALID_INPUT) && fdt_size_dt_struct(fdt) == 0)
            return -FDT_ERR_BADSTATE;
    } else {
        return -FDT_ERR_BADMAGIC;
    }
    if (totalsize < INT32_MAX)
        return totalsize;
    else
        return -FDT_ERR_TRUNCATED;
}
References can_assume, FDT_ERR_ALIGNMENT, FDT_ERR_BADMAGIC, FDT_ERR_BADSTATE, FDT_ERR_BADVERSION, FDT_ERR_TRUNCATED, FDT_FIRST_SUPPORTED_VERSION, fdt_last_comp_version, FDT_LAST_SUPPORTED_VERSION, FDT_MAGIC, fdt_magic, fdt_size_dt_struct, FDT_SW_MAGIC, fdt_totalsize, fdt_version, and INT32_MAX.
Referenced by fdt_get_name(), and fdt_get_string().