ko6: src/soft/uapp/hello/main.c File Reference
main.c File Reference
#include <libc.h>
Functions
int main (void)
Function Documentation
main()
int main (void)
{
    char name[64];
    fprintf( 1, "Hello world!\n");
    fprintf( 1, "What's your name? ");
    fgets( name, sizeof(name), 1);
    name[ strlen(name)-1 ]=0;
    fprintf( 1, "Hello %s!\n", name);
    return 0;
}
References fgets(), fprintf(), and strlen().