ko6: src/soft/hal/devices/irq/plic.c File Reference
plic.c File Reference
#include <hal/devices/irq/plic.h>
Functions
static void plic_init (struct irq_s *irq, unsigned address)
Initialize PLIC device.
static unsigned plic_get_highest (struct irq_s *irq)
Get the highest priority IRQ triggered (mclaim register of the PLIC)*.
static void plic_set_priority (struct irq_s *irq, unsigned irq, unsigned pri)
Set IRQ priority.
static void plic_acknowledge (struct irq_s *irq, unsigned irq)
Acknowledge the IRQ (write the IRQ no in the MCLAIM register)
static void plic_unmask (struct irq_s *irq, unsigned irq)
Unmask the IRQ (enable it), (write 1 in the corresponding MENABLE bit)
static void plic_mask (struct irq_s *irq, unsigned irq)
Mask the IRQ (disable it), (write 0 in the corresponding MENABLE bit)
Variables
struct irq_ops_s PlicOps
Function Documentation
plic_acknowledge()
static void plic_acknowledge (struct irq_s * irq, unsigned irq) static
Acknowledge the IRQ (write the IRQ no in the MCLAIM register)
Parameters
irq irq device
irq target irq
Returns
nothing
{
    *(unsigned*) PLIC_MCLAIM(irq->address, cpuid()) = irq;
}
References irq_s::address, cpuid(), and PLIC_MCLAIM.
plic_get_highest()
static unsigned plic_get_highest (struct irq_s * irq) static
Get the highest priority IRQ triggered (mclaim register of the PLIC)*.
Parameters
irq irq device
{
    return *(unsigned*) PLIC_MCLAIM(irq->address, cpuid());
}
References irq_s::address, cpuid(), and PLIC_MCLAIM.
plic_init()
static void plic_init (struct irq_s * irq, unsigned address) static
Initialize PLIC device.
Parameters
irq irq device to initialize
address address of the physical device
Returns
nothing
{
    irq->ops        = &PlicOps;
    irq->address    = address;
}
References irq_s::address, irq_s::ops, and PlicOps.
plic_mask()
static void plic_mask (struct irq_s * irq, unsigned irq) static
Mask the IRQ (disable it), (write 0 in the corresponding MENABLE bit)
Parameters
irq irq device
irq target irq
Returns
nothing
{
    unsigned j = irq % 32;
    *(unsigned*) PLIC_MENABLE(irq->address, cpuid(), irq) &= ~(1 << j);
}
References irq_s::address, cpuid(), and PLIC_MENABLE.
plic_set_priority()
static void plic_set_priority (struct irq_s * irq, unsigned irq, unsigned pri) static
Set IRQ priority.
Parameters
irq irq device
irq target irq
pri the new irq priority
Returns
nothing
{
    ((unsigned*)irq->address + PLIC_PRI_OFFSET)[irq] = pri;
}
References irq_s::address, and PLIC_PRI_OFFSET.
plic_unmask()
static void plic_unmask (struct irq_s * irq, unsigned irq) static
Unmask the IRQ (enable it), (write 1 in the corresponding MENABLE bit)
Parameters
irq irq device
irq target irq
Returns
nothing
{
    unsigned j = irq % 32;
    *(unsigned*) PLIC_MENABLE(irq->address, cpuid(), irq) |= (1 << j);
}
References irq_s::address, cpuid(), and PLIC_MENABLE.
Variable Documentation
PlicOps
struct irq_ops_s PlicOps
Initial value:
= {
    .irq_acknowledge = plic_acknowledge,
    .irq_get_highest = plic_get_highest,
    .irq_init = plic_init,
    .irq_mask = plic_mask,
    .irq_set_priority = plic_set_priority,
    .irq_unmask = plic_unmask
}