ko6: src/soft/kernel/kdev.h File Reference
kdev.h File Reference
#include <common/list.h>
#include <kernel/klibc.h>
Classes
struct dev_s
Device Driver informations FIXME struct dev_s should be hidden (defined in kdev.c) but we miss data field accessor.
Enumerations
enum dev_tag_e { CHAR_DEV , ICU_DEV , DMA_DEV , TIMER_DEV }
Devices Types.
Functions
unsigned dev_next_no (enum dev_tag_e tag)
Find the last element added with corresponding tag To do so, we loop through the device list in a reverse order Once we found the last device, we add one to his number.
struct dev_s * dev_alloc (enum dev_tag_e tag, unsigned dsize)
Allocate enough size in kernel heap to store device meta data (tag, no, list) and device data (struct tty_s, struct icu_s, ...) and add it into the global device list.
struct dev_s * dev_get (enum dev_tag_e tag, unsigned no)
Get a device based on its type and on its minor number.
void dev_free (struct dev_s *dev, unsigned dsize)
Release a created device (kfree + list_unlink)
Enumeration Type Documentation
dev_tag_e
enum dev_tag_e
Devices Types.
Enumerator
CHAR_DEV
ICU_DEV
DMA_DEV
TIMER_DEV
               {
    CHAR_DEV,
    ICU_DEV,
    DMA_DEV,
    TIMER_DEV
};
Function Documentation
dev_alloc()
struct dev_s * dev_alloc (enum dev_tag_e tag, unsigned dsize)
Allocate enough size in kernel heap to store device meta data (tag, no, list) and device data (struct tty_s, struct icu_s, ...) and add it into the global device list.
Parameters
tag type of the device (tty, icu, ...)
dsize size of the device-specific structure (ex: sizeof(struct_s))
Returns
the allocated device
{
    struct dev_s *dev = kmalloc(sizeof(struct dev_s) + dsize);  // Allocate enough space for
                                                                // device metadata (tag, no, list)
                                                                // and device-specific data
                                                                // (ops,...)
    dev->tag = tag;
    dev->no = dev_next_no(tag);
    list_addlast(&DevList, &dev->list);
    return dev;
}
References dev_next_no(), DevList, kmalloc(), dev_s::list, list_addlast(), dev_s::no, and dev_s::tag.
dev_free()
void dev_free (struct dev_s * dev, unsigned dsize)
Release a created device (kfree + list_unlink)
Parameters
dev the device to release
dsize size of device-specific structure
TODO: should we decrement every other device no in the last, ex: should tty 2 become tty 1 if tty 0 is removed ? i don't think so but it could be interesting to think about it
{
    list_unlink(&dev->list);
    kfree(dev, sizeof(struct dev_s) + dsize);
}
References kfree(), dev_s::list, and list_unlink().
dev_get()
struct dev_s * dev_get (enum dev_tag_e tag, unsigned no)
Get a device based on its type and on its minor number.
Parameters
tag type of the device
no minor number of the device
Returns
the corresponding device if found, NULL if not
Loop through the list until we find the corresponding entry We could gain some performance by having device-specific linked list but I can't think of a way to do it easily & in a simple manner
{
    list_foreach(&DevList, item) {
        struct dev_s *dev = list_item(item, struct dev_s, list);
        if (dev->tag == tag && dev->no == no)
            return dev;
    }
    return NULL;
}
References DevList, dev_s::list, list_foreach, list_item, dev_s::no, NULL, and dev_s::tag.
dev_next_no()
unsigned dev_next_no (enum dev_tag_e tag)
Find the last element added with corresponding tag To do so, we loop through the device list in a reverse order Once we found the last device, we add one to his number.
Parameters
tag type of the device (tty, icu, ...)
Returns
the next no (last device of this type no + 1)
{
    list_foreach_rev(&DevList, item) {
        struct dev_s *dev = list_item(item, struct dev_s, list);
        if (dev->tag == tag)
            return dev->no + 1;
    }
    return 0;
}
References DevList, dev_s::list, list_foreach_rev, list_item, dev_s::no, and dev_s::tag.
Referenced by dev_alloc().