ko6: src/soft/fs/kfs/kfs.c File Reference
kfs.c File Reference
#include <kfs.h>
Classes
struct kfs_dentry_s
struct kfs_inode_s
struct kfs_mbr_s
struct kfs_sblock_s
Macros
#define NULL (void *)0
#define KFS_MAX_NAME 28 /* dentry name length */
#define KFS_MAX_DENTRY ((KFS_NPG_DENTRY<<12)/sizeof(kfs_dentry_t)) /* number of dentries */
#define KFS_MAX_INODE ((KFS_NPG_INODE <<12)/sizeof(kfs_inode_t)) /* number of inodes */
#define KFS_MAX_FMAP ((KFS_NPG_FMAP <<12)/sizeof(kfs_fmap_t)) /* number of file maps */
#define NPGU (KFS_NPG_BOOT+KFS_NPG_META) /* number of pages used by BOOT and META */
Typedefs
typedef unsigned int u32_t
typedef unsigned short u16_t
typedef unsigned char u8_t
typedef signed int i32_t
typedef signed short i16_t
typedef signed char i8_t
typedef struct kfs_dentry_s kfs_dentry_t
typedef struct kfs_inode_s kfs_inode_t
typedef u16_t kfs_fmap_t[16]
fmap as inode extension, maps until 16 pages or 16 other fmaps
typedef struct kfs_mbr_s kfs_mbr_t
typedef struct kfs_sblock_s kfs_sblock_t
typedef u32_t kfs_page_t[1024]
atomic data segment exchanged with the disk
Functions
int kfs_root (int dentry)
read access functions to dentries
int kfs_next (int dentry)
int kfs_leaf (int dentry)
int kfs_inode (int dentry)
char * kfs_name (int dentry)
int kfs_isdir (int dentry)
boolean functions for dentries or inode
int kfs_count (int inode)
read access functions to inodes
int kfs_type (int inode)
int kfs_mode (int inode)
int kfs_size (int inode)
int kfs_owner (int inode)
int kfs_mtime (int inode)
int kfs_chmode (int inode, int mode)
write access functions to inode's properties
int kfs_chowner (int inode, int owner)
int kfs_chmtime (int inode, int mtime)
static char * kfs_getname (char *pathname)
get name from pathname up to character '/' pathname argument is not destroyed. Function NON-reentrant
static void kfs_strcpy (char *dest, char *src)
copy a string of characters
static int kfs_strcmp (const char *s1, const char *s2)
compare two strings of characters
static u32_t kfs_alloc_bitmap (u8_t bitmap[], u32_t *start, u32_t max)
bitmap allocator
static void kfs_free_bitmap (u8_t bitmap[], u32_t *start, u32_t bit)
releases one bit of a bitmap
static u32_t kfs_alloc_dentry (char *name)
allocates a new dentry, dentry 0 is for '/' thus it is never free
static void kfs_free_dentry (u16_t dentry)
frees a dentry (it is not necessary to erase its content, it will be done in allocation)
static u16_t kfs_alloc_inode (u8_t type)
allocates a new inode, inode 0 is for '/' thus it is never free
static void kfs_free_inode (int inode)
frees an inode (it is not necessary to erase it, it will be done in allocation)
static int kfs_alloc_fmap (void)
allocates a new map, map 0 is never free
static void kfs_free_fmap (u16_t fmap)
frees a map
static u16_t kfs_alloc_page (void)
allocates a new page of the disk
static void kfs_free_page (u16_t page)
frees a page of the disk
static int kfs_fmap (int inode)
int kfs_page (int inode, int pg_offset)
static u16_t * kfs_ppage (u16_t inode, u16_t pg_offset)
static int kfs_read_page (int *buf, u16_t page)
Reads from the disk to the memory buffer. There are two cases : 1) if kfs runs on Linux 2) if kfs runs on ko6 1) Linux: the kfs disk has been loaded in an array, so that's where we have to read it 2) ko6: the kfs disk is behind the disk device, so we need to ask the disk driver.
static int kfs_write_page (void *buf, int page)
writes to the disk from the memory buffer
static int kfs_tree_cb_r (int root, int depth, void(*callback)(int dentry, int depth, int pos))
Recursively executes the callback() function for all entries in a directory. This is a deep-first walk. The callback() function is not executed on the root. _cb_r means "call back recursive" This function must not be used directly, it is used by kfs_tree_cb()
int kfs_open (char *pathname)
opens a file or directory, if file or directory not found, all the pathname is created
int kfs_openat (int root, char *name)
looks for name in the directory root, if the name is not found, it is created
int kfs_readdir (int root, int leaf, void *buf)
Reads a directory, it reads one entry from the directory dentry to memory buffer. After reading, buffer will contain the name of the directory or item.
int kfs_read (int dentry, int pg_offset, int *buf)
Reads a file, it reads one page from the file dentry to memory buffer. After reading, buffer will contain the entire page of which the offset belongs.
int kfs_set_size (int dentry, int newsize)
Sets the size field of the inode associated with the dentry to newsize.
int kfs_write (int dentry, int pg_offset, void *buf)
Writes one page from memory buffer to file dentry. The buffer is written on the disk in file page of which the offset belongs.
int kfs_link (char *src_name, char *dst_name)
creates a new link (also called hard link) on an existing file.
int kfs_unlink (char *name)
int kfs_tree_cb (int root, void(*callback)(int dentry, int depth, int postion))
Variables
static kfs_sblock_t KfsSblock
static kfs_dentry_t KfsDentry [KFS_MAX_DENTRY]
up to MAX_DENTRY files
static kfs_inode_t KfsInode [KFS_MAX_INODE]
static kfs_fmap_t KfsFmap [KFS_MAX_FMAP]
up to MAX_FMAP inode extensions
static u16_t KfsOffset [KFS_MAX_INODE]
last offset used for inode by read write
Macro Definition Documentation
KFS_MAX_DENTRY
#define KFS_MAX_DENTRY ((KFS_NPG_DENTRY<<12)/sizeof(kfs_dentry_t)) /* number of dentries */
KFS_MAX_FMAP
#define KFS_MAX_FMAP ((KFS_NPG_FMAP <<12)/sizeof(kfs_fmap_t)) /* number of file maps */
KFS_MAX_INODE
#define KFS_MAX_INODE ((KFS_NPG_INODE <<12)/sizeof(kfs_inode_t)) /* number of inodes */
KFS_MAX_NAME
#define KFS_MAX_NAME 28 /* dentry name length */
NPGU
#define NPGU (KFS_NPG_BOOT+KFS_NPG_META) /* number of pages used by BOOT and META */
NULL
#define NULL (void *)0
Typedef Documentation
i16_t
typedef signed short i16_t
i32_t
typedef signed int i32_t
i8_t
typedef signed char i8_t
kfs_dentry_t
typedef struct kfs_dentry_s kfs_dentry_t
kfs_fmap_t
typedef u16_t kfs_fmap_t[16]
fmap as inode extension, maps until 16 pages or 16 other fmaps
kfs_inode_t
typedef struct kfs_inode_s kfs_inode_t
kfs_mbr_t
typedef struct kfs_mbr_s kfs_mbr_t
kfs_page_t
typedef u32_t kfs_page_t[1024]
atomic data segment exchanged with the disk
kfs_sblock_t
typedef struct kfs_sblock_s kfs_sblock_t
u16_t
typedef unsigned short u16_t
u32_t
typedef unsigned int u32_t
u8_t
typedef unsigned char u8_t
Function Documentation
kfs_alloc_bitmap()
static u32_t kfs_alloc_bitmap (u8_t bitmap[], u32_t * start, u32_t max) static
bitmap allocator
Parameters
bitmap is a bit array, but it is accessed by byte
start is a pointer to position of last allocated or released bit (from 0 to max-1)
max is the number of bits in the bitmap
Returns
the position of the bit found or 0 if not found, there are 2 side effects, the bit bitmap[] at the returned position is cleared and start is updated for the next search
{
    for (;*start != max ; *start += 1)                      // search from the last allocated
        if ((bitmap[*start/8] & (1 << (*start%8))) == 0) {  // if this bit is 0 (then usable)
            bitmap[*start/8] |= (1 << (*start%8));          // set it
            return *start;                                  // and return its postion
        }
    return 0;                                               // whenever no bit found
}
Referenced by kfs_alloc_dentry(), kfs_alloc_fmap(), kfs_alloc_inode(), and kfs_alloc_page().
kfs_alloc_dentry()
static u32_t kfs_alloc_dentry (char * name) static
allocates a new dentry, dentry 0 is for '/' thus it is never free
Parameters
name of the new dentry
Returns
On success, the new dentry, on failure, 0 (because dentry 0 is always allocated)
{
    u32_t new= kfs_alloc_bitmap (KfsSblock.bmp_dentry, &KfsSblock.cur_dentry, KfsSblock.max_dentry);
    if (new == 0) return 0;                                 // no more dentries available
    kfs_strcpy (KfsDentry[new].name, name);                 // copy name
    return new;                                             // all other fields are not initialized
}
References kfs_sblock_s::bmp_dentry, kfs_sblock_s::cur_dentry, kfs_alloc_bitmap(), kfs_strcpy(), KfsDentry, KfsSblock, and kfs_sblock_s::max_dentry.
Referenced by kfs_openat().
kfs_alloc_fmap()
static int kfs_alloc_fmap (void) static
allocates a new map, map 0 is never free
Returns
On success, the new map, on failure, 0 (because fmap 0 is always allocated)
{
    return kfs_alloc_bitmap (KfsSblock.bmp_fmap, &KfsSblock.cur_fmap, KfsSblock.max_fmap);
}
References kfs_sblock_s::bmp_fmap, kfs_sblock_s::cur_fmap, kfs_alloc_bitmap(), KfsSblock, and kfs_sblock_s::max_fmap.
Referenced by kfs_ppage().
kfs_alloc_inode()
static u16_t kfs_alloc_inode (u8_t type) static
allocates a new inode, inode 0 is for '/' thus it is never free
Parameters
type of the new inode
Returns
On success, the new inode, on failure, 0 (because inode 0 is always allocated)
{
    u32_t new = kfs_alloc_bitmap (KfsSblock.bmp_inode, &KfsSblock.cur_inode, KfsSblock.max_inode);
    if (new == 0) return 0;                                 // no more dentries available
    KfsInode[new].type = type;                              // type could be chosen
    KfsInode[new].mode = 077;                               // 077 == RWXRWX
    KfsInode[new].count = 1;                                // new inode means only one reference
    return new;                                             // at last, return the new inode
}
References kfs_sblock_s::bmp_inode, kfs_inode_s::count, kfs_sblock_s::cur_inode, kfs_alloc_bitmap(), KfsInode, KfsSblock, kfs_sblock_s::max_inode, kfs_inode_s::mode, and kfs_inode_s::type.
Referenced by kfs_openat().
kfs_alloc_page()
static u16_t kfs_alloc_page (void) static
allocates a new page of the disk
Returns
On success, the new page, on failure, 0 (because page 0 is always allocated)
{
    return kfs_alloc_bitmap (KfsSblock.bmp_page, &KfsSblock.cur_page, KfsSblock.max_page);
}
References kfs_sblock_s::bmp_page, kfs_sblock_s::cur_page, kfs_alloc_bitmap(), KfsSblock, and kfs_sblock_s::max_page.
Referenced by kfs_write().
kfs_chmode()
int kfs_chmode (int inode, int mode)
write access functions to inode's properties
Parameters
index of an inode
mode,owner & mtime are the new property value
Returns
the new property or -1 if failure
{return KfsInode[inode].mode = mode; }
References KfsInode, and kfs_inode_s::mode.
kfs_chmtime()
int kfs_chmtime (int inode, int mtime)
{return KfsInode[inode].mtime= mtime;}
References KfsInode, and kfs_inode_s::mtime.
kfs_chowner()
int kfs_chowner (int inode, int owner)
{return KfsInode[inode].owner= owner;}
References KfsInode, and kfs_inode_s::owner.
kfs_count()
int kfs_count (int inode)
read access functions to inodes
Parameters
index of an inode
offset is the page number in the file (start at 0 to filesize / sizeof(page))
Returns
- kfs_count : number of dentry pointing to this inode
kfs_type : type defined in kfs_enum_e
kfs_mode : permission modes rwxrwx for the owner and others (there are no groups)
kfs_size : file size
kfs_owner : file or directory owner
kfs_mtime : modification / creation relative time
kfs_page : index of page of data on the disk
{return KfsInode[inode].count;}
References kfs_inode_s::count, and KfsInode.
Referenced by kfs_print_dentry().
kfs_fmap()
static int kfs_fmap (int inode) static
{return KfsInode[inode].fmap; }
References kfs_inode_s::fmap, and KfsInode.
Referenced by kfs_page().
kfs_free_bitmap()
static void kfs_free_bitmap (u8_t bitmap[], u32_t * start, u32_t bit) static
releases one bit of a bitmap
Parameters
bitmap is a bit array, but it is accessed by byte
start is a pointer to position of last allocated or released bit (from 0 to max-1)
bit is the bit position to realease
Returns
there are 2 side effects, the bit bitmap[] at the start position is set and start is updated for the next search
{
    bitmap [bit/8] &= ~(1<<bit%8);                          // clear bit in bitmap
    if (bit < *start) *start = bit;                         // change position to start next time
}
Referenced by kfs_free_dentry(), kfs_free_fmap(), kfs_free_inode(), and kfs_free_page().
kfs_free_dentry()
static void kfs_free_dentry (u16_t dentry) static
frees a dentry (it is not necessary to erase its content, it will be done in allocation)
Parameters
dentry to free
{
    u16_t root = KfsDentry[dentry].root;                    // get the directory where dentry is
    u16_t curr = KfsDentry[root].leaf;                      // get the 1st entry of this directory
    u16_t prev = 0;                                         // initiate previous
    while (curr != dentry) {                                // while the current entry isn't dentry
        prev = curr;                                        // previous dentry becomes current
        curr = KfsDentry[curr].next;                        // get the next current
    }
    if (prev == 0)                                          // if previous==0, dentry was the 1st
        KfsDentry[root].leaf = KfsDentry[dentry].next;      // new 1st is the one just after dentry
    else                                                    // else
        KfsDentry[prev].next = KfsDentry[dentry].next;      // skip the dentry prev.next=dentry.next
    u32_t * pi = (u32_t *)&(KfsDentry[dentry]);             // erase data inside dentry
    for (int i = 0; i < 8; i++, *pi++=0)
    kfs_free_bitmap (KfsSblock.bmp_dentry, &KfsSblock.cur_dentry, dentry);  // free the bit
}
References kfs_sblock_s::bmp_dentry, kfs_sblock_s::cur_dentry, kfs_free_bitmap(), KfsDentry, KfsSblock, kfs_dentry_s::leaf, kfs_dentry_s::next, and kfs_dentry_s::root.
Referenced by kfs_unlink().
kfs_free_fmap()
static void kfs_free_fmap (u16_t fmap) static
frees a map
Parameters
map to free
{
    u32_t * pi = (u32_t *)(KfsFmap[fmap]);
    for (int i = 0; i < 8; i++, *pi++=0);
    kfs_free_bitmap (KfsSblock.bmp_fmap, &KfsSblock.cur_fmap, fmap);
}
References kfs_sblock_s::bmp_fmap, kfs_sblock_s::cur_fmap, kfs_free_bitmap(), KfsFmap, and KfsSblock.
Referenced by kfs_unlink().
kfs_free_inode()
static void kfs_free_inode (int inode) static
frees an inode (it is not necessary to erase it, it will be done in allocation)
Parameters
inode to free
{
    u32_t * pi = (u32_t *)&(KfsInode[inode]);
    for (int i = 0; i < 8; i++, *pi++=0);
    kfs_free_bitmap (KfsSblock.bmp_inode, &KfsSblock.cur_inode, inode);
}
References kfs_sblock_s::bmp_inode, kfs_sblock_s::cur_inode, kfs_free_bitmap(), KfsInode, and KfsSblock.
Referenced by kfs_link(), and kfs_unlink().
kfs_free_page()
static void kfs_free_page (u16_t page) static
frees a page of the disk
Parameters
page to free
{
    kfs_free_bitmap (KfsSblock.bmp_page, &KfsSblock.cur_page, page);
}
References kfs_sblock_s::bmp_page, kfs_sblock_s::cur_page, kfs_free_bitmap(), and KfsSblock.
Referenced by kfs_unlink(), and kfs_write().
kfs_getname()
static char * kfs_getname (char * pathname) static
get name from pathname up to character '/' pathname argument is not destroyed. Function NON-reentrant
Parameters
pathname has to be an absolute pathname, thus it must start with '/' kfs_getname ignores the last '/' at the end of pathname if pathname is NULL, then kfs_getname gives the next name in the previous pathname
Returns
pointer to the current name or NULL on failure
{
    static char name[32] = "";                              // buffer for the extracted name
    static char *next = name;                               // next name, default empty name
    char * current = name;                                  // pointer used to fill the buffer
    if (pathname) {                                         // only true at first call
        if (*pathname != '/')                               // pathname must start with '/'
            return NULL;                                    // failure
        next = pathname;                                    // the next name is all pathname
    }
    if (*next == 0) return NULL;                            // no more name in pathname
    for (;*next && *next != '/'; *current++=*next++);       // strcpy till '/' excluded
    *current = 0;                                           // end of the name
    if (*next) next++;                                      // if *next == '/' go to next char
    while (*next == '/') next++;                            // several '/' are considered as single
    return name;                                            // at last return extracted name
}
References NULL.
Referenced by kfs_open().
kfs_inode()
int kfs_inode (int dentry)
{return KfsDentry[dentry].inode;}
References kfs_dentry_s::inode, and KfsDentry.
Referenced by kfs_print_dentry(), kfs_print_files(), kfs_read(), kfs_set_size(), kfs_write(), and split().
kfs_isdir()
int kfs_isdir (int dentry)
boolean functions for dentries or inode
Parameters
index of a dentry
Returns
- 0 if false, not 0 if true
{return KfsInode[KfsDentry[dentry].inode].type == KFS_DIR;}
References kfs_dentry_s::inode, KFS_DIR, KfsDentry, KfsInode, and kfs_inode_s::type.
Referenced by kfs_readdir(), kfs_tree_cb(), and kfs_tree_cb_r().
kfs_leaf()
int kfs_leaf (int dentry)
{return KfsDentry[dentry].leaf ;}
References KfsDentry, and kfs_dentry_s::leaf.
Referenced by kfs_print_dentry().
kfs_link()
int kfs_link (char * old_name, char * new_name)
creates a new link (also called hard link) on an existing file.
Parameters
old_name is an existing file name
new_name is the new name of the same file as old_name if new_name already exists it is not created, and it's a failure
Returns
0 if success, -1 if failure
{
    u16_t src_dentry = kfs_open (src_name);
    u16_t dst_dentry = kfs_open (dst_name);
    u16_t src_inode  = KfsDentry[src_dentry].inode;
    u16_t dst_inode  = KfsDentry[dst_dentry].inode;
    KfsDentry[dst_dentry].inode = src_inode;
    KfsInode[src_inode].count++;
    kfs_free_inode (dst_inode);
    return dst_dentry;
}
References kfs_inode_s::count, kfs_dentry_s::inode, kfs_free_inode(), kfs_open(), KfsDentry, and KfsInode.
Referenced by dummy_disk().
kfs_mode()
int kfs_mode (int inode)
{return KfsInode[inode].mode; }
References KfsInode, and kfs_inode_s::mode.
Referenced by kfs_print_dentry().
kfs_mtime()
int kfs_mtime (int inode)
{return KfsInode[inode].mtime;}
References KfsInode, and kfs_inode_s::mtime.
Referenced by kfs_print_dentry().
kfs_name()
char * kfs_name (int dentry)
{return KfsDentry[dentry].name ;}
References KfsDentry, and kfs_dentry_s::name.
Referenced by kfs_absolute_pathname(), and kfs_print_dentry().
kfs_next()
int kfs_next (int dentry)
{return KfsDentry[dentry].next ;}
References KfsDentry, and kfs_dentry_s::next.
Referenced by kfs_print_dentry().
kfs_open()
int kfs_open (char * pathname)
opens a file or directory, if file or directory not found, all the pathname is created
"deep-first walk" of the name tree to find or create the file defined by its absolute name
{
    char * name = kfs_getname (pathname);                   // get first name up to character '/'
    if (name == NULL) return -1;                            // pathname not correct, failure
    u32_t dentry = 0;                                       // search from root fs
    while ((name = kfs_getname (NULL)))                     // get the next name in pathname
        dentry = kfs_openat (dentry, name);                 // look for it in current directory
    KfsOffset[KfsDentry[dentry].inode] = 0;                 // by defaut, set offset to firstpage
    return dentry;                                          // finally, the last dentry found
}
References kfs_dentry_s::inode, kfs_getname(), kfs_openat(), KfsDentry, KfsOffset, and NULL.
Referenced by build(), dummy_disk(), kfs_files(), kfs_link(), kfs_tree(), kfs_unlink(), and main().
kfs_openat()
int kfs_openat (int root, char * name)
looks for name in the directory root, if the name is not found, it is created
find or create the file defined by its relative name into the directory defined by its dentry
{
    u32_t leaf = KfsDentry[root].leaf;                      // get first leaf of current root
    int notfound = 1;                                       // by default, suppose name not found
    KfsInode[KfsDentry[root].inode].type = KFS_DIR;         // root is necessarily a directory
    if (leaf) {                                             // if there are leafs
        u32_t leaf_next = KfsDentry[leaf].next;             // get next leaf
        notfound = kfs_strcmp(KfsDentry[leaf].name, name);  // !=0 if different
        while (notfound && leaf_next) {                     // while not good leaf and there is more
            leaf = leaf_next;                               // change the leaf to the next leaf
            leaf_next = KfsDentry[leaf].next;               // get next leaf
            notfound= kfs_strcmp(KfsDentry[leaf].name,name);// compare current leaf
        }
    }
    if (notfound) {
        leaf = kfs_alloc_dentry (name);                     // create a new dentry for the file
        KfsDentry[leaf].inode = kfs_alloc_inode (KFS_FILE); // create an empty inode (default FILE)
        KfsDentry[leaf].leaf = 0;                           // if new leaf is FILE, thus no leaf
        KfsDentry[leaf].root = root;                        // set the root of the new leaf
        KfsDentry[leaf].next = KfsDentry[root].leaf;        // put new leaf in same level nodes list
        KfsDentry[root].leaf = leaf;                        // the beginning of the list of leafs
    }
    return leaf;                                            // return the found or created leaf
}
References kfs_dentry_s::inode, kfs_alloc_dentry(), kfs_alloc_inode(), KFS_DIR, KFS_FILE, kfs_strcmp(), KfsDentry, KfsInode, kfs_dentry_s::leaf, kfs_dentry_s::next, kfs_dentry_s::root, and kfs_inode_s::type.
Referenced by dummy_disk(), and kfs_open().
kfs_owner()
int kfs_owner (int inode)
{return KfsInode[inode].owner;}
References KfsInode, and kfs_inode_s::owner.
Referenced by kfs_print_dentry().
kfs_page()
int kfs_page (int inode, int pg_offset)
{
    int size = kfs_size(inode);                             // real size of file
    if ((size==0) || (pg_offset > size>>12)) return -1;     // if pg_offset is > than the nb of page
    if (pg_offset < 12) return KfsInode[inode].page[pg_offset];// page is referenced by inode
    pg_offset -= 12;                                        // all others are in fmaps
    int map1 = kfs_fmap(inode);                             // get the first level
    if (size <= 28<<12) return KfsFmap[map1][pg_offset];    // if size is <= 28 pages, then 1 level
    int map2 = KfsFmap[map1][pg_offset/16];                 // else get the second  level
    return KfsFmap[map2][pg_offset%16];                     // then get the page
}
References kfs_fmap(), kfs_size(), KfsFmap, KfsInode, and kfs_inode_s::page.
Referenced by kfs_print_dentry(), and kfs_read().
kfs_ppage()
static u16_t * kfs_ppage (u16_t inode, u16_t pg_offset) static
returns the pointer to the box containing the page number of the disk corresponding to the page npg_offset of a file. This box is in the inode or in the fmaps.
The 12 first pages are directly referenced by the inode, thus if file is smaller than 48kiB we have just to look in the inode (case [A])
The following 16 are referenced in a fmap pointed by the inode, but olny if file size is smaller than 28 (12+16) pages (112kiB) (case [B])
if the file is greater than 28 pages then the 1st level of map references a 2nd level of fmap and this 2nd level of fmap references pages, thus 16 x 16 pages (1MiB) (case [C])
if fmaps are not yet allocated, the function will do it We may have to create up to 2 maps (1st and 2nd level) and a page. There are many sub-cases depending on the current file size and the future size.
{
    u32_t size = KfsInode[inode].size;              // previous size of file
    u16_t * pfmap2in1;                              // address of 2nd lev fmap in 1st lev fmap
    kfs_fmap_t * pfmap1;                            // 1st level of fmap address
    kfs_fmap_t * pfmap2;                            // 2nd level of fmap address
    u32_t fmap;                                     // 2nd level of fmap
    u32_t old_pg_size = size >> 12;                 // old last page offset of the file
    if (pg_offset < 12)                             // if inside 12 pages mapped by inode
        return &(KfsInode[inode].page[pg_offset]);  // -- get the address of page number
    if (old_pg_size < 12) {                         // if old size is <= 12 pages
        fmap = kfs_alloc_fmap();                    // -- alloc a new fmap
        if (fmap == 0) return NULL;                 // -- no more fmap
        KfsInode[inode].fmap = fmap;                // -- connect inode to the 1st level fmap
    }
    pg_offset -= 12;                                // shift of 12 for the pg_offset
    pfmap1 = &(KfsFmap[KfsInode[inode].fmap]);      // get the address of 1st level of fmap
    if (pg_offset < 16)                             // if new page offset is < 28
        return &((*pfmap1)[pg_offset]);             // -- get addr of page nbr in 1st level fmap
    if (old_pg_size < 28) {                         // if need to change from a 1 to 2 level fmap
        fmap = kfs_alloc_fmap();                    // -- new 1st level fmap
        if (fmap == 0) return NULL;                 // -- no more fmap
        KfsFmap[fmap][0] = KfsInode[inode].fmap;    // -- the old fmap that becomes 2nd level
        KfsInode[inode].fmap = fmap;                // -- connect inode to the 1st level fmap
        pfmap1 = &(KfsFmap[KfsInode[inode].fmap]);  // -- get the new addr of 1st level of fmap
    }
    pfmap2in1 = &((*pfmap1)[pg_offset/16]);         // get addr of 2nd fmap in 1st fmap
    if (*pfmap2in1 == 0) {                          // if 2nd level does not exit
        fmap = kfs_alloc_fmap();                    // -- new 2nd level of fmap
        if (fmap == 0) return NULL;                 // -- no more fmap
        *pfmap2in1 = fmap;                          // -- update le 1st level of fmap
    }
    pfmap2 = &(KfsFmap[*pfmap2in1]);                // get the address of 2nd level of fmap
    return &((*pfmap2)[pg_offset%16]);              // get addr of page nbr in 2nd level fmap
}
References kfs_inode_s::fmap, kfs_alloc_fmap(), KfsFmap, KfsInode, NULL, kfs_inode_s::page, and kfs_inode_s::size.
Referenced by kfs_write().
kfs_read()
int kfs_read (int dentry, int pg_offset, int * buf)
Reads a file, it reads one page from the file dentry to memory buffer. After reading, buffer will contain the entire page of which the offset belongs.
Try to read an entire page (4kiB) from file dentry
{
    int page = kfs_page (kfs_inode (dentry), pg_offset);     // get the page number in the disk
    if (page == -1) return 0;                               // if outside of the file
    return kfs_read_page (buf, page);                       // at last read disk page to buf
}
References kfs_inode(), kfs_page(), and kfs_read_page().
Referenced by dummy_disk(), kfs_print_files(), and split().
kfs_read_page()
static int kfs_read_page (int * buf, u16_t page) static
Reads from the disk to the memory buffer. There are two cases : 1) if kfs runs on Linux 2) if kfs runs on ko6 1) Linux: the kfs disk has been loaded in an array, so that's where we have to read it 2) ko6: the kfs disk is behind the disk device, so we need to ask the disk driver.
Parameters
buf is a buffer address in memory
page is a page number on disk, if page == 0 then the page is considered as full of 0
Returns
0 if buf is filled with 0, 1 if the page read is not empty or -1 in case of failure If page read on disk in empty, but we return 1 it is not a problem
{
    int a = 0;                                              // counter of words
    if (page == 0) {                                        // the page 0 is full of 0
        for (; a != 1024; a++, *(int *)buf++ = 0);          // fill buffer with 0
        return 0;                                           // success
    }
#ifdef HOST
    int * ppage = (int *)KfsDisk[page];               // ppage points to the first int of page
    for (; a != 1024; a++, *buf++ = *ppage++);
    return 1;                                               // success
#else
    return -1;                                              // FIXME  Real disk not yet handled
#endif
}
Referenced by kfs_read().
kfs_readdir()
int kfs_readdir (int root, int leaf, void * buf)
Reads a directory, it reads one entry from the directory dentry to memory buffer. After reading, buffer will contain the name of the directory or item.
readdir reads all entries in a directory
{
    if (!kfs_isdir(root)) return -1;                        // root dentry must be a directory
    if (buf) kfs_strcpy (buf, KfsDentry[leaf].name);        // if asked, get this leaf dentry name
    if (leaf == root)                                       // at first, leaf is the root
        return KfsDentry[root].leaf;                        // get the first leaf thus 0 if empty
    if (KfsDentry[leaf].root != root) return -1;            // leaf must be in root directory
    return KfsDentry[leaf].next;                            // find and return next leaf (0 if last)
}
References kfs_isdir(), kfs_strcpy(), KfsDentry, kfs_dentry_s::leaf, and kfs_dentry_s::next.
Referenced by kfs_tree_cb_r().
kfs_root()
int kfs_root (int dentry)
read access functions to dentries
Parameters
index of a dentry
Returns
- a dentry number for kfs_root(), kfs_next(), kfs_leaf(). For these three functions, 0 means either file system root '/' or last leaf
the inode number for kfs_inode(), there is always one
the pointer to the entry name for kfs_name()
{return KfsDentry[dentry].root ;}
References KfsDentry, and kfs_dentry_s::root.
Referenced by kfs_absolute_pathname(), and kfs_print_dentry().
kfs_set_size()
int kfs_set_size (int dentry, int newsize)
Sets the size field of the inode associated with the dentry to newsize.
Parameters
dentry given by open or openat
newsize new size of the file
Returns
int : the size of the file after modification
{
    u16_t inode = kfs_inode(dentry);                // get inode associated with the dentry
    KfsInode[inode].size = newsize;                 // set the new size
    return kfs_size(inode);
}
References kfs_inode(), kfs_size(), KfsInode, and kfs_inode_s::size.
Referenced by add_new_file(), and dummy_disk().
kfs_size()
int kfs_size (int inode)
{return KfsInode[inode].size; }
References KfsInode, and kfs_inode_s::size.
Referenced by kfs_page(), kfs_print_dentry(), kfs_print_files(), kfs_set_size(), and split().
kfs_strcmp()
static int kfs_strcmp (const char * s1, const char * s2) static
compare two strings of characters
Parameters
s1 is the first string
s2 is the second string
Returns
0 if s1 == s2 or the difference between s1 and s2 on the first character that differs
{
    u8_t c1, c2;
    do {
        c1 = (u8_t) *s1++;
        c2 = (u8_t) *s2++;
    }
    while (c1 && (c1 == c2));
    return c1 - c2;
}
Referenced by kfs_openat().
kfs_strcpy()
static void kfs_strcpy (char * dest, char * src) static
copy a string of characters
Parameters
dest is the address of the destination buffer
src is the address of the source buffer
Returns
nothing but the side effect on destination buffer
{
    for (int i = 0; (i < KFS_MAX_NAME) && (*src); i++)
        *dest++ = *src++;
    *dest = 0;
}
References KFS_MAX_NAME.
Referenced by kfs_alloc_dentry(), and kfs_readdir().
kfs_tree_cb()
int kfs_tree_cb (int root, void(*)(int dentry, int depth, int postion) callback)
{
    callback (root, 0, 0);                                  // callback function execution on root
    if (!kfs_isdir(root)) return 1;                         // if not a directory, it is finished
    return 1+kfs_tree_cb_r (root, 1, callback);             // else start the recursion
}
References kfs_isdir(), and kfs_tree_cb_r().
Referenced by kfs_files(), kfs_tree(), and main().
kfs_tree_cb_r()
static int kfs_tree_cb_r (int root, int depth, void(*)(int dentry, int depth, int pos) callback) static
Recursively executes the callback() function for all entries in a directory. This is a deep-first walk. The callback() function is not executed on the root. _cb_r means "call back recursive" This function must not be used directly, it is used by kfs_tree_cb()
Parameters
root has to be a dentry of a directory
depth is the current depth of the walk
callback is the callback function exectuted on each entry the call back function receives 3 arguments
dentry is the current entry in this directory which can be of any type
depth is the current depth of the walk (necessarily >= 1)
pos is the current position in the current direcrory
Returns
the number of calls of callback()
{
    int calls = 0;                                          // nb of calls at this depth
    int pos = 0;                                            // leaf position in current directory
    int leaf = kfs_readdir (root, root, NULL);              // root dentry has to be a directory
    if (leaf == -1) return 0;                               // if root is not a directory do nothing
    while (leaf) {                                          // while a leaf has been found
        callback (leaf, depth, pos++);                      // callback function execution
        calls++;                                            // increment the number of calls
        if (leaf && kfs_isdir(leaf))                        // if current leaf is a directory
            calls += kfs_tree_cb_r (leaf, depth+1,callback);// recursive call to kfs_tree_cb_r()
        leaf = kfs_readdir (root, leaf, NULL);              // get the next leaf in current root
    }
    return calls;
}
References kfs_isdir(), kfs_readdir(), kfs_tree_cb_r(), and NULL.
Referenced by kfs_tree_cb(), and kfs_tree_cb_r().
kfs_type()
int kfs_type (int inode)
{return KfsInode[inode].type; }
References KfsInode, and kfs_inode_s::type.
Referenced by kfs_print_dentry(), kfs_print_files(), and split().
kfs_unlink()
int kfs_unlink (char * name)
{
    u16_t dentry = kfs_open (name);
    u32_t inode = KfsDentry[dentry].inode;
    u32_t size = KfsInode[inode].size;
    u32_t fmap1 = KfsInode[inode].fmap;
    u32_t fmap2 = 0;
    u32_t freemap=0;
    u16_t * ppage;
    kfs_free_dentry (dentry);
    if (KfsInode[inode].count-- == 0) {
        for (int s = size, p = 0; s > 0; s -= 1<<12, p++){
            if (p < 12) {
                ppage = &(KfsInode[inode].page[p]);
            } else if (size <= (28<<12)) {
                ppage = &(KfsFmap[fmap1][p-12]);
                if (p == size>>12) freemap=1;
            } else {
                fmap2 = KfsFmap[fmap1][(p-12)/16];
                ppage = &(KfsFmap[fmap2][(p-12)%16]);
                if ((p-12)%16 == 15) freemap=2;
                if (p == size>>12) freemap=3;
            }
            kfs_free_page (*ppage);
            if (freemap & 1) kfs_free_fmap(fmap1);
            if (freemap & 2) kfs_free_fmap(fmap2);
        }
        kfs_free_inode (inode);
    }
    return 0;
}
References kfs_inode_s::fmap, kfs_dentry_s::inode, kfs_free_dentry(), kfs_free_fmap(), kfs_free_inode(), kfs_free_page(), kfs_open(), KfsDentry, KfsFmap, KfsInode, kfs_inode_s::page, and kfs_inode_s::size.
kfs_write()
int kfs_write (int dentry, int pg_offset, void * buffer)
Writes one page from memory buffer to file dentry. The buffer is written on the disk in file page of which the offset belongs.
Parameters
dentry given by open or openat
pg_offset is the number of the page that will be written
buffer contains the page to write (at least one page length)
Returns
the number of pages written 1 if success with page in disk as a side effect, 0 if success but buffer was full of 0, thus no page needs to be allocated -1 if something is wrong
{
    u16_t inode = kfs_inode(dentry);                // get inode associated with the dentry
    u16_t *ppage = kfs_ppage (inode, pg_offset);    // get addr in fmaps of page number (alloc fmap)
    if (ppage == NULL) return -1;                   // NULL means no more space in fmaps
    if (*ppage == 0) *ppage = kfs_alloc_page();     // if page absent, allocate a new page
    if (*ppage == 0) return -1;                     // 0 means no more space on the disk
    if (kfs_write_page (buf, *ppage)) return 1;     // at last write disk page from buf
    kfs_free_page (*ppage);                         // if returns 0, it means page full of 0
    return *ppage = 0;                              // erase page number in fmap;
}
References kfs_alloc_page(), kfs_free_page(), kfs_inode(), kfs_ppage(), kfs_write_page(), and NULL.
Referenced by add_new_file(), and dummy_disk().
kfs_write_page()
static int kfs_write_page (void * buf, int page) static
writes to the disk from the memory buffer
Parameters
buf is a buffer address in memory
page is a page number on disk
Returns
0 if new page is full of 0, 1 if the page written is not empty or -1 in case of failure. If page written on disk in empty, but we return 1 it is not a problem
{
#ifdef HOST
    int res = 0;                                            // return value
    int a = 0;                                              // counter of words
    int * buffer = (int *)buf;                              // cast buf to int
    int * ppage = (int *)KfsDisk[page];                     // ppage points to the first int of page
    if ((page == 0) || (page >= KFS_NPG_DISK)) return -1;   // condition : 0 < page < KFS_NBPAGES
    for(;a != 1024; a++, res |= (*ppage++ = *buffer++));    // memory buf to disk page, compute res
    return (res) ? 1 : 0;                                   // if res remains 0 return 0 else 1
#else
    return -1;                                              // FIXME Real disk not yet handled
#endif
}
References buffer, and KFS_NPG_DISK.
Referenced by kfs_write().
Variable Documentation
KfsDentry
kfs_dentry_t KfsDentry[KFS_MAX_DENTRY] static
up to MAX_DENTRY files
Referenced by kfs_alloc_dentry(), kfs_free_dentry(), kfs_inode(), kfs_isdir(), kfs_leaf(), kfs_link(), kfs_name(), kfs_next(), kfs_open(), kfs_openat(), kfs_readdir(), kfs_root(), and kfs_unlink().
KfsFmap
kfs_fmap_t KfsFmap[KFS_MAX_FMAP] static
up to MAX_FMAP inode extensions
Referenced by kfs_free_fmap(), kfs_page(), kfs_ppage(), and kfs_unlink().
KfsInode
kfs_inode_t KfsInode[KFS_MAX_INODE] static
Initial value:
= {
    [0] = {.type=KFS_DIR, .mode=077}
}
Referenced by kfs_alloc_inode(), kfs_chmode(), kfs_chmtime(), kfs_chowner(), kfs_count(), kfs_fmap(), kfs_free_inode(), kfs_isdir(), kfs_link(), kfs_mode(), kfs_mtime(), kfs_openat(), kfs_owner(), kfs_page(), kfs_ppage(), kfs_set_size(), kfs_size(), kfs_type(), and kfs_unlink().
KfsOffset
u16_t KfsOffset[KFS_MAX_INODE] static
last offset used for inode by read write
Referenced by kfs_open().
KfsSblock
kfs_sblock_t KfsSblock static
Initial value:
= {
    .max_dentry = KFS_MAX_DENTRY,
    .max_inode  = KFS_MAX_INODE,
    .max_fmap   = KFS_MAX_FMAP,
    .max_page   = KFS_NPG_DISK,
    .cur_dentry = 1,
    .cur_inode  = 1,
    .cur_fmap   = 1,
    .cur_page   = NPGU,
    .bmp_dentry = { [0] = 1 },
    .bmp_inode  = { [0] = 1 },
    .bmp_fmap   = { [0] = 1 },
    .bmp_page   = {
        [0 ... ((NPGU-1)/8)-1] = 0xFF,
        [((NPGU+7)/8)-1] = (1<<(1+((NPGU+7)%8)))-1}
}
Referenced by kfs_alloc_dentry(), kfs_alloc_fmap(), kfs_alloc_inode(), kfs_alloc_page(), kfs_free_dentry(), kfs_free_fmap(), kfs_free_inode(), and kfs_free_page().