ko6: src/soft/kernel/kirq.c File Reference
kirq.c File Reference
#include <kernel/kirq.h>
Functions
void register_interrupt (unsigned irq, isr_t handler, void *arg)
Assign an ISR (Interrupt-Service Routine) to an IRQ.
void route_interrupt (unsigned irq)
Call the ISR of a given IRQ.
void unregister_interrupt (unsigned irq)
Remove the ISR linked to an IRQ.
Variables
static struct ite_s InterruptVector [MAX_N_IRQS]
Function Documentation
register_interrupt()
void register_interrupt (unsigned irq, isr_t handler, void * arg)
Assign an ISR (Interrupt-Service Routine) to an IRQ.
Parameters
irq the irq
handler the ISR to call
arg argument given to the ISR
{
    InterruptVector[irq].handler = handler;
    InterruptVector[irq].arg = arg;
}
References ite_s::arg, ite_s::handler, and InterruptVector.
Referenced by soc_timer_init(), and soc_tty_init().
route_interrupt()
void route_interrupt (unsigned irq)
Call the ISR of a given IRQ.
Parameters
irq the irq
{
    struct ite_s ite = InterruptVector[irq];
    if (ite.handler)
        ite.handler(irq, ite.arg);
}
References ite_s::arg, ite_s::handler, and InterruptVector.
Referenced by isrcall().
unregister_interrupt()
void unregister_interrupt (unsigned irq)
Remove the ISR linked to an IRQ.
Parameters
irq the irq
{
    // TODO: register kpanic as a default isr, like the old system
    InterruptVector[irq].handler = (isr_t) 0;
    InterruptVector[irq].arg = (void*) 0;
}
References ite_s::arg, ite_s::handler, and InterruptVector.
Variable Documentation
InterruptVector
struct ite_s InterruptVector[MAX_N_IRQS] static
Referenced by register_interrupt(), route_interrupt(), and unregister_interrupt().