ko6: src/soft/kernel/kirq.h File Reference
kirq.h File Reference
Classes
struct ite_s
Interrupt Table Entry, describe what to do for a specific IRQ.
Macros
#define MAX_N_IRQS 1024
Typedefs
typedef void(* isr_t) (unsigned, void *)
Functions
void register_interrupt (unsigned irq, isr_t handler, void *arg)
Assign an ISR (Interrupt-Service Routine) to an IRQ.
void route_interrupt (unsigned irq)
Call the ISR of a given IRQ.
void unregister_interrupt (unsigned irq)
Remove the ISR linked to an IRQ.
Macro Definition Documentation
MAX_N_IRQS
#define MAX_N_IRQS 1024
Typedef Documentation
isr_t
typedef void(* isr_t) (unsigned, void *)
Interrupt table helper functions isr_t is a type of an isr function
This comment explains what is a type of function, and how to create one. If we have a function : RETURN_TYPE FUNCTION_NAME (list of ARG_TYPE ARG_NAME)
For example : int erase (double * tab, unsigned size);
RETURN_TYPE = int * FUNCTION_NAME = erase
ARG_TYPE 1 = double * ARG_TYPE 2 = unsigned
ARG_NAME 1 = tab * ARG_NAME 2 = size
To create a variable named VF which is a pointer to a function, we must write : RETURN_TYPE (*VF) (list of ARG_TYPE ARG_NAME); be warned that the parentheses around *VF are mandatory, otherwise gcc recognize a simple declaration of function
For example, we can write : int (*VF) (double * tab, unsigned size); // declaration of VF VF = erase; // initialisation of VF int x = VF (tab, size); // this line is equivalent to int x = erase (tab, size); // this one
To create a type named TF for the pointer to a function, we must write : typedef RETURN_TYPE (*TF) (list of ARG_TYPE ARG_NAME); the parentheses around *TF are also mandatory,
For example, we can write : typedef int (*TF) (double * tab, unsigned size); TF VF ; VF = erase; int x = VF (tab, size); int x = erase (tab, size);
Function Documentation
register_interrupt()
void register_interrupt (unsigned irq, isr_t handler, void * arg)
Assign an ISR (Interrupt-Service Routine) to an IRQ.
Parameters
irq the irq
handler the ISR to call
arg argument given to the ISR
{
    InterruptVector[irq].handler = handler;
    InterruptVector[irq].arg = arg;
}
References ite_s::arg, ite_s::handler, and InterruptVector.
Referenced by soc_timer_init(), and soc_tty_init().
route_interrupt()
void route_interrupt (unsigned irq)
Call the ISR of a given IRQ.
Parameters
irq the irq
{
    struct ite_s ite = InterruptVector[irq];
    if (ite.handler)
        ite.handler(irq, ite.arg);
}
References ite_s::arg, ite_s::handler, and InterruptVector.
Referenced by isrcall().
unregister_interrupt()
void unregister_interrupt (unsigned irq)
Remove the ISR linked to an IRQ.
Parameters
irq the irq
{
    // TODO: register kpanic as a default isr, like the old system
    InterruptVector[irq].handler = (isr_t) 0;
    InterruptVector[irq].arg = (void*) 0;
}
References ite_s::arg, ite_s::handler, and InterruptVector.