ko6: src/soft/kernel/klibc.h File Reference
klibc.h File Reference
#include <common/debug_off.h>
#include <stdarg.h>
#include <stddef.h>
#include <common/cstd.h>
#include <common/list.h>
#include <common/esc_code.h>
#include <common/errno.h>
#include <common/syscalls.h>
#include <common/usermem.h>
#include <hal/devices/chardev.h>
#include <hal/cpu/atomic.h>
#include <hal/cpu/cache.h>
#include <hal/cpu/thread.h>
#include <hal/cpu/irq.h>
#include <hal/cpu/cpuregs.h>
#include <hal/cpu/kpanic.h>
#include <hal/soc/soc.h>
#include <kernel/kmemory.h>
#include <kernel/kthread.h>
#include <kernel/ksynchro.h>
#include <kernel/kdev.h>
Classes
struct fifo_s
Simple fifo (1 writer - 1 reader)
Macros
#define _KERNEL_
#define VERBOSE 0
#define RAND_MAX 32767 /* maximum random value by default, must be < 0x7FFFFFFE */
#define PRINTF_MAX 256 /* largest printed message */
#define CEIL(a, b) ((int)(b)*(((int)(a)+(int)(b)-1)/(int)(b))) /* round up a aligned on b */
#define FLOOR(a, b) ((int)(b)*((int)(a)/(int)(b))) /* round down a aligned on b */
#define FIFO_DEPTH 20 /* maximum fifo depth */
Functions
int rand (void)
random int generator FIXME must be replaced by /dev/urandom https://en.wikipedia.org/wiki/Linear_congruential_generator (glibc generator)
void srand (unsigned seed)
allow to define a specific random suite
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
int kprintf (char *fmt,...)
print a formated string to the TTY0 this a simplified version which handles only: c, s, $d, x and p
void exit (int status)
exit the application, thus never returns
int tty_read (int tty, char *buf, unsigned count)
Wrapper function that selects the correct TTY based on his number and call the read function.
int tty_write (int tty, char *buf, unsigned count)
Wrapper function that selects the correct TTY based on his number and call the write function.
int tty_putc (int tty, int c)
write a single char to the tty
int tty_getc (int tty)
read a single char from the tty
int tty_puts (int tty, char *buf)
send all char of a buffer to the tty until a 0 is found
int tty_gets (int tty, char *buf, int count)
read any char from the tty until
is found or count-1 is reached, add 0 at the end
int fifo_push (struct fifo_s *fifo, char c)
push a character into the chardev's FIFO
int fifo_pull (struct fifo_s *fifo, int *c)
pop a character from the chardev's FIFO
Macro Definition Documentation
_KERNEL_
#define _KERNEL_
CEIL
#define CEIL (a, b) ((int)(b)*(((int)(a)+(int)(b)-1)/(int)(b))) /* round up a aligned on b */
FIFO_DEPTH
#define FIFO_DEPTH 20 /* maximum fifo depth */
FLOOR
#define FLOOR (a, b) ((int)(b)*((int)(a)/(int)(b))) /* round down a aligned on b */
PRINTF_MAX
#define PRINTF_MAX 256 /* largest printed message */
RAND_MAX
#define RAND_MAX 32767 /* maximum random value by default, must be < 0x7FFFFFFE */
VERBOSE
#define VERBOSE 0
Function Documentation
delay()
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
Parameters
nbcycles number of cycle to wait
{
    unsigned old_time, expected_time;
    old_time = clock ();                        // get the number od cycles at first
    expected_time = old_time + nbcycles;        // compute the number of cycles to reach
    while (clock () < expected_time);           // wait for expected time
}
exit()
void exit (int status)
exit the application, thus never returns
Parameters
status return value of the application
{
    PANIC_IF(true,"\n\nEXIT status = %d\n", status);
}
fifo_pull()
int fifo_pull (struct fifo_s * fifo, int * c)
pop a character from the chardev's FIFO
Parameters
fifo structure of fifo to store data
c pointer on char to put the read char
Returns
SUCCESS or FAILURE
{
    if (fifo->pt_read != fifo->pt_write) {
        *c = fifo->data [fifo->pt_read];
        fifo->pt_read = (fifo->pt_read + 1)% sizeof(fifo->data);
        return SUCCESS;
    }
    return FAILURE;
}
References fifo_s::data, FAILURE, fifo_s::pt_read, fifo_s::pt_write, and SUCCESS.
Referenced by ns16550_read(), and soclib_tty_read().
fifo_push()
int fifo_push (struct fifo_s * fifo, char c)
push a character into the chardev's FIFO
Parameters
fifo structure of fifo to store data
c char to write
Returns
SUCCESS or FAILURE
{
    unsigned pt_write_next = (fifo->pt_write + 1) % sizeof(fifo->data);
    if (pt_write_next != fifo->pt_read) {
        fifo->data [fifo->pt_write] = c;
        fifo->pt_write = pt_write_next;
        return SUCCESS;
    }
    return FAILURE;
}
References fifo_s::data, FAILURE, fifo_s::pt_read, fifo_s::pt_write, and SUCCESS.
Referenced by ns16550_isr(), and soclib_tty_isr().
kprintf()
int kprintf (char * fmt, ...)
print a formated string to the TTY0 this a simplified version which handles only: c, s, $d, x and p
Parameters
fmt formated string
... variadic arguments, i.e. variable number of arguments
Returns
number of printed char
{
    char buffer[PRINTF_MAX];
    va_list ap;
    va_start (ap, fmt);
    int res = vsnprintf(buffer, sizeof(buffer), fmt, ap);
    tty_write(0, buffer, res);
    va_end(ap);
    return res;
}
References buffer, PRINTF_MAX, tty_write(), and vsnprintf().
Referenced by kdump(), kinit(), kmalloc_print(), kmalloc_test(), print_ustack(), sched_dump(), sched_insert(), and unknown_syscall().
rand()
int rand (void)
random int generator FIXME must be replaced by /dev/urandom https://en.wikipedia.org/wiki/Linear_congruential_generator (glibc generator)
Returns
a random int between 0 and RAND_MAX
{
    randseed = randseed * 1664525 + 1013904223; // Numerical Recipes
    return (randseed>>1);
}
srand()
void srand (unsigned seed)
allow to define a specific random suite
Parameters
seed any integer
{
    randseed = seed;
}
tty_getc()
int tty_getc (int tty)
read a single char from the tty
Parameters
tty tty number (between 0 and NTTYS-1)
Returns
the read char
{
    char c;
    tty_read (tty, &c, 1);                      // read only 1 char
    tty_write (tty, &c, 1);                     // loop back to the tty
    return c;                                   // return the read char
}
References tty_read(), and tty_write().
tty_gets()
int tty_gets (int tty, char * buf, int count)
read any char from the tty until
is found or count-1 is reached, add 0 at the end
Parameters
tty tty number (between 0 and NTTYS-1)
buf buffer where the read char are put
count buffer size
Returns
the number of read chars
{
    // to make the backspace, we use ANSI codes : https://www.wikiwand.com/en/ANSI_escape_code
    char *DEL = "\033[D \033[D";                // move left, then write ' ' and move left
    int res = 0;
    count--;                                    // we need to add a NUL (0) char at the end
    char c=0;
    while ((count != 0) && (c != '\n')) {       // as long as we can or need to get a char
        tty_read (tty, &c, 1);                  // read only 1 char
        if (c == '\r')                          // if c is the carriage return (13)
            tty_read (tty, &c, 1);              // get the next that is line feed (10)
        if ((c == 8)||(c == 127)) {             // 8 = backspace, 127 = delete
            if (res) {                          // go back in the buffer if possible
                tty_write (tty, DEL, 7);        // replace the current char by a ' ' (space)
                count++;                        // count is the remaining place
                buf--;                          // but is the next address in buffer
                res--;
            }
            continue;                           // ask for another key
        } else
            tty_write (tty, &c, 1);             // loop back to the tty
        *buf = c;                               // write the char into the buffer
        buf++;                                  // increments the writing pointer
        count--;                                // decrements the remaining space
        res++;                                  // increments the read char
    }
    *buf = 0;                                   // add a last 0 to end the string
    return res;                                 // returns the number of char read
}
References tty_read(), and tty_write().
tty_putc()
int tty_putc (int tty, int c)
write a single char to the tty
Parameters
tty tty number (between 0 and NTTYS-1)
c the char to write
Returns
the written character
{
    tty_write (tty, (char *)&c, 1);             // only write one char
    return c;
}
References tty_write().
tty_puts()
int tty_puts (int tty, char * buf)
send all char of a buffer to the tty until a 0 is found
Parameters
tty tty number (between 0 and NTTYS-1)
buf buffer pointer
Returns
the number of written char
{
    int count = 0;                              // nb of written char
    while (buf[count++]);                       // count the number of char
    return tty_write (tty, buf, count);         // send buf to the tty
}
References tty_write().
tty_read()
int tty_read (int tty, char * buf, unsigned count)
Wrapper function that selects the correct TTY based on his number and call the read function.
Parameters
tty the TTY's number
buf target buffer where the user's entry will be typed
count number of bytes to write into buffer
{
    /* If the tty is not available, default to 0 */
    if (tty > chardev_count())
        tty = 0;
    struct chardev_s *cdev = chardev_get(tty);
    if (cdev)
        return cdev->ops->chardev_read(cdev, buf, count);
    // TODO: do a more specific error if the TTY is unavailable
    return -1;
}
References chardev_count, chardev_get, chardev_ops_s::chardev_read, and chardev_s::ops.
Referenced by tty_getc(), and tty_gets().
tty_write()
int tty_write (int tty, char * buf, unsigned count)
Wrapper function that selects the correct TTY based on his number and call the write function.
Parameters
tty the TTY's number
buf target buffer sent to the tty
count number of bytes to read into buffer
{
    /* If the tty is not available, default to 0 */
    if (tty > chardev_count())
        tty = 0;
    struct chardev_s *cdev = chardev_get(tty);
    if (cdev)
        return cdev->ops->chardev_write(cdev, buf, count);
    return -1;
}
References chardev_count, chardev_get, chardev_ops_s::chardev_write, and chardev_s::ops.
Referenced by kprintf(), tty_getc(), tty_gets(), tty_putc(), and tty_puts().