ko6: src/soft/kernel/ksynchro.h File Reference
ksynchro.h File Reference
Typedefs
typedef struct thread_mutex_s * thread_mutex_t
hidden mutex type, the other modules do not what is in the mutex structure
typedef struct thread_barrier_s * thread_barrier_t
hidden barrier type, the user do not what is in the barrier structure
Functions
int thread_mutex_init (thread_mutex_t *mutex)
creates a new mutex and initializes mutex variable with the new mutex (side effect) it is a nutex with error checking
int thread_mutex_destroy (thread_mutex_t *mutex)
destroy the referenced mutex If the mutex is locked the destruction is not done, this is an error
int thread_mutex_lock (thread_mutex_t *mutex)
lock the referenced mutex, it is a blocking operation. If the mutex is already locked, the calling thread blocks until the mutex becomes available. If the mutex does not exist or is already locked, this is an error
int thread_mutex_unlock (thread_mutex_t *mutex)
unlock the referenced mutex If the mutex does not exist or is not locked or has been locked by another, this is an error that causes exit with error
int thread_barrier_init (thread_barrier_t *barrier, size_t count)
creates or initialize a barrier depending the value of barrier parameter
int thread_barrier_wait (thread_barrier_t *barrier)
wait to the referenced barrier, it is a blocking operation for all thread but the last the last arrived thread doesn't wait and notifies the other threads which becomes READY
int thread_barrier_destroy (thread_barrier_t *barrier)
destroy the referenced barrier If a thread is waiting at the barrier, then the destruction is not done, it is an error
Typedef Documentation
thread_barrier_t
typedef struct thread_barrier_s* thread_barrier_t
hidden barrier type, the user do not what is in the barrier structure
thread_mutex_t
typedef struct thread_mutex_s* thread_mutex_t
hidden mutex type, the other modules do not what is in the mutex structure
Function Documentation
thread_barrier_destroy()
int thread_barrier_destroy (thread_barrier_t * barrier)
destroy the referenced barrier If a thread is waiting at the barrier, then the destruction is not done, it is an error
Parameters
barrier a pointer referencing a barrier
Returns
SUCCESS if it all goes fine or EINVAL wrong argument EBUSY The implementation has detected an attempt to destroy a barrier while it is in use (for example, while being used in a thread_barrier_wait()
call) by another thread.
{
    thread_barrier_t b = *barrier;                          // get the barrier pointer
    if (b == NULL) return EINVAL;                           // b is not created
    if (b && (b->magic != MAGIC_BARRIER)) return EINVAL;    // check that it is barrier (MAGIC)
    spin_lock (&b->lock);                                   // get the ownership
    if (b->waiting != 0) {                                  // if barrier is in use
        spin_unlock (&b->lock);                             // release the lock
        return EBUSY;                                       // return an error
    }
    kfree (b, sizeof (struct thread_barrier_s));            // destroys barrier & erases its memory
    return SUCCESS;                                         // erasing the memory releases the lock
}
References barrier, EBUSY, EINVAL, kfree(), thread_barrier_s::lock, thread_barrier_s::magic, MAGIC_BARRIER, NULL, spin_lock(), spin_unlock(), SUCCESS, and thread_barrier_s::waiting.
thread_barrier_init()
int thread_barrier_init (thread_barrier_t * barrier, size_t count)
creates or initialize a barrier depending the value of barrier parameter
Parameters
barrier a pointer referencing the barrier, there are two cases 1) if *barrier == NULL then allocate a new barrier, then initialize count 2) if *barrier != NULL it the barrier already exists, just initialize count
count number of expected threads for this barrier
Returns
SUCCESS if it all goes fine or EINVAL barrier is not a barrier or the value specified by count is equal to zero. ENOMEM Insufficient memory exists to initialize the barrier EBUSY The implementation has detected an attempt to reinitialize a barrier while it is in use (for example, while being used in a thread_barrier_wait()
call) by another thread.
{
    thread_barrier_t b = *barrier;                          // get the barrier pointer
    if (count == 0) return EINVAL;                          // count must be > 0
    if (b == NULL) {                                        // if we need a new barrier
        b = kmalloc (sizeof (struct thread_barrier_s));     // allocates a new barrier
        if (b == NULL) return ENOMEM;                       // test if there is enough memory
        b->magic = MAGIC_BARRIER;                           // tell it is a BARRIER
        b->lock = 0;                                        // free the lock
        b->expected = count;                                // init the expected threads
        b->waiting = 0;                                     // init the counter of waiting threads
        list_init (&b->wait);                               // init the waiting list
        *barrier = b;                                       // at last, init. the return variable
        return SUCCESS;                                     // it's fine
    }
    if (b && (b->magic != MAGIC_BARRIER)) return EINVAL;    // it is not an old barrier
    spin_lock (&b->lock);                                   // get the ownership
    if (b->waiting != 0) {                                  // if someone is waiting
        spin_lock (&b->lock);                               // release the ownership
        return EBUSY;                                       // return an error
    }
    b->expected = count;                                    // set the number of expected threads
    spin_lock (&b->lock);                                   // release the ownership
    return SUCCESS;                                         // it's fine
}
References barrier, EBUSY, EINVAL, ENOMEM, thread_barrier_s::expected, kmalloc(), list_init(), thread_barrier_s::lock, thread_barrier_s::magic, MAGIC_BARRIER, NULL, spin_lock(), SUCCESS, thread_barrier_s::wait, and thread_barrier_s::waiting.
thread_barrier_wait()
int thread_barrier_wait (thread_barrier_t * barrier)
wait to the referenced barrier, it is a blocking operation for all thread but the last the last arrived thread doesn't wait and notifies the other threads which becomes READY
Parameters
barrier a pointer referencing a barrier
Returns
SUCCESS or FEALURE
{
    thread_barrier_t b = *barrier;                          // get the barrier pointer
    if (b == NULL) return EINVAL;                           // b is not created
    if (b && (b->magic != MAGIC_BARRIER)) return EINVAL;    // check that it is barrier (MAGIC)
    spin_lock (&b->lock);                                   // get the ownership
    b->waiting++;                                           // the current thread is the newcomer
    if (b->waiting == b->expected) {                        // if all the expected threads are there
        list_foreach (&b->wait, waiting_item) {             // then for each thread waiting
            list_unlink (waiting_item);                     // get thread from waiting list
            thread_t t = thread_item (waiting_item);        // get the pointer of a waiting thread
            thread_notify (t);                              // and notifies it
        }
        b->waiting = 0;                                     // init the counter of waiting threads
        spin_unlock (&b->lock);                             // release the ownership
    } else {
        thread_addlast (&b->wait, ThreadCurrent);           // the current thread in the wait. list
        spin_unlock (&b->lock);                             // release the lock
        thread_wait ();                                     // tell the thread to wait
    }
    return SUCCESS;                                         // it's fine
}
References barrier, EINVAL, thread_barrier_s::expected, list_foreach, list_unlink(), thread_barrier_s::lock, thread_barrier_s::magic, MAGIC_BARRIER, NULL, spin_lock(), spin_unlock(), SUCCESS, thread_addlast(), thread_item(), thread_notify(), thread_wait(), ThreadCurrent, thread_barrier_s::wait, and thread_barrier_s::waiting.
thread_mutex_destroy()
int thread_mutex_destroy (thread_mutex_t * mutex)
destroy the referenced mutex If the mutex is locked the destruction is not done, this is an error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
Destroy the given mutex if possible
{
    thread_mutex_t m = *mutex;
    if (m == NULL) return EINVAL;                               // unitialized mutex
    if (m->busy) return EBUSY;                                  // try to destroy an lock mutex
    if (m->owner != ThreadCurrent) return EPERM;                // the thread does not own the mutex
    kfree (m, sizeof (*m));
    return SUCCESS;
}
References thread_mutex_s::busy, EBUSY, EINVAL, EPERM, kfree(), NULL, thread_mutex_s::owner, SUCCESS, and ThreadCurrent.
thread_mutex_init()
int thread_mutex_init (thread_mutex_t * mutex)
creates a new mutex and initializes mutex variable with the new mutex (side effect) it is a nutex with error checking
Parameters
mutex a pointer referencing the new mutex
Returns
0 on success, 1 on fealure
Create and initialize a mutex
{
    thread_mutex_t m = kmalloc (sizeof (*m));                   // Get memory
    if (m == NULL) return ENOMEM;                               // malloc impossible
    m->lock = 0;                                                // lock to protect
    m->busy = 0;                                                // busy is free at first
    list_init (&m->wait);                                       // no waiting threads
    m->owner = NULL;                                            // no thread owns the mutex
    *mutex = m;                                                 // at last save the new mutex
    return SUCCESS;
}
References thread_mutex_s::busy, ENOMEM, kmalloc(), list_init(), thread_mutex_s::lock, NULL, thread_mutex_s::owner, SUCCESS, and thread_mutex_s::wait.
thread_mutex_lock()
int thread_mutex_lock (thread_mutex_t * mutex)
lock the referenced mutex, it is a blocking operation. If the mutex is already locked, the calling thread blocks until the mutex becomes available. If the mutex does not exist or is already locked, this is an error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
lock = Acquire the mutex. First, check if the arguments are legal, then take the lock that protects the mutex, it is an active loop but not too long. After that, there are two possibilities: A) the mutex is busy, B) the mutex is free. A) busy case: ThreadCurrent is added to the end of the mutex's pending thread list using thread_addlast(). This function is defined in the thread API (kthread.c), note that we cannot use list_addlast() as we do not have access to the thread structure (it is a hidden structure for security reasons). Next, we need to release the lock, then finally the current thread needs to change its state from RUNNING to WAIT. When the thread that currently owns the mutex releases it, then it will give ownership of the mutex by leaving the state occupied, but changing the owner field. Note that it is possible that the release of the mutex occurs just after the current thread has decided to wait, there could be a risk that it will start waiting while it owns the mutex. This case is handled by the thread_wait() and thread_notify() functions, details are in the comments of these functions in kthread.c. B) free case : it's quite simple, it just have to set busy to 1 and fill the ownership field, and release the lock.
{
    thread_mutex_t m = *mutex;
    if (m == NULL) return EINVAL;                           // unitialized mutex
    if (m->busy && (m->owner == ThreadCurrent)) return EDEADLK; // try to lock several times
    spin_lock (&m->lock);                                   // take the lock of the mutex
    if (m->busy) {                                          // if the mutex is busy
        thread_addlast (&m->wait, ThreadCurrent);           // put the current thread waiting
        spin_unlock (&m->lock);                             // give the lock back
        thread_wait ();                                     // tell the thread to wait
    } else {
        m->busy = 1;                                        // take the mutex
        m->owner = ThreadCurrent;                           // set the ownership
        spin_unlock (&m->lock);                             // give the lock back
    }
    return SUCCESS;                                         // and return with success
}
References thread_mutex_s::busy, EDEADLK, EINVAL, thread_mutex_s::lock, NULL, thread_mutex_s::owner, spin_lock(), spin_unlock(), SUCCESS, thread_addlast(), thread_wait(), ThreadCurrent, and thread_mutex_s::wait.
thread_mutex_unlock()
int thread_mutex_unlock (thread_mutex_t * mutex)
unlock the referenced mutex If the mutex does not exist or is not locked or has been locked by another, this is an error that causes exit with error
Parameters
mutex a pointer referencing a mutex
Returns
0 on success, 1 on fealure
unlock : release the mutex First, check if the arguments are legal, then take the lock that protects the mutex, Then, get the thread in the thread waiting list of the mutex. There are two possibilities: A) there is one or B) there is not. A) There is a waiting thread, leave the busy field set to 1, change the property and notify the waiting thread with thread_notify() and it will become READY. If the new mutex owner decide to wait while the current thread try to notify it, there could be a risk that the new mutex owner waits definitively with the mutex ownership. This case is handled by the functions thread_wait() and thread_notify(), see details in kthread.c B) There is no waiting thread, reset busy and owner. At last, in both cases, the mutex lock is released.
{
    thread_mutex_t m = *mutex;
    if (m == NULL) return EINVAL;                           // unitialized mutex
    if (m->busy == 0) return EINVAL;                        // unlocked an unlock mutex
    if (m->owner != ThreadCurrent) return EPERM;            // the thread does not own the mutex
    spin_lock (&m->lock);                                   // take the lock of the mutex
    list_t * waiting_item = list_getfirst(&m->wait);        // get thread from waiting list
    if (waiting_item) {                                     // if there is a thread waiting
        m->owner = thread_item (waiting_item);              // get the new mutex owner
        thread_notify (m->owner);                           // this thread owns the mutex
    } else {                                                // no thread is waiting
        m->busy = 0;                                        // free the mutex
        m->owner = NULL;                                    // delete the owner field
    }
    spin_unlock (&m->lock);                                 // give the lock back
    return SUCCESS;
}
References thread_mutex_s::busy, EINVAL, EPERM, list_getfirst(), thread_mutex_s::lock, NULL, thread_mutex_s::owner, spin_lock(), spin_unlock(), SUCCESS, thread_item(), thread_notify(), ThreadCurrent, and thread_mutex_s::wait.