ko6: src/soft/ulib/libc.c File Reference
libc.c File Reference
#include <libc.h>
Functions
void perror (char *s)
finds the error message corresponding to the current value of the global variable errno and writes it, followed by a newline (errno is thread safe)
void exit (int status)
exit the application, thus never returns
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
int read (int fd, void *buf, int count)
reads in at most count characters from fd and stores them into buf.
int write (int fd, void *buf, int count)
write in at most count characters from buf to fd.
unsigned clock (void)
clock cycle counter
void dcache_buf_inval (void *buf, size_t size)
invalidate all lines from data L1 cache belonging to buffer buf
void dcache_inval (void *addr)
invalidate the line from data L1 cache where the addr is located
size_t cachelinesize (void)
get the cache line size in bytes
int rand (void)
random int generator FIXME must be replaced by /dev/urandom https://en.wikipedia.org/wiki/Linear_congruential_generator (glibc generator)
void srand (unsigned seed)
allow to define a specific random suite
int fputc (int tty, int c)
write un single char on tty
int fgetc (int tty)
reads the next character from tty and returns it cast to an int
int fgets (char *buf, int count, int tty)
reads in at most size-1 characters from tty and stores them into the buffer s. Reading stops after a newline. If a newline is read, it is stored into the buffer. A terminating null byte (0) is stored after the last character in the buffer.
int fprintf (int tty, char *fmt,...)
this a simplified version which handles only: c, s, $d, x and p
Variables
static unsigned randnext = 1
Function Documentation
cachelinesize()
size_t cachelinesize (void)
get the cache line size in bytes
ask the processor what is the L1-cache line size
Returns
the size
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CACHELINESIZE);
}
References SYSCALL_CACHELINESIZE, and syscall_fct().
Referenced by malloc_init(), and memory_init().
clock()
unsigned clock (void)
clock cycle counter
Returns
the number of cycles from the reset
{
    return syscall_fct (0, 0, 0, 0, SYSCALL_CLOCK);
}
References SYSCALL_CLOCK, and syscall_fct().
Referenced by delay(), sched_dump(), and sched_insert().
dcache_buf_inval()
void dcache_buf_inval (void * buf, size_t size)
invalidate all lines from data L1 cache belonging to buffer buf
Parameters
buf user buffer address
size buffer size in bytes
{
    syscall_fct (0, 0, 0, 0, SYSCALL_DCACHEBUFINVAL);
}
References SYSCALL_DCACHEBUFINVAL, and syscall_fct().
dcache_inval()
void dcache_inval (void * addr)
invalidate the line from data L1 cache where the addr is located
Parameters
addr address into the line to invalidate
{
    syscall_fct (0, 0, 0, 0, SYSCALL_DCACHEINVAL);
}
References SYSCALL_DCACHEINVAL, and syscall_fct().
delay()
void delay (unsigned nbcycles)
stop until a delay mesured in cycles
Parameters
nbcycles number of cycle to wait
{
    unsigned old_time, expected_time;
    old_time = clock ();                        // get the number of cycles at first
    expected_time = old_time + nbcycles;        // compute the number of cycles to reach
    while (clock () < expected_time);           // wait for expected time
}
References clock().
exit()
void exit (int status)
exit the application, thus never returns
Parameters
status return value of the application
{
    syscall_fct( status, 0, 0, 0, SYSCALL_EXIT);        // never returns
}
References SYSCALL_EXIT, and syscall_fct().
fgetc()
int fgetc (int tty)
reads the next character from tty and returns it cast to an int
Parameters
tty tty number (between 0 and TTY_MAX-1)
{
    char buf[1];                                // create a buffer for the read char
    int res = read (tty, buf, 1);               // ask for one char from TTY
    if (res != 1) return 0;                     // if no char read, should return EOF
    res = write (tty, buf, 1);                  // send it back to the TTY
    if (res != 1) return 0;                     // if no char written, should return EOF
    return (int) buf[0];                        // return char read
}
References read(), and write().
fgets()
int fgets (char * s, int size, int tty)
reads in at most size-1 characters from tty and stores them into the buffer s. Reading stops after a newline. If a newline is read, it is stored into the buffer. A terminating null byte (0) is stored after the last character in the buffer.
Parameters
s pointer to the buffer where the characters read will be written
size number of places in bytes in the buffer s.
tty tty number (between 0 and TTY_MAX-1) should be a FILE *
{
    // to make the backspace, we use ANSI codes : https://www.wikiwand.com/en/ANSI_escape_code
    char *DEL = "\033[D \033[D";                // move left, then write ' ' and move left
    int res = 0;
    count--;                                    // we need to add a NUL (0) char at the end
    char c=0;
    while ((count != 0) && (c != '\n')) {       // as long as we can or need to get a char
        read (tty, &c, 1);                      // read only 1 char
        if (c == '\n')                          // if c is the line feed (10)
            read (tty, &c, 1);                  // drop it and read the next one
        if (c == '\r')                          // if c is the carriage return (13)
                c = '\n';                       // change it for '\n', that is what fgets waits for
        if ((c == 8)||(c == 127)) {             // 8 = backspace, 127 = delete
            if (res) {                          // go back in the buffer if possible
                write (tty, DEL, 7);            // erase current char
                count++;                        // count is the remaining place
                buf--;                          // but is the next address in buffer
                res--;
            }
            continue;                           // ask for another key
        } else {
            write (tty, &c, 1);                 // loop back to the tty
        }
        *buf = c;                               // write the char into the buffer
        buf++;                                  // increments the writing pointer
        count--;                                // decrements the remaining space
        res++;                                  // increments the read char
    }
    *buf = 0;                                   // add a last 0 to end the string
    return res;                                 // returns the number of char read
}
References read(), and write().
Referenced by main().
fprintf()
int fprintf (int tty, char * fmt, ...)
this a simplified version which handles only: c, s, $d, x and p
Parameters
tty tty number (between 0 and TTY_MAX-1)
fmt formated string
... variadic arguments, i.e. variable number of arguments
Returns
number of printed char
{
    static char buffer[PRINTF_MAX];
    int res;
    va_list ap;
    va_start (ap, fmt);
    res = vsnprintf(buffer, sizeof(buffer), fmt, ap);
    res = write( tty, buffer, res);
    va_end(ap);
    return res;
}
References buffer, PRINTF_MAX, vsnprintf(), and write().
Referenced by main(), malloc_print(), perror(), and t0_fun().
fputc()
int fputc (int tty, int c)
write un single char on tty
Parameters
tty tty number (between 0 and TTY_MAX-1)
c char to print
Returns
the written char
{
    write (tty, &c, 1);                         // the char is in the least significant byte
    return c;
}
References write().
perror()
void perror (char * s)
finds the error message corresponding to the current value of the global variable errno and writes it, followed by a newline (errno is thread safe)
Parameters
s is a string written if not NULL and not empty just before the system error
{
    if (s && *s)
        fprintf (0, "%s: %s\n", s, errno_mess[errno + 1]); // first number of errno is -1
    else
        fprintf (0, "%s\n", errno_mess[errno + 1]);
}
References errno, errno_mess, and fprintf().
rand()
int rand (void)
random int generator FIXME must be replaced by /dev/urandom https://en.wikipedia.org/wiki/Linear_congruential_generator (glibc generator)
random int generator
Returns
a random int between 0 and RAND_MAX
{
    randnext = (randnext * 1103515245 + 12345) % ((unsigned) RAND_MAX + 1);
    return randnext;
}
References RAND_MAX, and randnext.
read()
int read (int fd, void * buf, int count)
reads in at most count characters from fd and stores them into buf.
Parameters
fd normally it is the file descriptor, but now it is just the tty number
buf pointer to the buffer
count number of bytes to read, must be lower than buf size
Returns
on success, the number of char read, else -1
{
    return syscall_fct( fd, (int)buf, count, 0, SYSCALL_READ);
}
References syscall_fct(), and SYSCALL_READ.
Referenced by add_new_file(), fgetc(), and fgets().
srand()
void srand (unsigned seed)
allow to define a specific random suite
Parameters
seed any integer
{
    randnext = seed;
}
References randnext.
write()
int write (int fd, void * buf, int count)
write in at most count characters from buf to fd.
Parameters
fd normally it is the file descriptor, but now it is just the tty number
buf pointer to the buffer
count number of bytes to write, must be lower than buf size
Returns
on success, the number of written char, else -1
{
    return syscall_fct( fd, (int)buf, count, 0, SYSCALL_WRITE);
}
References syscall_fct(), and SYSCALL_WRITE.
Referenced by fgetc(), fgets(), fprintf(), fputc(), kfs_print_files(), and split().
Variable Documentation
randnext
unsigned randnext = 1 static
Referenced by rand(), and srand().