ko6: src/soft/ulib/memory.c File Reference
memory.c File Reference
#include <libc.h>
Classes
struct block_info_s
struct heap_s
Macros
#define LINE_FLOOR(p) (block_info_t *)FLOOR((size_t)(p),CacheLineSize)
#define LINE_CEIL(p) (block_info_t *)CEIL((size_t)(p),CacheLineSize)
#define BINFO_SZ sizeof(block_info_t)
Typedefs
typedef struct block_info_s block_info_t
Functions
static void * try_malloc (size_t size)
static void merge (block_info_t *ptr)
void * sbrk (int incr)
change the boundary of the heap
void malloc_init (void *beg)
Heap initialiation, called only once before to call the main() fonction.
void * malloc (size_t size)
void free (void *ptr)
free an allocated object with malloc(), object is not erased.
void malloc_print (size_t level)
print the heap state
Variables
static size_t CacheLineSize
static struct heap_s Heap
Macro Definition Documentation
BINFO_SZ
#define BINFO_SZ sizeof(block_info_t)
LINE_CEIL
#define LINE_CEIL (p) (block_info_t *)CEIL((size_t)(p),CacheLineSize)
LINE_FLOOR
#define LINE_FLOOR (p) (block_info_t *)FLOOR((size_t)(p),CacheLineSize)
Typedef Documentation
block_info_t
typedef struct block_info_s block_info_t
Function Documentation
free()
void free (void * ptr)
free an allocated object with malloc(), object is not erased.
Parameters
ptr previously allocated object pointer
{
    block_info_t *info = (block_info_t *)ptr - 1;           // block_info is just before ptr
    if (!ptr || !info->full || (info->magic != MAGIC_HEAP)) // pt NULL OR segment free OR not MAGIC
        exit(1);                                            // memory corrupted
    info->full = 0;                                         // erase the full flag
}
References exit(), block_info_s::full, block_info_s::magic, and MAGIC_HEAP.
Referenced by build(), and split().
malloc()
void * malloc (size_t size)
{
    block_info_t *ptr = try_malloc (size);                  // Search for a block
    if (ptr == NULL) {                                      // if no free space
        merge (Heap.beg);                                   // merge all free blocks from beginning
        ptr = try_malloc (size);                            // try again to find a block
    }
    if (ptr == NULL)
        errno = ENOMEM;
    return ptr;                                             // return what you have found
}
References heap_s::beg, ENOMEM, errno, Heap, merge(), NULL, and try_malloc().
Referenced by build(), and split().
malloc_init()
void malloc_init (void * start)
Heap initialiation, called only once before to call the main() fonction.
Parameters
start address of the first byte
{
    CacheLineSize = cachelinesize();                        // need to know the cache line size
    int *end = sbrk (4* PAGE_SIZE);                         // try to get 4 pages (16ko)
    if (end == (int *)-1) exit (2);                         // if impossible exit the app
    Heap.beg = LINE_FLOOR (beg);                            // address of the first BLOCK
    Heap.end = LINE_FLOOR (end);                            // address of the boundary
    Heap.beg->full = 0;                                     // empty at the begining
    Heap.beg->magic = MAGIC_HEAP;                           // to try detect Heap corruption
    Heap.beg->size = Heap.end - Heap.beg;                   // size of free space
    CacheLineSize = cachelinesize();                        // ask the kernel for cache line size
}
References heap_s::beg, cachelinesize(), CacheLineSize, heap_s::end, exit(), block_info_s::full, Heap, LINE_FLOOR, block_info_s::magic, MAGIC_HEAP, PAGE_SIZE, sbrk(), and block_info_s::size.
Referenced by _start().
malloc_print()
void malloc_print (size_t level)
print the heap state
Parameters
level use: 0 = full/free bytes; 1 = the nb of blocks full/free per size; 2 = all details
{
    block_info_t *ptr;
    fprintf (0, "------------ %p ------------\n", Heap.beg);
    for (ptr = Heap.beg; ptr < Heap.end; ptr += ptr->size)  // browse all blocks
        fprintf (0, " %s  [ %x\t- %x\t] = %d\n",
            (ptr->full) ? "full" : "free",                  // print if block is full or free
            BINFO_SZ*(size_t)(ptr - Heap.beg),              // print block begin position
            BINFO_SZ*(size_t)((ptr + ptr->size) - Heap.beg),// print block end position
            BINFO_SZ*(size_t)(ptr->size));                  // print block size
    fprintf (0, "------------ %p ------------\n", Heap.end);
}
References heap_s::beg, BINFO_SZ, heap_s::end, fprintf(), block_info_s::full, Heap, and block_info_s::size.
merge()
static void merge (block_info_t * ptr) static
{
    for (; ptr != Heap.end; ptr += ptr->size)               // try to merge all free blocks from ptr
        if (ptr->full == 0)                                 // if current block is free
            for (block_info_t * next = ptr + ptr->size;     // find next one
                ((next != Heap.end) && (next->full == 0));  // while not end found a free block
                next = ptr + ptr->size)                     // go to next block
                ptr->size += next->size;                    // merge current block with first free
}
References heap_s::end, block_info_s::full, Heap, and block_info_s::size.
Referenced by malloc().
sbrk()
void * sbrk (int increment)
change the boundary of the heap
change the boundary of heap
Parameters
increment integer added to the current heap boundary
Returns
SUCCESS or FAILURE
{
    void *r = (void*)syscall_fct(incr,0,0,0,SYSCALL_SBRK);  // ask for heap boundary change
    sbrk_s();
    return r;
}
References sbrk_s(), syscall_fct(), and SYSCALL_SBRK.
Referenced by malloc_init().
try_malloc()
static void * try_malloc (size_t size) static
{
    size = CEIL (size+BINFO_SZ, CacheLineSize);             // true required size in bytes
    size = size / sizeof (block_info_t);                    // in the heap size is in block_info_t
    block_info_t *oldnext, *newnext, *new;
    for (new = Heap.beg;                                    // from the beginning of the Heap
        (new < Heap.end) && (new->full||(new->size<size));  // while end not reached and no space
        new += new->size);                                  // go to next block
    if (new >= Heap.end) return NULL;                       // end reached without finding space
    new->full = 1;                                          // space found, we put the block
    oldnext = new + new->size;                              // next block address before the cut
    newnext = LINE_CEIL(new+size);                          // find the new next block
    if (newnext != oldnext) {                               // if we need to cut the find block
        new->size = newnext - new;                          // new size of current block
        new->magic = MAGIC_HEAP;                            // to try detect Heap corruption
        newnext->size = oldnext - newnext;                  // new size of remaining space
        newnext->full = 0;                                  // that is free space
        newnext->magic = MAGIC_HEAP;                        // to try detect Heap corruption
    }
    return (void *)(new + 1);                               // the allocated block after block_info
}
References heap_s::beg, BINFO_SZ, CacheLineSize, CEIL, heap_s::end, block_info_s::full, Heap, LINE_CEIL, block_info_s::magic, MAGIC_HEAP, NULL, and block_info_s::size.
Referenced by malloc().
Variable Documentation
CacheLineSize
size_t CacheLineSize static
Referenced by malloc_init(), and try_malloc().
Heap
struct heap_s Heap static
Referenced by malloc(), malloc_init(), malloc_print(), merge(), and try_malloc().