ko6: src/soft/ulib/memory.h File Reference
memory.h File Reference
Functions
void sbrk_s (void)
void * sbrk (int increment)
change the boundary of heap
void malloc_print (size_t level)
print the heap state
void malloc_init (void *start)
Heap initialiation, called only once before to call the main() fonction.
void * malloc (unsigned size)
Try to find a free object large enough, if none, merge free segments and try again.
void free (void *ptr)
free an allocated object with malloc(), object is not erased.
Function Documentation
free()
void free (void * ptr)
free an allocated object with malloc(), object is not erased.
Parameters
ptr previously allocated object pointer
{
    block_info_t *info = (block_info_t *)ptr - 1;           // block_info is just before ptr
    if (!ptr || !info->full || (info->magic != MAGIC_HEAP)) // pt NULL OR segment free OR not MAGIC
        exit(1);                                            // memory corrupted
    info->full = 0;                                         // erase the full flag
}
References exit(), block_info_s::full, block_info_s::magic, and MAGIC_HEAP.
Referenced by build(), and split().
malloc()
void * malloc (unsigned size)
Try to find a free object large enough, if none, merge free segments and try again.
Parameters
size number of bytes asked
Returns
A pointer of the allocated object or NULL if there is not place anymore.
malloc_init()
void malloc_init (void * start)
Heap initialiation, called only once before to call the main() fonction.
Parameters
start address of the first byte
{
    CacheLineSize = cachelinesize();                        // need to know the cache line size
    int *end = sbrk (4* PAGE_SIZE);                         // try to get 4 pages (16ko)
    if (end == (int *)-1) exit (2);                         // if impossible exit the app
    Heap.beg = LINE_FLOOR (beg);                            // address of the first BLOCK
    Heap.end = LINE_FLOOR (end);                            // address of the boundary
    Heap.beg->full = 0;                                     // empty at the begining
    Heap.beg->magic = MAGIC_HEAP;                           // to try detect Heap corruption
    Heap.beg->size = Heap.end - Heap.beg;                   // size of free space
    CacheLineSize = cachelinesize();                        // ask the kernel for cache line size
}
References heap_s::beg, cachelinesize(), CacheLineSize, heap_s::end, exit(), block_info_s::full, Heap, LINE_FLOOR, block_info_s::magic, MAGIC_HEAP, PAGE_SIZE, sbrk(), and block_info_s::size.
Referenced by _start().
malloc_print()
void malloc_print (size_t level)
print the heap state
Parameters
level use: 0 = full/free bytes; 1 = the nb of blocks full/free per size; 2 = all details
{
    block_info_t *ptr;
    fprintf (0, "------------ %p ------------\n", Heap.beg);
    for (ptr = Heap.beg; ptr < Heap.end; ptr += ptr->size)  // browse all blocks
        fprintf (0, " %s  [ %x\t- %x\t] = %d\n",
            (ptr->full) ? "full" : "free",                  // print if block is full or free
            BINFO_SZ*(size_t)(ptr - Heap.beg),              // print block begin position
            BINFO_SZ*(size_t)((ptr + ptr->size) - Heap.beg),// print block end position
            BINFO_SZ*(size_t)(ptr->size));                  // print block size
    fprintf (0, "------------ %p ------------\n", Heap.end);
}
References heap_s::beg, BINFO_SZ, heap_s::end, fprintf(), block_info_s::full, Heap, and block_info_s::size.
sbrk()
void * sbrk (int increment)
change the boundary of heap
Parameters
increment is the signed number of bytes , which will be aligned on a cache line
Returns
new end address of the heap, (increment=0) gives the current one, returns -1 on failure
change the boundary of heap
Parameters
increment integer added to the current heap boundary
Returns
SUCCESS or FAILURE
{
    errno = SUCCESS;
    int * a = _usermem.uheap_end + increment/sizeof(int);   // sizeof() because uheap_end is int*
    a = (int *) FLOOR (a, CacheLineSize);                   // addr 'a' could be the new uheap_end
    if ((a<_usermem.uheap_beg)||(a>_usermem.ustack_end)){  // if it is outside the heap zone
        errno = ENOMEM;
        return (void *)-1;                                  // -1 on failure
    }
    return a;                                               // else return a;
}
References _usermem, CacheLineSize, ENOMEM, errno, FLOOR, sbrk_s(), SUCCESS, syscall_fct(), SYSCALL_SBRK, _usermem_s::uheap_beg, _usermem_s::uheap_end, and _usermem_s::ustack_end.
Referenced by malloc_init().
sbrk_s()
void sbrk_s (void)
TODO: ask about this
Referenced by sbrk().