ko6: src/soft/hal/devices/chardev/ns16550.c File Reference
ns16550.c File Reference
#include <hal/devices/chardev/ns16550.h>
Functions
static void ns16550_init (struct chardev_s *cdev, unsigned address, unsigned baudrate)
NS16550 UART initialization The procedure is the following:
static int ns16550_read (struct chardev_s *cdev, char *buf, unsigned count)
Read a buffer from the NS16550 UART.
static int ns16550_write (struct chardev_s *cdev, char *buf, unsigned count)
Write in the UART.
void ns16550_isr (unsigned irq, struct chardev_s *cdev)
Interrupt Service Routine for NS16550 UART The ISR push received character into the software fifo (cdev->fifo)
Variables
struct chardev_ops_s NS16550Ops
Function Documentation
ns16550_init()
static void ns16550_init (struct chardev_s * cdev, unsigned address, unsigned baudrate) static
NS16550 UART initialization The procedure is the following:
Init the baudrate through de DLAB registers
Configure register: 8bits word, no parity check, 1 stop bit
Enable interrupts
Disable FIFO
Parameters
cdev the char device
address the base NS16550 MMIO address
baudrate the baudrate of the UART
Can't find it elsewhere but xv6 assume a 1843200hz frequency for the uart TODO: handle the PSD register
Enable only the interrupt that tells us we receive a character TODO: in the future, we could also manage de THR Empty interrupt
{
    cdev->ops        = &NS16550Ops;
    cdev->address    = address;
    cdev->baudrate   = baudrate;
    struct fifo_s *fifo = kmalloc(sizeof(struct fifo_s));
    cdev->driver_data = (void*) fifo;
    volatile struct ns16550_general_regs_s *gregs =
        (struct ns16550_general_regs_s *) address;
    volatile struct ns16550_dlab_regs_s *dregs =
        (struct ns16550_dlab_regs_s *) address;
    /* Set baudrate */
    gregs->lcr |= NS16550_ENABLE_DLAB;
    unsigned short dl = 1843200 / (16 * baudrate);
    dregs->dll = dl & 0xff;
    dregs->dlm = (dl & 0xff00) >> 8;
    /* 8 bits word length, no parity */
    gregs->lcr = NS16550_WORD_LENGTH_8;
    gregs->ier = NS16550_INT_DATA_READY;
    /* Disable hardware FIFO */
    gregs->fcr = 0;
}
References chardev_s::address, chardev_s::baudrate, ns16550_dlab_regs_s::dll, ns16550_dlab_regs_s::dlm, chardev_s::driver_data, ns16550_general_regs_s::fcr, ns16550_general_regs_s::ier, kmalloc(), ns16550_general_regs_s::lcr, NS16550_ENABLE_DLAB, NS16550_INT_DATA_READY, NS16550_WORD_LENGTH_8, NS16550Ops, and chardev_s::ops.
ns16550_isr()
void ns16550_isr (unsigned irq, struct chardev_s * cdev)
Interrupt Service Routine for NS16550 UART The ISR push received character into the software fifo (cdev->fifo)
Parameters
irq the irq linked to this ISR
cdev the device linked to this ISR
{
    volatile struct ns16550_general_regs_s *regs =
        (struct ns16550_general_regs_s *) cdev->address;
    struct fifo_s *fifo = (struct fifo_s *) cdev->driver_data;
    char c = regs->hr;
    fifo_push(fifo, c);
}
References chardev_s::address, chardev_s::driver_data, fifo_push(), and ns16550_general_regs_s::hr.
Referenced by soc_tty_init().
ns16550_read()
static int ns16550_read (struct chardev_s * cdev, char * buf, unsigned count) static
Read a buffer from the NS16550 UART.
Parameters
cdev the chardev device corresponding to the NS16550
buf the buf to fill
count number of bytes to read from the UART
Returns
number of bytes read
{
    int res = 0;
    int c;
    struct fifo_s *fifo = (struct fifo_s *) cdev->driver_data;
    while (count--) {
        while (fifo_pull(fifo, &c) == FAILURE) {                // wait for a char from the keyboard
            thread_yield();                                     // nothing then we yield the processor
            irq_enable();                                       // get few characters if thread is alone
            irq_disable();                                      // close enter
        }
        *buf++ = c;
        res++;
    }
    return res;                                                 // return the number of char read
}
References chardev_s::driver_data, FAILURE, fifo_pull(), irq_disable(), irq_enable(), and thread_yield().
ns16550_write()
static int ns16550_write (struct chardev_s * cdev, char * buf, unsigned count) static
Write in the UART.
Parameters
cdev the device struct corresponding to the UART
buf the buffer to write
count number of bytes to write
Returns
number of bytes written
{
    int res = 0;                                        // nb of written char
    volatile struct ns16550_general_regs_s *regs =
        (struct ns16550_general_regs_s *) cdev->address;// access the registers
    while (count--) {                                   // while there are chars
        regs->hr = *buf;                                // send the char to TTY
        res++;                                          // nb of written char
        buf++;                                          // but is the next address in buffer
    }
    return res;
}
References chardev_s::address, and ns16550_general_regs_s::hr.
Variable Documentation
NS16550Ops
struct chardev_ops_s NS16550Ops
Initial value:
= {
    .chardev_init = ns16550_init,
    .chardev_read = ns16550_read,
    .chardev_write = ns16550_write
}
Referenced by ns16550_init(), and soc_tty_init().