ko6: src/soft/hal/soc/soc.h File Reference
soc.h File Reference
Functions
int soc_init (void *fdt, int tick)
Request the initialization of all the architecture of the SOC This function configures each used devices and configures which IRQ are used and how they are connected to the CPU thanks to the ICU Mask.
Function Documentation
soc_init()
int soc_init (void * fdt, int tick)
Request the initialization of all the architecture of the SOC This function configures each used devices and configures which IRQ are used and how they are connected to the CPU thanks to the ICU Mask.
Parameters
fdt is the pointer to the flattened device tree
tick is the time in cycles between to IRQ for the timer
Returns
-1 if initialization fails, else 0
Request the initialization of all the architecture of the SOC This function configures each used devices and configures which IRQ are used and how they are connected to the CPU thanks to the ICU Mask.
There are at most 14 IRQs for almo1, but the real number depends of the prototype paramaters There are as many timers as CPU, thus NCPUS timers There are Nicus ttys There are also a DMA to perfom memcpy and optionnal Block Device (hard drive)
Device IRQs are wired as following:
ICU.PIN [0] : timer 0 " " " depending on NCPUS (0 to 7) * ICU.PIN [7] : timer 7 * ICU.PIN [8] : bd Bloc Device (Hard Drive) * ICU.PIN [9] : dma Direct Memory Access (Hard memcpy) * ICU.PIN [10] : TTY0 TTY n'0 " " " depending on NTTYS (0 to 3)
ICU.PIN [13] : TTY3
Parameters
tick number of ticks between two timer interrupts
Returns
-1 if the initialization failed, 0 if it succeeded
Request the initialization of all the architecture of the SOC This function configures each used devices and configures which IRQ are used and how they are connected to the CPU thanks to the ICU Mask.
Parameters
tick number of ticks between two timer interrupts
Returns
-1 if the initialization failed, 0 if it succeeded
{
    if (fdt_magic(fdt) != 0xd00dfeed)
        return -1;
    // We MUST initialize the ICU first since every other device
    // initialization will rely on it for its interrupts
    soc_icu_init(fdt);
    // Initialize TTY early so we can debug as soon as possible
    if (soc_tty_init(fdt) < 0)
        return -1;
    soc_dma_init(fdt);
    // Finish by the timer (we don't want to schedule anything until everything
    // is initialized)
    if (soc_timer_init(fdt, tick) < 0)
        return -1;
    return 0;
}
References fdt_magic, soc_dma_init(), soc_icu_init(), soc_timer_init(), and soc_tty_init().
Referenced by kinit().