ko6: src/soft/hal/devices/chardev/soclib-tty.c File Reference
soclib-tty.c File Reference
#include <hal/devices/chardev/soclib-tty.h>
Functions
static void soclib_tty_init (struct chardev_s *cdev, unsigned address, unsigned baudrate)
Init the soclib tty device.
static int soclib_tty_read (struct chardev_s *cdev, char *buf, unsigned count)
Read a buffer from the soclib tty.
static int soclib_tty_write (struct chardev_s *cdev, char *buf, unsigned count)
Write in the TTY.
void soclib_tty_isr (unsigned irq, struct chardev_s *cdev)
ISR for the soclib tty device The only interrupt handled is the one raised when a character is received by the tty device.
Variables
struct chardev_ops_s SoclibTTYOps
Function Documentation
soclib_tty_init()
static void soclib_tty_init (struct chardev_s * cdev, unsigned address, unsigned baudrate) static
Init the soclib tty device.
Parameters
cdev soclib device
address the soclib tty address
baudrate the soclib tty baudrate (unused for this device)
Returns
nothing
{
    cdev->ops        = &SoclibTTYOps;
    cdev->address    = address;
    cdev->baudrate   = baudrate;
    struct fifo_s *fifo = kmalloc(sizeof(struct fifo_s));
    cdev->driver_data = (void*) fifo;
}
References chardev_s::address, chardev_s::baudrate, chardev_s::driver_data, kmalloc(), chardev_s::ops, and SoclibTTYOps.
soclib_tty_isr()
void soclib_tty_isr (unsigned irq, struct chardev_s * cdev)
ISR for the soclib tty device The only interrupt handled is the one raised when a character is received by the tty device.
Parameters
irq the irq linked to this isr
cdev the device linked to this isr
Returns
nothing
{
    struct soclib_tty_regs_s *regs =
        (struct soclib_tty_regs_s *) cdev->address;
    struct fifo_s *fifo = (struct fifo_s *) cdev->driver_data;
    char c = regs->read;
    fifo_push(fifo, c);
}
References chardev_s::address, chardev_s::driver_data, fifo_push(), and soclib_tty_regs_s::read.
Referenced by soc_tty_init().
soclib_tty_read()
static int soclib_tty_read (struct chardev_s * cdev, char * buf, unsigned count) static
Read a buffer from the soclib tty.
Parameters
cdev the chardev device corresponding to the soclib tty
buf the buf to fill
count number of bytes to read from the tty
Returns
number of bytes written
{
    int res = 0;                                        // nb of read char
    int c;                                              // char read
    struct fifo_s *fifo = (struct fifo_s *) cdev->driver_data;
    while (count--) {
        while (fifo_pull(fifo, &c) == FAILURE) {  // wait for a char from the keyboard
            thread_yield();                                 // nothing then we yield the processor
            irq_enable();                                   // get few characters if thread is alone
            irq_disable();                                  // close enter
        }
        *buf++ = c;
        res++;
    }
    return res;                                         // return the number of char read
}
References chardev_s::driver_data, FAILURE, fifo_pull(), irq_disable(), irq_enable(), and thread_yield().
soclib_tty_write()
static int soclib_tty_write (struct chardev_s * cdev, char * buf, unsigned count) static
Write in the TTY.
Parameters
cdev the device struct corresponding to the tty
buf the buffer to write
count number of bytes to write
Returns
number of bytes written
{
    int res = 0;                                        // nb of written char
    struct soclib_tty_regs_s *regs =
        (struct soclib_tty_regs_s *) cdev->address;     // access the registers
    while (count--) {                                   // while there are chars
        regs->write = *buf;                             // send the char to TTY
        delay(150);
        res++;                                          // nb of written char
        buf++;                                          // but is the next address in buffer
    }
    return res;
}
References chardev_s::address, delay(), and soclib_tty_regs_s::write.
Variable Documentation
SoclibTTYOps
struct chardev_ops_s SoclibTTYOps
Initial value:
= {
    .chardev_init = soclib_tty_init,
    .chardev_read = soclib_tty_read,
    .chardev_write = soclib_tty_write
}
Referenced by soc_tty_init(), and soclib_tty_init().