ko6: src/soft/hal/devices/timer/soclib-timer.c File Reference
soclib-timer.c File Reference
#include <hal/devices/timer/soclib-timer.h>
#include <kernel/klibc.h>
Functions
static void soclib_timer_set_tick (struct timer_s *timer, unsigned tick)
Set the number of ticks between two soclib timer interrupts.
static void soclib_timer_init (struct timer_s *timer, unsigned address, unsigned tick)
soclib timer initialization
static void soclib_timer_set_event (struct timer_s *timer, void(*f)(void *arg), void *arg)
Set the event that will triggered by a soclib timer interrupt.
void soclib_timer_isr (unsigned irq, struct timer_s *timer)
ISR of the soclib timer device.
Variables
struct timer_ops_s SoclibTimerOps
Function Documentation
soclib_timer_init()
static void soclib_timer_init (struct timer_s * timer, unsigned address, unsigned tick) static
soclib timer initialization
Parameters
timer timer device to initialize
address address of the device
tick number of ticks between two interrupts
Returns
nothing
{
    timer->address  = address;
    timer->ops      = &SoclibTimerOps;
    struct soclib_timer_regs_s *regs =
        (struct soclib_timer_regs_s *) timer->address;
    regs->resetirq = 1;                                 // to be sure there won't be a IRQ when timer start
    soclib_timer_set_tick(timer, tick);                 // next period
    regs->mode = (tick) ? 3 : 0;                        // timer ON with IRQ only if (tick != 0)
}
References timer_s::address, soclib_timer_regs_s::mode, timer_s::ops, soclib_timer_regs_s::resetirq, soclib_timer_set_tick(), and SoclibTimerOps.
soclib_timer_isr()
void soclib_timer_isr (unsigned irq, struct timer_s * timer)
ISR of the soclib timer device.
Parameters
irq irq linked to the ISR
timer device linked to the ISR
Returns
nothing
{
    struct soclib_timer_regs_s *regs =
        (struct soclib_timer_regs_s *) timer->address;
    /* IRQ acknoledgement to lower the interrupt signal */
    regs->resetirq = 1;
    if (timer->event.f)
        timer->event.f(timer->event.arg);
}
References timer_s::address, timer_event_s::arg, timer_s::event, timer_event_s::f, and soclib_timer_regs_s::resetirq.
Referenced by soc_timer_init().
soclib_timer_set_event()
static void soclib_timer_set_event (struct timer_s * timer, void(*)(void *arg) f, void * arg) static
Set the event that will triggered by a soclib timer interrupt.
Parameters
timer the timer device
f the function corresponding to the event
arg argument that will be passed to the function
Returns
nothing
{
    timer->event.f = f;
    timer->event.arg = arg;
}
References timer_event_s::arg, timer_s::event, and timer_event_s::f.
soclib_timer_set_tick()
static void soclib_timer_set_tick (struct timer_s * timer, unsigned tick) static
Set the number of ticks between two soclib timer interrupts.
Parameters
timer timer device
tick number of ticks
Returns
nothing
{
    struct soclib_timer_regs_s *regs =
        (struct soclib_timer_regs_s *) timer->address;
    regs->period = tick;
}
References timer_s::address, and soclib_timer_regs_s::period.
Referenced by soclib_timer_init().
Variable Documentation
SoclibTimerOps
struct timer_ops_s SoclibTimerOps
Initial value:
= {
    .timer_init = soclib_timer_init,
    .timer_set_event = soclib_timer_set_event,
    .timer_set_tick = soclib_timer_set_tick
}
Referenced by soc_timer_init(), and soclib_timer_init().