ko6: timer_event_s Struct Reference
timer_event_s Struct Reference
Structure describing what to do when we receive a timer interrupt.
#include <timer.h>
Public Attributes
void(* f)(void *arg)
void * arg
Detailed Description
Structure describing what to do when we receive a timer interrupt.
Member Data Documentation
arg
void* timer_event_s::arg
Referenced by clint_timer_isr(), clint_timer_set_event(), soclib_timer_isr(), and soclib_timer_set_event().
f
void(* timer_event_s::f) (void *arg)
Referenced by clint_timer_isr(), clint_timer_set_event(), soclib_timer_isr(), and soclib_timer_set_event().
The documentation for this struct was generated from the following file:
src/soft/hal/devices/timer.h