ko6: timer_ops_s Struct Reference
timer_ops_s Struct Reference
Functions prototypes of the timer device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
#include <timer.h>
Public Attributes
void(* timer_init)(struct timer_s *timer, unsigned address, unsigned tick)
Generic function to initialize the timer device.
void(* timer_set_tick)(struct timer_s *timer, unsigned tick)
Generic function that allows the kernel to set the number of ticks after which we want an interrupt.
void(* timer_set_event)(struct timer_s *timer, void(*f)(void *arg), void *arg)
Generic function that sets the event that will be triggered after a timer interrupt.
Detailed Description
Functions prototypes of the timer device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
Member Data Documentation
timer_init
void(* timer_ops_s::timer_init) (struct timer_s *timer, unsigned address, unsigned tick)
Generic function to initialize the timer device.
Parameters
address the base address of the memory-mapped registers
tick number of ticks between to timer interrupts
Referenced by soc_timer_init().
timer_set_event
void(* timer_ops_s::timer_set_event) (struct timer_s *timer, void(*f)(void *arg), void *arg)
Generic function that sets the event that will be triggered after a timer interrupt.
Parameters
timer the timer device
f the function to be called
arg the arg passed to the function
Referenced by soc_timer_init().
timer_set_tick
void(* timer_ops_s::timer_set_tick) (struct timer_s *timer, unsigned tick)
Generic function that allows the kernel to set the number of ticks after which we want an interrupt.
Parameters
timer the timer device
tick the number of ticks
Referenced by clint_timer_isr().
The documentation for this struct was generated from the following file:
src/soft/hal/devices/timer.h