ko6: chardev_ops_s Struct Reference
chardev_ops_s Struct Reference
Functions prototypes of character device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
#include <chardev.h>
Public Attributes
void(* chardev_init)(struct chardev_s *chardev, unsigned address, unsigned baudrate)
Generic function that initialize the chardev device.
int(* chardev_write)(struct chardev_s *chardev, char *buf, unsigned count)
Generic function that write to the chardev device.
int(* chardev_read)(struct chardev_s *chardev, char *buf, unsigned count)
Generic function that reads from the chardev device.
Detailed Description
Functions prototypes of character device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
Member Data Documentation
chardev_init
void(* chardev_ops_s::chardev_init) (struct chardev_s *chardev, unsigned address, unsigned baudrate)
Generic function that initialize the chardev device.
Parameters
chardev the char device
address base address of the device memory-mapped registers
baudrate the device baudrate
Referenced by soc_tty_init().
chardev_read
int(* chardev_ops_s::chardev_read) (struct chardev_s *chardev, char *buf, unsigned count)
Generic function that reads from the chardev device.
Parameters
chardev the chardev device
buf the buffer that will receive the data from the chardev
count the number of bytes that should be written into the buffer
Returns
number of bytes actually read
Referenced by tty_read().
chardev_write
int(* chardev_ops_s::chardev_write) (struct chardev_s *chardev, char *buf, unsigned count)
Generic function that write to the chardev device.
Parameters
chardev the chardev device
buf the buffer to write to the chardev
count the number of bytes to write
Returns
number of bytes actually written
Referenced by tty_write().
The documentation for this struct was generated from the following file:
src/soft/hal/devices/chardev.h