ko6: icu_ops_s Struct Reference
icu_ops_s Struct Reference
Functions prototypes of the ICU device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
#include <icu.h>
Public Attributes
void(* icu_init)(struct icu_s *icu, unsigned address)
Generic function to initialize the ICU device.
unsigned(* icu_get_highest)(struct icu_s *icu)
Generic function that fetch the highest priority IRQ from the ICU device.
void(* icu_set_priority)(struct icu_s *icu, unsigned irq, unsigned pri)
Generic function that sets the priority of a given IRQ.
void(* icu_acknowledge)(struct icu_s *icu, unsigned irq)
Generic function that should aknowledge an IRQ.
void(* icu_mask)(struct icu_s *icu, unsigned irq)
Generic function that mask (disable) an IRQ.
void(* icu_unmask)(struct icu_s *icu, unsigned irq)
Generic function that unmask (enable) an IRQ.
Detailed Description
Functions prototypes of the ICU device, they should be implemented by a device driver. They serve as an interface between the kernel and the driver.
Member Data Documentation
icu_acknowledge
void(* icu_ops_s::icu_acknowledge) (struct icu_s *icu, unsigned irq)
Generic function that should aknowledge an IRQ.
Parameters
icu the icu device
irq the irq to acknowledge
Referenced by isrcall().
icu_get_highest
unsigned(* icu_ops_s::icu_get_highest) (struct icu_s *icu)
Generic function that fetch the highest priority IRQ from the ICU device.
Parameters
icu the icu device
Returns
highest priority IRQ
Referenced by isrcall().
icu_init
void(* icu_ops_s::icu_init) (struct icu_s *icu, unsigned address)
Generic function to initialize the ICU device.
Parameters
address the base address of the memory-mapped registers
Referenced by soc_icu_init().
icu_mask
void(* icu_ops_s::icu_mask) (struct icu_s *icu, unsigned irq)
Generic function that mask (disable) an IRQ.
Parameters
icu the icu device
irq the irq to mask
icu_set_priority
void(* icu_ops_s::icu_set_priority) (struct icu_s *icu, unsigned irq, unsigned pri)
Generic function that sets the priority of a given IRQ.
Parameters
icu the icu device
irq the irq
pri the new priority of the IRQ
Referenced by soc_tty_init().
icu_unmask
void(* icu_ops_s::icu_unmask) (struct icu_s *icu, unsigned irq)
Generic function that unmask (enable) an IRQ.
Parameters
icu the icu device
irq the irq to unmask
Referenced by soc_timer_init(), and soc_tty_init().
The documentation for this struct was generated from the following file:
src/soft/hal/devices/icu.h