ko6: src/soft/common/syscalls.h File Reference
syscalls.h File Reference
Macros
#define SYSCALL_EXIT 0
#define SYSCALL_READ 1
#define SYSCALL_WRITE 2
#define SYSCALL_CLOCK 3
#define SYSCALL_DMA_MEMCPY 4
#define SYSCALL_CACHELINESIZE 5
#define SYSCALL_DCACHEBUFINVAL 6
#define SYSCALL_DCACHEINVAL 7
#define SYSCALL_SBRK 8
#define SYSCALL_ERRNO 9
#define SYSCALL_THREAD_CREATE 10
#define SYSCALL_THREAD_YIELD 11
#define SYSCALL_THREAD_EXIT 12
#define SYSCALL_SCHED_DUMP 13
#define SYSCALL_THREAD_JOIN 14
#define SYSCALL_MUTEX_INIT 15
#define SYSCALL_MUTEX_LOCK 16
#define SYSCALL_MUTEX_UNLOCK 17
#define SYSCALL_MUTEX_DESTROY 18
#define SYSCALL_BARRIER_INIT 19
#define SYSCALL_BARRIER_WAIT 20
#define SYSCALL_BARRIER_DESTROY 21
#define SYSCALL_NR 32
Functions
int syscall_fct (int a0, int a1, int a2, int a3, int syscall_code)
allows to enter the kernel, it is written in assembler in crt0.c
Macro Definition Documentation
SYSCALL_BARRIER_DESTROY
#define SYSCALL_BARRIER_DESTROY 21
SYSCALL_BARRIER_INIT
#define SYSCALL_BARRIER_INIT 19
SYSCALL_BARRIER_WAIT
#define SYSCALL_BARRIER_WAIT 20
SYSCALL_CACHELINESIZE
#define SYSCALL_CACHELINESIZE 5
SYSCALL_CLOCK
#define SYSCALL_CLOCK 3
SYSCALL_DCACHEBUFINVAL
#define SYSCALL_DCACHEBUFINVAL 6
SYSCALL_DCACHEINVAL
#define SYSCALL_DCACHEINVAL 7
SYSCALL_DMA_MEMCPY
#define SYSCALL_DMA_MEMCPY 4
SYSCALL_ERRNO
#define SYSCALL_ERRNO 9
SYSCALL_EXIT
#define SYSCALL_EXIT 0
SYSCALL_MUTEX_DESTROY
#define SYSCALL_MUTEX_DESTROY 18
SYSCALL_MUTEX_INIT
#define SYSCALL_MUTEX_INIT 15
SYSCALL_MUTEX_LOCK
#define SYSCALL_MUTEX_LOCK 16
SYSCALL_MUTEX_UNLOCK
#define SYSCALL_MUTEX_UNLOCK 17
SYSCALL_NR
#define SYSCALL_NR 32
SYSCALL_READ
#define SYSCALL_READ 1
SYSCALL_SBRK
#define SYSCALL_SBRK 8
SYSCALL_SCHED_DUMP
#define SYSCALL_SCHED_DUMP 13
SYSCALL_THREAD_CREATE
#define SYSCALL_THREAD_CREATE 10
SYSCALL_THREAD_EXIT
#define SYSCALL_THREAD_EXIT 12
SYSCALL_THREAD_JOIN
#define SYSCALL_THREAD_JOIN 14
SYSCALL_THREAD_YIELD
#define SYSCALL_THREAD_YIELD 11
SYSCALL_WRITE
#define SYSCALL_WRITE 2
Function Documentation
syscall_fct()
int syscall_fct (int a0, int a1, int a2, int a3, int syscall_code)
allows to enter the kernel, it is written in assembler in crt0.c
ASSEMBLER is automatically defined when gcc runs the assembler (.S source file) (see https://bit.ly/32tv7u8) thus this part is not included in assembler files (.S)
Parameters
a0 1st generic parameter
a1 2nd generic parameter
a2 3rd generic parameter
a3 4th generic parameter
syscall_code syscall code must be one of those defined above : SYSCALL_xxx
Returns
depends on the syscall code but often it is the success information: 0 good else failure
Referenced by cachelinesize(), clock(), dcache_buf_inval(), dcache_inval(), exit(), pthread_barrier_destroy(), pthread_barrier_init(), pthread_barrier_wait(), pthread_create(), pthread_exit(), pthread_join(), pthread_mutex_destroy(), pthread_mutex_init(), pthread_mutex_lock(), pthread_mutex_unlock(), pthread_yield(), read(), sbrk(), sched_dump(), and write().