ko6: src/soft/hal/cpu/thread.h File Reference
thread.h File Reference
Functions
void thread_context_init (int context[], void *bootstrap, void *stack_pointer)
Initialize the thread context at the very beginning.
int thread_context_save (int context[])
kernel saves the given thread registers in the context table
int thread_context_load (int context[])
kernel load the given thread registers from the context table
int thread_launch (int fun, int arg, int start)
The kernel starts any thread for the very first time with this function. This function is called by the static function thread_bootstrap() (in kthread.c) which is the real beginning of a thread, and thread_bootstrap() is called by the first call of thread_load() for each thread (see comment of thread_bootstrat in kthread.c for more details)
Function Documentation
thread_context_init()
void thread_context_init (int context[], void * bootstrap, void * stack_pointer)
Initialize the thread context at the very beginning.
Parameters
context thread_context table
bootstrap function without any argument, used just after the 1st thread_context_load
stack_pointer top stack pointer at the very beginning
Returns
side effect on the given thread context table
mstatus of a user-thread should have: mstatus.MPIE = 0 (we don't want interrupts when we go back in M-mode) mstatus.MPP = M-mode (we want to go back in m-mode) mstatus.MIE = 1 (interrupts are enabled)
{
    context[TH_CONTEXT_SR] = 0x413;                 // UM=1 EXL=1 IE=1
    context[TH_CONTEXT_RA] = (int)bootstrap;        // goto thread_bootstrap
    context[TH_CONTEXT_SP] = (int)stack_pointer;    // stack beginning
}
References TH_CONTEXT_MSTATUS, TH_CONTEXT_RA, TH_CONTEXT_SP, and TH_CONTEXT_SR.
Referenced by thread_create().
thread_context_load()
int thread_context_load (int context[])
kernel load the given thread registers from the context table
Parameters
context thread_context table of the thread to load (or to restore)
Returns
returns alway 0 (false)
Referenced by sched_switch(), and thread_main_load().
thread_context_save()
int thread_context_save (int context[])
kernel saves the given thread registers in the context table
Parameters
context thread_context table of the thread to save
Returns
it returns two values depending on how this function has been called. First case, the simplest, we call thread_save () then it returns 1 (true). Secondly, we call thread_restore() (see bellow) that causes the restoration of all registers recorded by thread_save(), including $31, thus when we return from thread_load(), in reality, we return from thread_save, but with 0 (false) as return value.
Referenced by sched_switch().
thread_launch()
int thread_launch (int fun, int arg, int start)
The kernel starts any thread for the very first time with this function. This function is called by the static function thread_bootstrap() (in kthread.c) which is the real beginning of a thread, and thread_bootstrap() is called by the first call of thread_load() for each thread (see comment of thread_bootstrat in kthread.c for more details)
Parameters
fun ptr to the function of the thread, type: void*(fun)(void) but cast to int
arg the argument given to fun(), type: void* but cast to int
start ptr to the user function which calls fun(arg) for real, type is cast to int In fact, start has two possible types. If it is the main thread then it is : void (*start) (void) but if it is a standard thread then it is : void (*start) (void *(*fun) (void *), void *arg)
Returns
never returns
Referenced by thread_bootstrap().