name: doxygen deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages
          folder: docs/html
          target_folder: doxydocs
          config_file: docs/doxygen/doxygen.cfg
          doxygen_version: 1.9.6